Imports

In [1]:
import pandas as pd
import re

Load Data

In [2]:
from google.colab import files
uploaded = files.upload()
df = pd.read_csv('dubizzle_phones_clean.csv')

Saving dubizzle_phones_clean.csv to dubizzle_phones_clean.csv

Dataset Shape

In [3]:
print("Dataset shape:", df.shape)

Dataset shape: (8213, 30)

Dataset Columns

In [4]:
print("Columns names:\n", df.columns.to_list())

Columns names:
 ['title', 'price', 'location', 'ad_url', 'ad_id', 'run_id', 'brand', 'storage_gb', 'ram_gb', 'storage_src', 'condition', 'condition_src', 'ram_src', 'has_5g', 'has_warranty', 'has_box', 'mentions_exchange', 'is_wanted_ad', 'is_accessory_hint', 'is_tablet_hint', 'is_parts_hint', 'accessory_first', 'bundle_hint', 'is_feature_phone_hint', 'price_placeholder', 'loc_area', 'loc_city', 'price_missing', 'price_suspicious', 'price_very_high']

In [5]:
print("Number of columns:", len(df.columns))

Number of columns: 30

In [6]:
df.head()

,title,price,location,ad_url,ad_id,run_id,brand,storage_gb,ram_gb,storage_src,...,is_parts_hint,accessory_first,bundle_hint,is_feature_phone_hint,price_placeholder,loc_area,loc_city,price_missing,price_suspicious,price_very_high
0,ايفون 13 iPhone,19500.0,مساكن المهندسين، مدينة نصر,/ad/%D8%A7%D9%8A%D9%81%D9%88%D9%86-13-iphone-I...,208854767,legacy,apple,NaN,NaN,NaN,...,False,False,False,False,False,مساكن المهندسين,مدينة نصر,False,False,False
1,Honor Magic V5,80000.0,اوبن اير مول، مدينتي,/ad/honor-magic-v5-ID209010621.html,209010621,legacy,honor,NaN,NaN,NaN,...,False,False,False,False,False,اوبن اير مول,مدينتي,False,False,False
2,OPPO Find X9 Pro ضمان محلي للبيع او البدل,57999.0,سموحة، الإسكندرية,/ad/oppo-find-x9-pro-%D8%B6%D9%85%D8%A7%D9%86-...,209003975,legacy,oppo,NaN,NaN,NaN,...,False,False,False,False,False,سموحة,الإسكندرية,False,False,False
3,Honor Robot Phone 512G 12G ram,94000.0,مدينة نصر، القاهرة,/ad/honor-robot-phone-512g-12g-ram-ID208841945...,208841945,legacy,honor,512.0,12.0,L1:unit,...,False,False,False,False,False,مدينة نصر,القاهرة,False,False,False
4,شاومي 17 الترا xiaomi 17 ultra,70000.0,التجمع الخامس، القاهرة الجديدة,/ad/%D8%B4%D8%A7%D9%88%D9%85%D9%8A-17-%D8%A7%D...,208281312,legacy,xiaomi,NaN,NaN,NaN,...,False,False,False,False,False,التجمع الخامس,القاهرة الجديدة,False,False,False

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8213 entries, 0 to 8212
Data columns (total 30 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   title                  8213 non-null   object
 1   price                  8213 non-null   float64
 2   location               8207 non-null   object
 3   ad_url                 8213 non-null   object
 4   ad_id                  8213 non-null   int64
 5   run_id                 8213 non-null   object
 6   brand                  7772 non-null   object
 7   storage_gb             586 non-null    float64
 8   ram_gb                 177 non-null    float64
 9   storage_src            586 non-null    object
 10  condition              439 non-null    object
 11  condition_src          439 non-null    object
 12  ram_src                177 non-null    object
 13  has_5g                 8213 non-null   bool
 14  has_warranty           8213 non-null   bool
 15  has_box                8213 non-null   bool
 16  mentions_exchange      8213 non-null   bool
 17  is_wanted_ad           8213 non-null   bool
 18  is_accessory_hint      8213 non-null   bool
 19  is_tablet_hint         8213 non-null   bool
 20  is_parts_hint          8213 non-null   bool
 21  accessory_first        8213 non-null   bool
 22  bundle_hint            8213 non-null   bool
 23  is_feature_phone_hint  8213 non-null   bool
 24  price_placeholder      8213 non-null   bool
 25  loc_area               8207 non-null   object
 26  loc_city               8207 non-null   object
 27  price_missing          8213 non-null   bool
 28  price_suspicious       8213 non-null   bool
 29  price_very_high        8213 non-null   bool
dtypes: bool(15), float64(3), int64(1), object(11)
memory usage: 1.1+ MB

In [8]:
df.isna().sum().to_frame("Missing Values")

                       Missing Values
title                               0
price                               0
location                            6
ad_url                              0
ad_id                               0
run_id                              0
brand                             441
storage_gb                       7627
ram_gb                           8036
storage_src                      7627
condition                        7774
condition_src                    7774
ram_src                          8036
has_5g                              0
has_warranty                        0
has_box                             0
mentions_exchange                   0
is_wanted_ad                        0
is_accessory_hint                   0
is_tablet_hint                      0
is_parts_hint                       0
accessory_first                     0
bundle_hint                         0
is_feature_phone_hint               0
price_placeholder                   0
loc_area                            6
loc_city                            6
price_missing                       0
price_suspicious                    0
price_very_high                     0

Data Types and Missing Values

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8213 entries, 0 to 8212
Data columns (total 30 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   title                  8213 non-null   object
 1   price                  8213 non-null   float64
 2   location               8207 non-null   object
 3   ad_url                 8213 non-null   object
 4   ad_id                  8213 non-null   int64
 5   run_id                 8213 non-null   object
 6   brand                  7772 non-null   object
 7   storage_gb             586 non-null    float64
 8   ram_gb                 177 non-null    float64
 9   storage_src            586 non-null    object
 10  condition              439 non-null    object
 11  condition_src          439 non-null    object
 12  ram_src                177 non-null    object
 13  has_5g                 8213 non-null   bool
 14  has_warranty           8213 non-null   bool
 15  has_box                8213 non-null   bool
 16  mentions_exchange      8213 non-null   bool
 17  is_wanted_ad           8213 non-null   bool
 18  is_accessory_hint      8213 non-null   bool
 19  is_tablet_hint         8213 non-null   bool
 20  is_parts_hint          8213 non-null   bool
 21  accessory_first        8213 non-null   bool
 22  bundle_hint            8213 non-null   bool
 23  is_feature_phone_hint  8213 non-null   bool
 24  price_placeholder      8213 non-null   bool
 25  loc_area               8207 non-null   object
 26  loc_city               8207 non-null   object
 27  price_missing          8213 non-null   bool
 28  price_suspicious       8213 non-null   bool
 29  price_very_high        8213 non-null   bool
dtypes: bool(15), float64(3), int64(1), object(11)
memory usage: 1.1+ MB

In [10]:
df.isna().sum().to_frame("Number of Missing Values")

                       Number of Missing Values
title                                         0
price                                         0
location                                      6
ad_url                                        0
ad_id                                         0
run_id                                        0
brand                                       441
storage_gb                                 7627
ram_gb                                     8036
storage_src                                7627
condition                                  7774
condition_src                              7774
ram_src                                    8036
has_5g                                        0
has_warranty                                  0
has_box                                       0
mentions_exchange                             0
is_wanted_ad                                  0
is_accessory_hint                             0
is_tablet_hint                                0
is_parts_hint                                 0
accessory_first                               0
bundle_hint                                   0
is_feature_phone_hint                         0
price_placeholder                             0
loc_area                                      6
loc_city                                      6
price_missing                                 0
price_suspicious                              0
price_very_high                               0

Check Duplicate Titles

In [11]:
df["title"].duplicated().sum()

np.int64(4513)

Inspect Duplicate Titles

In [12]:
df.loc[df["title"].duplicated(keep = False) , "title"].head(20).to_frame()

                        title
0             ايفون 13 iPhone
1              Honor Magic V5
5       Apple - iPhone 17 Pro
9     آبل - آيفون 15 برو ماكس
14    آبل - آيفون 17 برو ماكس
15    آبل - آيفون 13 برو ماكس
17          Apple - iPhone 15
18          Samsung S25 Ultra
19        سامسونج اس 24 الترا
21  Apple - iPhone 17 Pro Max
22          Apple - iPhone 14
30          iPhone 16 pro max
35                   هونر 600
37        سامسونج اس 24 الترا
46             آبل - آيفون 13
48                   Vivo V60
50      Apple - iPhone 13 Pro
51  Apple - iPhone 11 Pro Max
55        سامسونج اس 25 الترا
57             آبل - آيفون 12

Inspect Title Examples

In [13]:
df["title"].head(30)

0                                       ايفون 13 iPhone
1                                        Honor Magic V5
2             OPPO Find X9 Pro ضمان محلي للبيع او البدل
3                        Honor Robot Phone 512G 12G ram
4                        شاومي 17 الترا xiaomi 17 ultra
5                                 Apple - iPhone 17 Pro
6     للبيع iPhone 15 Pro 1TB_ايفون 15 برو_زيرو بسعر...
7                                         Honor 500 pro
8     ايفون 11 بحاله الزيرو (iphone11) - سعر لقطه لل...
9                               آبل - آيفون 15 برو ماكس
10                                   Huawei nova 15 max
11    ايفون 16e جديد وارد الامارات مدفوع ضريبة | iPh...
12    Oppo Find X5 5G dual sim 256/8G Black بحالة مم...
13    Samsung S24 Ultra زيرو 256GB تيتانيوم مدفوع ال...
14                              آبل - آيفون 17 برو ماكس
15                              آبل - آيفون 13 برو ماكس
16    Honor Magic V5 dual sim 512/16G White Gold جدي...
17                                    Apple - iPhone 15
18                                    Samsung S25 Ultra
19                                  سامسونج اس 24 الترا
20    زد فولد ٨  للبيع مستعمل ساعتين فقط بحالة الجدي...
21                            Apple - iPhone 17 Pro Max
22                                    Apple - iPhone 14
23                                    oppo find x9s pro
24                                   Redmi k100 pro max
25                                      Galaxy Z Flip 8
26                     Apple - iPhone 17 Pro Max 512 GB
27                                         Honor win rt
28          Google Pixel 11 Pro Fold 16g 256g Black New
29                                Galaxy Z Fold 8 ultra
Name: title, dtype: object

Check Title Normalization Examples

In [14]:
df.loc[df["title"].str.contains("iPhone 17 Pro Max", case=False), "title"]

21                              Apple - iPhone 17 Pro Max
26                       Apple - iPhone 17 Pro Max 512 GB
39                Apple - iPhone 17 Pro Max - Battery 98%
42                 Apple - iPhone 17 Pro Max battery 100%
43      Apple iPhone 17 Pro Max (512GB) كسر زيرو | خال...
                              ...
8049                            Apple - iPhone 17 Pro Max
8057                            Apple - iPhone 17 Pro Max
8072    Apple - iPhone 17 Pro Max battery 98% still in...
8084                            Apple - iPhone 17 Pro Max
8122                            Apple - iPhone 17 Pro Max
Name: title, Length: 169, dtype: object

Check Title Variations

In [15]:
df.loc[df["title"].str.contains("iPhone 17 Pro Max", case=False),"title"].nunique()

46

Inspect Unique Title Variations

In [16]:
df.loc[df["title"].str.contains("iPhone 17 Pro Max", case=False),"title"].drop_duplicates().to_list()

['Apple - iPhone 17 Pro Max',
 'Apple - iPhone 17 Pro Max 512 GB',
 'Apple - iPhone 17 Pro Max - Battery 98%',
 'Apple - iPhone 17 Pro Max battery 100%',
 'Apple iPhone 17 Pro Max (512GB) كسر زيرو | خالص ضريبة',
 'iPhone 17 pro max',
 'Apple - iPhone 17 Pro Max First high copy',
 'Apple - iPhone 17 Pro Max -Used Like New',
 'آبل - آيفون 17 برو ماكس iphone 17 pro max',
 'Apple - iPhone 17 Pro max',
 'iPhone 17 Pro Max 512gb',
 'iPhone 17 Pro Max 256GB – Silver',
 'iPhone 17 pro max 256 سيلفر',
 'IPhone 17 Pro Max silver zero scratches',
 'آيفون 17 برو ماكس  سيلفر - Apple iPhone 17 Pro Max siliver',
 'آبل IPhone 17 Pro max',
 'Apple - iPhone 17 Pro Max خربوش بسيط جدا جدا ف الباغه',
 'Apple - iPhone 17 Pro Max tradeline جديد متبرشم معفي ضريبة',
 'IPhone 17 pro max',
 'Iphone 17 pro max blue new',
 'iPhone 17 Pro Max 256 شريحه نسخه محلي مسجل بالعلبه فقط',
 'iphone 17 pro max',
 'iPhone 17 Pro Max كسر زيرو بدون خربوش للبيع',
 'iPhone 17 Pro Max 256GB Deep Blue – 100% Battery',
 'Apple - iPhone 17 Pro Max battery 100% 113 cycle',
 'أنتا الكسبان  IPhone 17 Pro Max جديد متبرشم ضمان سنة بسعر مميز',
 'Apple - iPhone 17 Pro Max / اي فون 17 برو مكس',
 'موبيل ايفون 17 برو ماكس | Apple iPhone 17 Pro Max تليفون مميز جدا',
 'Apple - iPhone 17 Pro Max - ايفون ١٧ برو ماكس',
 'Apple - iPhone 17 pro max',
 'iPhone 17 Pro Max',
 'iPhone 17 Pro Max 512 - مدفوع الضريبة',
 'iPhone 17 pro max gray white',
 'Apple IPhone 17 pro max',
 'iPhone 17 Pro max - 1st High copy "American"',
 'Apple - iPhone 17 Pro Max sliver',
 'Apple - iPhone 17 Pro Max trade line',
 'Iphone 17 pro max 256GB 98%',
 'Iphone 17 Pro Max',
 'iPhone 17 Pro Max 256GB with Box– 96% Battery Health – معفي من الضريبة',
 'iphone 17 pro max 256G',
 'Apple - iPhone 17 Pro Max كالجديد بدون خدش',
 'iPhone 17 Pro Max-256GB perfect condition',
 'iphone 17 pro max with box and cable',
 'iPhone 17 Pro Max خطين فعلي بطاريه ٩٦ بالعلبه معفي ضرايب',
 'Apple - iPhone 17 Pro Max battery 98% still in warranty']

Title Normalization

In [17]:
df["title_normalized"] = df["title"].str.lower().str.strip()

In [18]:
df[["title", "title_normalized"]].head(20)

,title,title_normalized
0,ايفون 13 iPhone,ايفون 13 iphone
1,Honor Magic V5,honor magic v5
2,OPPO Find X9 Pro ضمان محلي للبيع او البدل,oppo find x9 pro ضمان محلي للبيع او البدل
3,Honor Robot Phone 512G 12G ram,honor robot phone 512g 12g ram
4,شاومي 17 الترا xiaomi 17 ultra,شاومي 17 الترا xiaomi 17 ultra
5,Apple - iPhone 17 Pro,apple - iphone 17 pro
6,للبيع iPhone 15 Pro 1TB_ايفون 15 برو_زيرو بسعر...,للبيع iphone 15 pro 1tb_ايفون 15 برو_زيرو بسعر...
7,Honor 500 pro,honor 500 pro
8,ايفون 11 بحاله الزيرو (iphone11) - سعر لقطه لل...,ايفون 11 بحاله الزيرو (iphone11) - سعر لقطه لل...
9,آبل - آيفون 15 برو ماكس,آبل - آيفون 15 برو ماكس
10,Huawei nova 15 max,huawei nova 15 max
11,ايفون 16e جديد وارد الامارات مدفوع ضريبة | iPh...,ايفون 16e جديد وارد الامارات مدفوع ضريبة | iph...
12,Oppo Find X5 5G dual sim 256/8G Black بحالة مم...,oppo find x5 5g dual sim 256/8g black بحالة مم...
13,Samsung S24 Ultra زيرو 256GB تيتانيوم مدفوع ال...,samsung s24 ultra زيرو 256gb تيتانيوم مدفوع ال...
14,آبل - آيفون 17 برو ماكس,آبل - آيفون 17 برو ماكس
15,آبل - آيفون 13 برو ماكس,آبل - آيفون 13 برو ماكس
16,Honor Magic V5 dual sim 512/16G White Gold جدي...,honor magic v5 dual sim 512/16g white gold جدي...
17,Apple - iPhone 15,apple - iphone 15
18,Samsung S25 Ultra,samsung s25 ultra
19,سامسونج اس 24 الترا,سامسونج اس 24 الترا

Compare Unique Titles

In [19]:
print("Original unique titles:", df["title"].nunique())
print("Normalized unique titles:", df["title_normalized"].nunique())

Original unique titles: 3700
Normalized unique titles: 3565

Normalize Arabic Letter Variants

In [20]:
df["title_normalized"] = (df["title_normalized"]
    .str.replace("أ" , "ا", regex=False)
    .str.replace("إ" , "ا", regex=False)
    .str.replace("آ" , "ا", regex=False)
    .str.replace("ى" , "ي", regex=False)
)

Compare Normalized Titles

In [21]:
df["title_normalized"].nunique()

3551

Inspect Title Punctuation

In [22]:
df["title_normalized"].head(20).to_list()

['ايفون 13 iphone',
 'honor magic v5',
 'oppo find x9 pro ضمان محلي للبيع او البدل',
 'honor robot phone 512g 12g ram',
 'شاومي 17 الترا xiaomi 17 ultra',
 'apple - iphone 17 pro',
 'للبيع iphone 15 pro 1tb_ايفون 15 برو_زيرو بسعر لقطة لسرعه البيع ممتاز',
 'honor 500 pro',
 'ايفون 11 بحاله الزيرو (iphone11) - سعر لقطه للجادين للسرعه البيع 64 gb',
 'ابل - ايفون 15 برو ماكس',
 'huawei nova 15 max',
 'ايفون 16e جديد وارد الامارات مدفوع ضريبة | iphone 16e phone new',
 'oppo find x5 5g dual sim 256/8g black بحالة ممتازة',
 'samsung s24 ultra زيرو 256gb تيتانيوم مدفوع الضريبة بالضمان',
 'ابل - ايفون 17 برو ماكس',
 'ابل - ايفون 13 برو ماكس',
 'honor magic v5 dual sim 512/16g white gold جديد بضمان الوكيل',
 'apple - iphone 15',
 'samsung s25 ultra',
 'سامسونج اس 24 الترا']

Punctuation Normalization

In [23]:
df["title_punct_normalized"] = (
    df["title_normalized"]
    .str.replace("-", " ", regex=False)
    .str.replace("_", " ", regex=False)
    .str.strip()
    .str.split()
    .str.join(" ")
)

Compare Titles After Punctuation Normalization

In [24]:
print("Before:", df["title_normalized"].nunique())
print("After:", df["title_punct_normalized"].nunique())

Before: 3551
After: 3531

Review Normalized Titles

In [25]:
df[["title", "title_normalized", "title_punct_normalized"]].head(10)

,title,title_normalized,title_punct_normalized
0,ايفون 13 iPhone,ايفون 13 iphone,ايفون 13 iphone
1,Honor Magic V5,honor magic v5,honor magic v5
2,OPPO Find X9 Pro ضمان محلي للبيع او البدل,oppo find x9 pro ضمان محلي للبيع او البدل,oppo find x9 pro ضمان محلي للبيع او البدل
3,Honor Robot Phone 512G 12G ram,honor robot phone 512g 12g ram,honor robot phone 512g 12g ram
4,شاومي 17 الترا xiaomi 17 ultra,شاومي 17 الترا xiaomi 17 ultra,شاومي 17 الترا xiaomi 17 ultra
5,Apple - iPhone 17 Pro,apple - iphone 17 pro,apple iphone 17 pro
6,للبيع iPhone 15 Pro 1TB_ايفون 15 برو_زيرو بسعر...,للبيع iphone 15 pro 1tb_ايفون 15 برو_زيرو بسعر...,للبيع iphone 15 pro 1tb ايفون 15 برو زيرو بسعر...
7,Honor 500 pro,honor 500 pro,honor 500 pro
8,ايفون 11 بحاله الزيرو (iphone11) - سعر لقطه لل...,ايفون 11 بحاله الزيرو (iphone11) - سعر لقطه لل...,ايفون 11 بحاله الزيرو (iphone11) سعر لقطه للجا...
9,آبل - آيفون 15 برو ماكس,ابل - ايفون 15 برو ماكس,ابل ايفون 15 برو ماكس

Improve Punctuation Normalization

In [26]:
df["title_punct_normalized"] = (
    df["title_normalized"]
    .str.replace("-", " ", regex=False)
    .str.replace("_", " ", regex=False)
    .str.strip()
)

In [27]:
df.loc[df["title_normalized"] != df["title_punct_normalized"],["title_normalized", "title_punct_normalized"]].head(10)

,title_normalized,title_punct_normalized
5,apple - iphone 17 pro,apple iphone 17 pro
6,للبيع iphone 15 pro 1tb_ايفون 15 برو_زيرو بسعر...,للبيع iphone 15 pro 1tb ايفون 15 برو زيرو بسعر...
8,ايفون 11 بحاله الزيرو (iphone11) - سعر لقطه لل...,ايفون 11 بحاله الزيرو (iphone11) سعر لقطه لل...
9,ابل - ايفون 15 برو ماكس,ابل ايفون 15 برو ماكس
14,ابل - ايفون 17 برو ماكس,ابل ايفون 17 برو ماكس
15,ابل - ايفون 13 برو ماكس,ابل ايفون 13 برو ماكس
17,apple - iphone 15,apple iphone 15
21,apple - iphone 17 pro max,apple iphone 17 pro max
22,apple - iphone 14,apple iphone 14
26,apple - iphone 17 pro max 512 gb,apple iphone 17 pro max 512 gb

In [28]:
print("Before:", df["title_normalized"].nunique())
print("After:", df["title_punct_normalized"].nunique())

Before: 3551
After: 3551

Normalize Extra Spaces

In [29]:
df["title_punct_normalized"] = (
    df["title_punct_normalized"]
    .str.split()
    .str.join(" ")
)

In [30]:
df["title_punct_normalized"].head(20).to_list()

['ايفون 13 iphone',
 'honor magic v5',
 'oppo find x9 pro ضمان محلي للبيع او البدل',
 'honor robot phone 512g 12g ram',
 'شاومي 17 الترا xiaomi 17 ultra',
 'apple iphone 17 pro',
 'للبيع iphone 15 pro 1tb ايفون 15 برو زيرو بسعر لقطة لسرعه البيع ممتاز',
 'honor 500 pro',
 'ايفون 11 بحاله الزيرو (iphone11) سعر لقطه للجادين للسرعه البيع 64 gb',
 'ابل ايفون 15 برو ماكس',
 'huawei nova 15 max',
 'ايفون 16e جديد وارد الامارات مدفوع ضريبة | iphone 16e phone new',
 'oppo find x5 5g dual sim 256/8g black بحالة ممتازة',
 'samsung s24 ultra زيرو 256gb تيتانيوم مدفوع الضريبة بالضمان',
 'ابل ايفون 17 برو ماكس',
 'ابل ايفون 13 برو ماكس',
 'honor magic v5 dual sim 512/16g white gold جديد بضمان الوكيل',
 'apple iphone 15',
 'samsung s25 ultra',
 'سامسونج اس 24 الترا']

Inspect Remaining Punctuation

In [31]:
df.loc[df["title_punct_normalized"].str.contains(r"[|()]", regex=True, na=False), ["title", "title_punct_normalized"]].head(10)

,title,title_punct_normalized
8,ايفون 11 بحاله الزيرو (iphone11) - سعر لقطه لل...,ايفون 11 بحاله الزيرو (iphone11) سعر لقطه للجا...
11,ايفون 16e جديد وارد الامارات مدفوع ضريبة | iPh...,ايفون 16e جديد وارد الامارات مدفوع ضريبة | iph...
40,موبايل Samsung S23 Ultra مستعمل (256GB / 12GB ...,موبايل samsung s23 ultra مستعمل (256gb / 12gb ...
43,Apple iPhone 17 Pro Max (512GB) كسر زيرو | خال...,apple iphone 17 pro max (512gb) كسر زيرو | خال...
72,Infinix smart 20 (4+4/64) جديد,infinix smart 20 (4+4/64) جديد
196,ايفون ١٦ بلس (iphone 16 plus),ايفون ١٦ بلس (iphone 16 plus)
327,Apple iPhone 16 Pro (128 g) كسر زيرو | بطارية ...,apple iphone 16 pro (128 g) كسر زيرو | بطارية ...
527,Xiaomi Poco X3 (128/6),xiaomi poco x3 (128/6)
529,جهازين 11pro max (X),جهازين 11pro max (x)
653,iPhone 12 Pro Max (256) zero tax,iphone 12 pro max (256) zero tax

Normalize Arabic and English Digits

In [32]:
digit_map = str.maketrans("٠١٢٣٤٥٦٧٨٩", "0123456789")

df["title_normalized"] = (df["title_normalized"].str.translate(digit_map))

Remove Arabic Diacritics

In [33]:
df["title_normalized"] = (df["title_normalized"].str.replace(r"[\u064B-\u065F\u0670]", "" , regex=True))

In [34]:
df.loc[df["title"].str.contains("[ًٌٍَُِّْ]", na=False),["title", "title_normalized"]].head(10)

,title,title_normalized
354,سامسونج جالاكسي A07 مساحة 128GB رام 6GB - زير...,سامسونج جالاكسي a07 مساحة 128gb رام 6gb - زير...
507,Realme 9i 6/128 بحالة ممتازة جدًا + الكرتونة,realme 9i 6/128 بحالة ممتازة جدا + الكرتونة
746,للبيغ Infinix Smart بحالة ممتازة وبسعر لُقطة!,للبيغ infinix smart بحالة ممتازة وبسعر لقطة!
1499,لقطه العمر هاتف سامسونج جالاكسي ايه 13 ب 3000ج...,لقطه العمر هاتف سامسونج جالاكسي ايه 13 ب 3000ج...
2296,13 عاديً,13 عادي
2443,اوبو رينو 6 5g الفون زي الجديد حرفياً موضح بالصور,اوبو رينو 6 5g الفون زي الجديد حرفيا موضح بالصور
2495,​ فرصة مميزة للبيع: هاتف Infinix Note 50s كسر ...,​ فرصة مميزة للبيع: هاتف infinix note 50s كسر ...
3507,آبل - آيفون 17 برو ماكس زيرو تماماً جديد,ابل - ايفون 17 برو ماكس زيرو تماما جديد
3790,موبايل مختلف وفخم جدًا لعشاق التميز OPPO Find ...,موبايل مختلف وفخم جدا لعشاق التميز oppo find n...
4020,موبل سامسونج ِ30 جيد جدا للبيع,موبل سامسونج 30 جيد جدا للبيع

Compare Unique Titles Before and After Punctuation Normalization

In [35]:
print("Unique normalized titles:", df["title_normalized"].nunique())
print("Unique punctuation-normalized titles:", df["title_punct_normalized"].nunique())

Unique normalized titles: 3521
Unique punctuation-normalized titles: 3531

Rebuild Punctuation-Normalized Titles

In [36]:
df["title_punct_normalized"] = (df["title_normalized"]
    .str.replace(r"[-_]", " ", regex=True)
    .str.split()
    .str.join(" ")
)

In [37]:
df[["title", "brand", "storage_gb", "ram_gb"]].head(20)

,title,brand,storage_gb,ram_gb
0,ايفون 13 iPhone,apple,NaN,NaN
1,Honor Magic V5,honor,NaN,NaN
2,OPPO Find X9 Pro ضمان محلي للبيع او البدل,oppo,NaN,NaN
3,Honor Robot Phone 512G 12G ram,honor,512.0,12.0
4,شاومي 17 الترا xiaomi 17 ultra,xiaomi,NaN,NaN
5,Apple - iPhone 17 Pro,apple,NaN,NaN
6,للبيع iPhone 15 Pro 1TB_ايفون 15 برو_زيرو بسعر...,apple,1024.0,NaN
7,Honor 500 pro,honor,NaN,NaN
8,ايفون 11 بحاله الزيرو (iphone11) - سعر لقطه لل...,apple,64.0,NaN
9,آبل - آيفون 15 برو ماكس,apple,NaN,NaN
10,Huawei nova 15 max,huawei,NaN,NaN
11,ايفون 16e جديد وارد الامارات مدفوع ضريبة | iPh...,apple,NaN,NaN
12,Oppo Find X5 5G dual sim 256/8G Black بحالة مم...,oppo,256.0,8.0
13,Samsung S24 Ultra زيرو 256GB تيتانيوم مدفوع ال...,samsung,256.0,NaN
14,آبل - آيفون 17 برو ماكس,apple,NaN,NaN
15,آبل - آيفون 13 برو ماكس,apple,NaN,NaN
16,Honor Magic V5 dual sim 512/16G White Gold جدي...,honor,512.0,16.0
17,Apple - iPhone 15,apple,NaN,NaN
18,Samsung S25 Ultra,samsung,NaN,NaN
19,سامسونج اس 24 الترا,samsung,NaN,NaN

In [38]:
print("Unique normalized titles:", df["title_normalized"].nunique())
print("Unique punctuation-normalized titles:", df["title_punct_normalized"].nunique())

Unique normalized titles: 3521
Unique punctuation-normalized titles: 3500

In [39]:
df[["title", "title_normalized", "title_punct_normalized"]].sample(10, random_state=42)

,title,title_normalized,title_punct_normalized
6791,فيفو x200 fe,فيفو x200 fe,فيفو x200 fe
7863,اوبو رينو 10 برو,اوبو رينو 10 برو,اوبو رينو 10 برو
3647,شاومي موديل اخر,شاومي موديل اخر,شاومي موديل اخر
7364,Apple - iPhone 17 Pro Max,apple - iphone 17 pro max,apple iphone 17 pro max
5549,آبل - آيفون 14 برو,ابل - ايفون 14 برو,ابل ايفون 14 برو
5584,آبل - آيفون 13,ابل - ايفون 13,ابل ايفون 13
2540,Apple - iPhone 15 Pro Max,apple - iphone 15 pro max,apple iphone 15 pro max
1882,Vivo y19 s Pro,vivo y19 s pro,vivo y19 s pro
970,آبل - آيفون 11 برو ماكس,ابل - ايفون 11 برو ماكس,ابل ايفون 11 برو ماكس
5952,Apple - iPhone 12 Pro Max,apple - iphone 12 pro max,apple iphone 12 pro max

Check for Extra Spaces in Normalized Titles

In [40]:
df["title_punct_normalized"].str.contains(r"\s{2,}", regex=True, na=False).sum()

np.int64(0)

 Verify Final Title Normalization

In [41]:
df[["title", "title_normalized", "title_punct_normalized"]].sample(10, random_state=42)

,title,title_normalized,title_punct_normalized
6791,فيفو x200 fe,فيفو x200 fe,فيفو x200 fe
7863,اوبو رينو 10 برو,اوبو رينو 10 برو,اوبو رينو 10 برو
3647,شاومي موديل اخر,شاومي موديل اخر,شاومي موديل اخر
7364,Apple - iPhone 17 Pro Max,apple - iphone 17 pro max,apple iphone 17 pro max
5549,آبل - آيفون 14 برو,ابل - ايفون 14 برو,ابل ايفون 14 برو
5584,آبل - آيفون 13,ابل - ايفون 13,ابل ايفون 13
2540,Apple - iPhone 15 Pro Max,apple - iphone 15 pro max,apple iphone 15 pro max
1882,Vivo y19 s Pro,vivo y19 s pro,vivo y19 s pro
970,آبل - آيفون 11 برو ماكس,ابل - ايفون 11 برو ماكس,ابل ايفون 11 برو ماكس
5952,Apple - iPhone 12 Pro Max,apple - iphone 12 pro max,apple iphone 12 pro max

Count Unique Titles After Final Normalization

In [42]:
df["title_punct_normalized"].nunique()

3500

Create Final Normalized Title Groups

In [43]:
df["title_group"] = df["title_punct_normalized"]

In [44]:
print("Missing groups:", df["title_group"].isna().sum())
print("Total groups:", df["title_group"].nunique())
print("Total rows:", len(df))

Missing groups: 0
Total groups: 3500
Total rows: 8213

Validate Title Normalization

In [45]:
print("Original unique titles:", df["title"].nunique())
print("Normalized unique titles:", df["title_normalized"].nunique())
print("Final title groups:", df["title_group"].nunique())
print("Missing groups:", df["title_group"].isna().sum())
print("Total rows:", len(df))

Original unique titles: 3700
Normalized unique titles: 3521
Final title groups: 3500
Missing groups: 0
Total rows: 8213

# Grouped Train-Test Split

In [46]:
from sklearn.model_selection import GroupShuffleSplit

splitter = GroupShuffleSplit(n_splits=1 , test_size=0.20, random_state=42)

train_idx, test_idx = next(splitter.split(df , groups = df["title_group"]))

train_df = df.iloc[train_idx].copy()
test_df = df.iloc[test_idx].copy()

Validate Grouped Split

In [47]:
train_groups = set(train_df["title_group"])
test_groups = set(test_df["title_group"])

overlap = train_groups.intersection(test_groups)

print("Train rows:", len(train_df))
print("Test rows:", len(test_df))
print("Overlapping groups:", len(overlap))

Train rows: 6417
Test rows: 1796
Overlapping groups: 0

Save Frozen Test Set

In [48]:
from pathlib import Path

output_dir = Path("data/processed")
output_dir.mkdir(parents=True, exist_ok=True)

test_df.to_csv(output_dir / "frozen_test_set.csv",index=False)

train_df.to_csv(output_dir / "train_set.csv",index=False)

In [49]:
print("Train groups:", train_df["title_group"].nunique())
print("Test groups:", test_df["title_group"].nunique())
print("Total groups:", df["title_group"].nunique())

Train groups: 2800
Test groups: 700
Total groups: 3500

In [50]:
print("Saved test rows:", len(test_df))
print("Saved train rows:", len(train_df))
print("Test file exists:", (output_dir / "frozen_test_set.csv").exists())
print("Train file exists:", (output_dir / "train_set.csv").exists())

Saved test rows: 1796
Saved train rows: 6417
Test file exists: True
Train file exists: True

##### GroupKFold Cross-Validation

In [51]:
from sklearn.model_selection import GroupKFold

gkf = GroupKFold(n_splits=5)

for fold, (train_idx, val_idx) in enumerate(
    gkf.split(
        train_df,
        groups=train_df["title_group"]
    ),
    start=1
):
    print(
        f"Fold {fold}: "
        f"Train={len(train_idx)}, "
        f"Validation={len(val_idx)}"
    )

Fold 1: Train=5133, Validation=1284
Fold 2: Train=5133, Validation=1284
Fold 3: Train=5134, Validation=1283
Fold 4: Train=5134, Validation=1283
Fold 5: Train=5134, Validation=1283

In [52]:
for fold, (train_idx, val_idx) in enumerate(gkf.split(train_df,groups=train_df["title_group"]),
    start=1
):
    train_groups = set(train_df.iloc[train_idx]["title_group"])
    val_groups = set(train_df.iloc[val_idx]["title_group"])

    overlap = train_groups.intersection(val_groups)

    print(f"Fold {fold}: Overlapping groups = {len(overlap)}")

Fold 1: Overlapping groups = 0
Fold 2: Overlapping groups = 0
Fold 3: Overlapping groups = 0
Fold 4: Overlapping groups = 0
Fold 5: Overlapping groups = 0

Create Stage 1 Training Dataset

In [53]:
stage1_df = train_df.copy()

print("Stage 1 dataset shape:", stage1_df.shape)
print("Available columns:", stage1_df.columns.tolist())

Stage 1 dataset shape: (6417, 33)
Available columns: ['title', 'price', 'location', 'ad_url', 'ad_id', 'run_id', 'brand', 'storage_gb', 'ram_gb', 'storage_src', 'condition', 'condition_src', 'ram_src', 'has_5g', 'has_warranty', 'has_box', 'mentions_exchange', 'is_wanted_ad', 'is_accessory_hint', 'is_tablet_hint', 'is_parts_hint', 'accessory_first', 'bundle_hint', 'is_feature_phone_hint', 'price_placeholder', 'loc_area', 'loc_city', 'price_missing', 'price_suspicious', 'price_very_high', 'title_normalized', 'title_punct_normalized', 'title_group']

Define Final iPhone Model Extraction Function

In [54]:
def extract_iphone_model(title):
    text = re.sub(r"\s+", " ", str(title).lower()).strip()
    special_cases = [
        (r"(?:iphone|i\s*phone|ايفون|آيفون)\s*6\s*(?:s|اس|أس)\s*(?:plus|بلس)\b", "iphone 6s plus"),
        (r"(?:iphone|i\s*phone|ايفون|آيفون)\s*x\s*(?:s|اس|أس)\s*(?:max|ماكس)\b", "iphone xs max"),
        (r"(?:iphone|i\s*phone|ايفون|آيفون)\s*x\s*(?:max|ماكس)\b", "iphone x max"),
        (r"ip+h+o+n+e+\s*17\s+pro+m+a+x+", "iphone 17 pro max"),
        (r"ايفون+ن?\s*17\s*برماكس", "iphone 17 pro max"),
        (r"iphoneee?\s*17\s*pro+\s*ma+x+", "iphone 17 pro max"),
        (r"iphone+\s*17\s*pro+\s*ma+x+", "iphone 17 pro max"),
        (r"ايفون\s*17\s*برو+ما+كس", "iphone 17 pro max"),
        (r"ايفون\s*17\s*برماكس", "iphone 17 pro max"),
        (r"iphone\s*pro\s*max\s*17", "iphone 17 pro max"),
        (r"ايفون\s*pro\s*max\s*17", "iphone 17 pro max"),
        (r"iphone\s*3g\b", "iphone 3g"),
        (r"ايفون\s*3g\b", "iphone 3g"),
        (r"ايفون\s*6اس\b", "iphone 6s"),
        (r"ايفون\s*8بلص\b", "iphone 8 plus"),
        (r"ايفون\s*i\s*phone\s*plus\s*7", "iphone 7 plus"),
    ]

    for pattern, model in special_cases:
        if re.search(pattern, text):
            return model
    special_models = [
        (r"\bxs\s*max\b|\bاكس\s*اس\s*ماكس\b", "iphone xs max"),
        (r"\bxs\b|\bاكس\s*اس\b", "iphone xs"),
        (r"\bxr\b|\bاكس\s*ار\b", "iphone xr"),
        (r"\bx\b|\bاكس\b", "iphone x"),
        (r"\b(?:iphone|i\s*phone)\s*se\b", "iphone se"),
        (r"\bايفون\s*اس\s*اي\b", "iphone se"),
        (r"\bايفون\s*اكس\s*اس\s*ماكس\b", "iphone xs max"),
        (r"\bايفون\s*اكس\s*ار\b", "iphone xr"),
        (r"\bايفون\s*اكس\s*اس\b", "iphone xs"),
        (r"\bايفون\s*اكس\b", "iphone x"),
        (r"\b(?:iphone|i\s*phone)\s*xs\s*max\b", "iphone xs max"),
        (r"\b(?:iphone|i\s*phone)\s*xr\b", "iphone xr"),
        (r"\b(?:iphone|i\s*phone)\s*xs\b", "iphone xs"),
        (r"\b(?:iphone|i\s*phone)\s*x\b", "iphone x"),
    ]

    for pattern, model in special_models:
        if re.search(pattern, text):
            return model

    model_patterns = [
        (r"(?:iphone|i\s*phone|ايفون|آيفون)\s*(\d{1,2})\s*pro\s*max\b", "pro max"),
        (r"(?:iphone|i\s*phone|ايفون|آيفون)\s*(\d{1,2})\s*برو\s*ماكس\b", "pro max"),
        (r"(?:iphone|i\s*phone|ايفون|آيفون)\s*(\d{1,2})\s*plus\b", "plus"),
        (r"(?:iphone|i\s*phone|ايفون|آيفون)\s*(\d{1,2})\s*بلس\b", "plus"),
        (r"(?:iphone|i\s*phone|ايفون|آيفون)\s*(\d{1,2})\s*pro\b", "pro"),
        (r"(?:iphone|i\s*phone|ايفون|آيفون)\s*(\d{1,2})\s*برو\b", "pro"),
    ]

    for pattern, version in model_patterns:
        match = re.search(pattern, text)
        if match:
            return f"iphone {match.group(1)} {version}"

    numeric_pattern = re.compile(
        r"(?:\biphone\s*|\bi\s*phone\s*|ايفون\s*)"
        r"(\d{1,2})(s)?\s*"
        r"(pro\s*max|promax|pro|max|plus|mini|air|e)?\b"
    )

    match = numeric_pattern.search(text)

    if match:
        number = match.group(1)
        suffix = match.group(2) or ""
        version = re.sub(r"\s+", " ", (match.group(3) or "").strip())

        if version == "promax":
            version = "pro max"

        model = f"iphone {number}{suffix}"
        return f"{model} {version}" if version else model

    match = re.search(
        r"ايفون\s+(pro|max|plus|برو|ماكس|بلس)\s*(\d{1,2})",
        text
    )

    if match:
        version = {
            "برو": "pro",
            "ماكس": "max",
            "بلس": "plus"
        }.get(match.group(1), match.group(1))

        return f"iphone {match.group(2)} {version}"

    pattern = re.compile(
        r"\b(?:iphone\s*)?(\d{1,2})\s*"
        r"(pro\s*max|pro|max|plus|mini|air|e)?\b"
        r"|ايفون\s*(\d{1,2})\s*"
        r"(برو\s*ماكس|برو|ماكس|بلس|ميني|اير|e)?"
    )

    match = pattern.search(text)

    if not match:
        return "unknown"

    number = match.group(1) or match.group(3)
    version = (match.group(2) or match.group(4) or "").strip()

    version = {
        "برو ماكس": "pro max",
        "برو": "pro",
        "ماكس": "max",
        "بلس": "plus",
        "ميني": "mini",
        "اير": "air"
    }.get(version, version)

    return f"iphone {number} {version}".strip()

Extract iPhone Models and Evaluate Coverage

In [55]:
apple_titles = stage1_df[stage1_df["brand"] == "apple"].copy()

apple_titles["iphone_model"] = apple_titles[
    "title_punct_normalized"
].apply(extract_iphone_model)

print("Total Apple ads:", len(apple_titles))
print("Extracted:", (apple_titles["iphone_model"] != "unknown").sum())
print("Unknown:", (apple_titles["iphone_model"] == "unknown").sum())
print(
    "Coverage:",
    round((apple_titles["iphone_model"] != "unknown").mean() * 100, 2),
    "%"
)

display(
    apple_titles[
        ["title", "title_punct_normalized", "iphone_model"]
    ].head(20)
)

Total Apple ads: 2936
Extracted: 2899
Unknown: 37
Coverage: 98.74 %

,title,title_punct_normalized,iphone_model
0,ايفون 13 iPhone,ايفون 13 iphone,iphone 13
6,للبيع iPhone 15 Pro 1TB_ايفون 15 برو_زيرو بسعر...,للبيع iphone 15 pro 1tb ايفون 15 برو زيرو بسعر...,iphone 15 pro
8,ايفون 11 بحاله الزيرو (iphone11) - سعر لقطه لل...,ايفون 11 بحاله الزيرو (iphone11) سعر لقطه للجا...,iphone 11
9,آبل - آيفون 15 برو ماكس,ابل ايفون 15 برو ماكس,iphone 15 pro max
11,ايفون 16e جديد وارد الامارات مدفوع ضريبة | iPh...,ايفون 16e جديد وارد الامارات مدفوع ضريبة | iph...,iphone 16 e
14,آبل - آيفون 17 برو ماكس,ابل ايفون 17 برو ماكس,iphone 17 pro max
15,آبل - آيفون 13 برو ماكس,ابل ايفون 13 برو ماكس,iphone 13 pro max
21,Apple - iPhone 17 Pro Max,apple iphone 17 pro max,iphone 17 pro max
22,Apple - iPhone 14,apple iphone 14,iphone 14
26,Apple - iPhone 17 Pro Max 512 GB,apple iphone 17 pro max 512 gb,iphone 17 pro max
30,iPhone 16 pro max,iphone 16 pro max,iphone 16 pro max
31,Iphone 13 pro max,iphone 13 pro max,iphone 13 pro max
34,آبل - آيفون 17 برو ماكس iphone 17 promax 512,ابل ايفون 17 برو ماكس iphone 17 promax 512,iphone 17 pro max
39,Apple - iPhone 17 Pro Max - Battery 98%,apple iphone 17 pro max battery 98%,iphone 17 pro max
41,ايفون 16 pro max سعه 256,ايفون 16 pro max سعه 256,iphone 16 pro max
42,Apple - iPhone 17 Pro Max battery 100%,apple iphone 17 pro max battery 100%,iphone 17 pro max
43,Apple iPhone 17 Pro Max (512GB) كسر زيرو | خال...,apple iphone 17 pro max (512gb) كسر زيرو | خال...,iphone 17 pro max
46,آبل - آيفون 13,ابل ايفون 13,iphone 13
47,آبل - آيفون 16 برو ماكس غير مدفوع ضريبة,ابل ايفون 16 برو ماكس غير مدفوع ضريبة,iphone 16 pro max
50,Apple - iPhone 13 Pro,apple iphone 13 pro,iphone 13 pro

Save Final iPhone Predictions

In [56]:
iphone_model_compact = apple_titles["iphone_model"].copy()
print("Saved predictions:", len(iphone_model_compact))
print("Extracted:", (iphone_model_compact != "unknown").sum())
print("Unknown:", (iphone_model_compact == "unknown").sum())

Saved predictions: 2936
Extracted: 2899
Unknown: 37

Add iPhone Models to Stage 1 Dataset

In [57]:
apple_mask = stage1_df["brand"] == "apple"
stage1_df["iphone_model"] = "not_apple"

stage1_df.loc[apple_mask, "iphone_model"] = (
    stage1_df.loc[apple_mask, "title_punct_normalized"]
    .apply(extract_iphone_model)
)

print("iPhone column added successfully.")
print("Apple ads:", apple_mask.sum())
print(
    "Unknown iPhone models:",
    (stage1_df.loc[apple_mask, "iphone_model"] == "unknown").sum()
)

display(
    stage1_df.loc[
        apple_mask,
        ["title", "iphone_model"]
    ].head(10)
)

iPhone column added successfully.
Apple ads: 2936
Unknown iPhone models: 37

                                                title       iphone_model
0                                     ايفون 13 iPhone          iphone 13
6   للبيع iPhone 15 Pro 1TB_ايفون 15 برو_زيرو بسعر...      iphone 15 pro
8   ايفون 11 بحاله الزيرو (iphone11) - سعر لقطه لل...          iphone 11
9                             آبل - آيفون 15 برو ماكس  iphone 15 pro max
11  ايفون 16e جديد وارد الامارات مدفوع ضريبة | iPh...        iphone 16 e
14                            آبل - آيفون 17 برو ماكس  iphone 17 pro max
15                            آبل - آيفون 13 برو ماكس  iphone 13 pro max
21                          Apple - iPhone 17 Pro Max  iphone 17 pro max
22                                  Apple - iPhone 14          iphone 14
26                   Apple - iPhone 17 Pro Max 512 GB  iphone 17 pro max

Explore Samsung Listings

In [58]:
samsung_titles = stage1_df[
    stage1_df["brand"] == "samsung"
].copy()

print("Total Samsung ads:", len(samsung_titles))

display(
    samsung_titles[
        ["title", "title_punct_normalized"]
    ].sample(
        n=min(20, len(samsung_titles)),
        random_state=10
    )
)

Total Samsung ads: 1074

,title,title_punct_normalized
6991,Samsung A56,samsung a56
1992,سامسونجa36فجي تليفون حالته جميله اوي انا هبيعو...,سامسونجa36فجي تليفون حالته جميله اوي انا هبيعو...
553,سامسونج a06,سامسونج a06
2980,سامسونج ايه 16,سامسونج ايه 16
2272,Samsung a07,samsung a07
5789,Samsung S23 Ultra,samsung s23 ultra
631,سامسونج اس 22 الترا,سامسونج اس 22 الترا
1384,سامسونج جالكسي ايه ٩٠ 5g,سامسونج جالكسي ايه 90 5g
5688,Samsung A56,samsung a56
8157,سامسونج زد فولد 5,سامسونج زد فولد 5
6344,Samsung S21 Plus,samsung s21 plus
1927,سامسونج اس 4,سامسونج اس 4
7331,سامسونج ايه 56,سامسونج ايه 56
61,سامسونج ايه 52s,سامسونج ايه 52s
7126,موبايل سامسونج جالكسى S4,موبايل سامسونج جالكسي s4
4110,سامسونج اس 25 الترا,سامسونج اس 25 الترا
2545,Samsung S25 Ultra,samsung s25 ultra
2307,سامسونج ايه 57,سامسونج ايه 57
3059,سامسونج m52 بالعلبه/ samsung m525g,سامسونج m52 بالعلبه/ samsung m525g
1188,سامسونج a55,سامسونج a55

Define Final Samsung Model Extraction Function

In [59]:
def extract_samsung_model(title):
    text = str(title).lower()
    text = re.sub(r"\s+", " ", text).strip()

    for ar, en in zip("٠١٢٣٤٥٦٧٨٩", "0123456789"):
        text = text.replace(ar, en)

    text = text.replace("⁰", "0").replace("⁵", "5").replace("⁷", "7")

    compact = re.sub(r"\s+", "", text)
    if "ztrifold" in compact or "ztri fold" in text or "tri fold" in text:
        return "samsung z trifold"

    if "سامسونجa36فجي" in compact or "سامسونجa365g" in compact:
        return "samsung a36"

    if "چى" in text and "7" in text and "برو" in text:
        return "samsung j7 pro"

    if "جراند" in text and "برايم" in text:
        if "برو" in text:
            return "samsung grand prime pro"
        return "samsung grand prime"

    if re.search(r"جيه\s*[٧7]\s*برايم", text):
        return "samsung j7 prime"
    replacements = {
        "سامسونج": " samsung ",
        "جالكسى": " galaxy ",
        "جالكسي": " galaxy ",
        "جالاكسي": " galaxy ",
        "جلاكسي": " galaxy ",
        "ايه": " a ",
        "إيه": " a ",
        "اي": " a ",
        "إي": " a ",
        "اس": " s ",
        "إس": " s ",
        "ام": " m ",
        "إم": " m ",
        "اف": " f ",
        "إف": " f ",
        "جيه": " j ",
        "جى": " g ",
        "چى": " g ",
        "نوت": " note ",
        "الترا": " ultra ",
        "بلس": " plus ",
        "برو": " pro ",
        "برايم": " prime ",
        "فولد": " fold ",
        "فليب": " flip ",
        "زد": " z ",
        "جراند": " grand ",
    }

    for old, new in replacements.items():
        text = text.replace(old, new)

    text = re.sub(r"\s+", " ", text).strip()
    text = re.sub(r"\b(?:samsung|galaxy)\b", " ", text)
    text = re.sub(r"\s+", " ", text).strip()

    special_patterns = [
        (r"\bz\s*fold\s*(\d+)\b", "z fold"),
        (r"\bz\s*flip\s*(\d+)\b", "z flip"),
        (r"\b(?:samsung\s+)?fold\s*(\d+)\b", "fold"),
        (r"\bx\s*cover\s*(\d+)\s*(pro)?\b", "xcover"),
    ]

    for pattern, prefix in special_patterns:
        match = re.search(pattern, text)
        if match:
            model = prefix + match.group(1)
            if len(match.groups()) > 1 and match.group(2):
                model += " " + match.group(2)
            return "samsung " + model

    if re.search(r"\b26\s*ultra\b", text):
        return "samsung s26 ultra"

    if re.search(r"\ba\s*03\s*core\b", text):
        return "samsung a03 core"

    if re.search(r"\ba\s*04e\b", text):
        return "samsung a04e"

    if re.search(r"\ba\s*36\s*5g\b", text):
        return "samsung a36"

    if re.search(r"\ba\s*51\b", text):
        return "samsung a51"

    if re.search(r"\bflip\s*5\b", text):
        return "samsung z flip5"

    if re.search(r"\bgrand\s*prime\s*pro\b", text):
        return "samsung grand prime pro"

    if re.search(r"\bgrand\s*prime\b", text):
        return "samsung grand prime"

    if re.search(r"\bmega\b", text):
        return "samsung mega"

    patterns = [
        (r"\bf\s*(\d{1,3})\b", "f"),
        (r"\bnote\s*(\d+)\s*(ultra|plus)?\b", "note"),
        (r"\bnot\s*(\d+)\s*(ultra|plus)?\b", "note"),
        (r"\bs\s*(\d+)\s*(ultra|plus|fe)?\b", "s"),
        (r"\ba\s*(\d{1,3})\s*(ultra|plus|s)?\b", "a"),
        (r"\bm\s*(\d{1,3})\s*(ultra|plus|s)?\b", "m"),
        (r"\bj\s*(\d{1,2})\s*(prime|plus|pro)?\b", "j"),
    ]

    for pattern, series in patterns:
        match = re.search(pattern, text)
        if match:
            model = series + match.group(1)
            suffix = match.group(2) if len(match.groups()) > 1 else None

            if suffix:
                if series in ("a", "m") and suffix == "s":
                    model += "s"
                else:
                    model += " " + suffix

            return "samsung " + model

    match = re.search(r"\b(\d{1,2})\s*fe\b", text)
    if match:
        return "samsung s" + match.group(1) + " fe"

    match = re.search(r"\b(\d{1,3})\s*a\b", text)
    if match:
        return "samsung a" + match.group(1)

    return "unknown"

Test Special Samsung Model Cases

In [60]:
tests = [
    "Galaxy Z TriFold",
    "سامسونجa36فجي تليفون حالته جميله",
    "Samsung 26 ultra",
    "سامسونج جلاكسي چى7برو",
    "Samsung Galaxy Z Fold 5",
    "Samsung Galaxy Z Flip 6",
    "Samsung Galaxy A03 Core",
    "Samsung Galaxy A04e",
]

for title in tests:
    print(f"{title} -> {extract_samsung_model(title)}")

Galaxy Z TriFold -> samsung z trifold
سامسونجa36فجي تليفون حالته جميله -> samsung a36
Samsung 26 ultra -> samsung s26 ultra
سامسونج جلاكسي چى7برو -> samsung j7 pro
Samsung Galaxy Z Fold 5 -> samsung z fold5
Samsung Galaxy Z Flip 6 -> samsung z flip6
Samsung Galaxy A03 Core -> samsung a03 core
Samsung Galaxy A04e -> samsung a04e

 Extract Samsung Models and Evaluate Coverage

In [61]:
samsung_titles = stage1_df.loc[
    stage1_df["brand"] == "samsung"
].copy()

samsung_titles["samsung_model"] = samsung_titles["title"].apply(
    extract_samsung_model
)

total = len(samsung_titles)
unknown = (samsung_titles["samsung_model"] == "unknown").sum()
known = total - unknown

print("Total Samsung ads:", total)
print("Models extracted:", known)
print("Unknown models:", unknown)
print(
    "Extraction coverage:",
    round(known / total * 100, 2) if total else 0,
    "%"
)

display(
    samsung_titles[
        ["title", "samsung_model"]
    ].head(20)
)

Total Samsung ads: 1074
Models extracted: 1051
Unknown models: 23
Extraction coverage: 97.86 %

                                                 title      samsung_model
13   Samsung S24 Ultra زيرو 256GB تيتانيوم مدفوع ال...  samsung s24 ultra
18                                   Samsung S25 Ultra  samsung s25 ultra
19                                 سامسونج اس 24 الترا  samsung s24 ultra
25                                     Galaxy Z Flip 8    samsung z flip8
29                               Galaxy Z Fold 8 ultra    samsung z fold8
33   Galaxy TriFold dual sim 512/16G Black جديد خال...            unknown
37                                 سامسونج اس 24 الترا  samsung s24 ultra
38   Galaxy S26 Ultra dual sim 256/12G Sky Blue  Bl...  samsung s26 ultra
40   موبايل Samsung S23 Ultra مستعمل (256GB / 12GB ...  samsung s23 ultra
44                                    Galaxy Z TriFold  samsung z trifold
55                                 سامسونج اس 25 الترا  samsung s25 ultra
61                                     سامسونج ايه 52s       samsung a52s
74                                      سامسونج ايه 23        samsung a23
91                               سامسونج اف 70 اي 5 جي        samsung f70
95                                    سامسونج اس 21 fe     samsung s21 fe
97                                 سامسونج اس 25 الترا  samsung s25 ultra
99                                   Samsung S23 Ultra  samsung s23 ultra
109                                  Samsung S24 Ultra  samsung s24 ultra
136                                     سامسونج ايه 36        samsung a36
150                            Samsung S26 Ultra 512gb  samsung s26 ultra

Review Unknown Samsung Models

In [62]:
unknown_samsung = samsung_titles.loc[
    samsung_titles["samsung_model"] == "unknown",
    ["title"]
]

print("Unknown Samsung ads:", len(unknown_samsung))
display(unknown_samsung)

Unknown Samsung ads: 23

                                                  title
33    Galaxy TriFold dual sim 512/16G Black جديد خال...
586                          سامسونج جالكسي    Gt-55360
1972  فرصة عظيمة بسعر مغري  لن يتكرر  موبايل  سامسون...
2063                                Samsung Other Model
2605                                Samsung Other Model
2861                    بيع تليفون سامسونج جلاكسي الترا
2988                                Samsung g4+0اقتصادي
3032       سامسونج كسر زيرو مفهوش خدش بكل حاجتو الاصلية
3401                                     موبايل سامسونج
4004                                            سامسونج
4020                     موبل سامسونج ِ30 جيد جدا للبيع
4188                                Samsung Other Model
4488          عدد ثلاثة موبيل سامسونج  و أوبو  و  هواوى
4490            سامسونجA51هندى بالعلبه واسكرينه وجرابات
5204                                Samsung Other Model
5420                 موبايل سامسونج استعمال شهر كالجديد
5976                                            سامسونج
6296                                Samsung Other Model
6616                                      سامسونج8+لقطه
6888                          سامسونج بأقل من ٣٠٠٠ جنيه
6905                        موبايل سامسونج جلاكسي جراند
7052                       سامسونج و أخرى وانواع مختلفه
7267                                       سامسونج فولد

Save Samsung Models to Stage 1 Dataset

In [63]:
samsung_mask = stage1_df["brand"] == "samsung"

stage1_df.loc[samsung_mask, "samsung_model"] = (
    stage1_df.loc[samsung_mask, "title"]
    .apply(extract_samsung_model)
)

print("Samsung model column added successfully.")
print("Samsung rows:", samsung_mask.sum())
print(
    "Samsung unknown:",
    (stage1_df.loc[samsung_mask, "samsung_model"] == "unknown").sum()
)

Samsung model column added successfully.
Samsung rows: 1074
Samsung unknown: 23

Review Samsung Model Distribution

In [64]:
display(
    stage1_df.loc[
        stage1_df["brand"] == "samsung",
        "samsung_model"
    ].value_counts().head(30)
)

samsung_model
samsung s25 ultra    87
samsung s24 ultra    63
samsung a36          45
samsung a56          44
samsung a17          35
samsung a16          30
samsung a15          26
samsung a55          24
unknown              23
samsung a07          23
samsung a57          22
samsung a52          21
samsung s22 ultra    21
samsung s21 ultra    20
samsung a26          18
samsung a51          18
samsung a37          17
samsung s25 fe       17
samsung a13          17
samsung s23 ultra    16
samsung a71          16
samsung a23          14
samsung a35          14
samsung a54          13
samsung a32          12
samsung a20          10
samsung a53          10
samsung s26 ultra     9
samsung s21 plus      9
samsung a30           8
Name: count, dtype: int64

Identify Samsung Parts and Accessories Listings

In [65]:
parts_pattern = (
    r"شاشه|شاشة|قطع غيار|بورده|بوردة|بطاريه|بطارية|"
    r"جراب|اسكرينه|اسكرينة|شاحن|سماعه|سماعة|"
    r"screen|spare parts|battery|charger|case|cover"
)

samsung_parts = stage1_df.loc[
    (stage1_df["brand"] == "samsung")
    & stage1_df["title"].str.contains(
        parts_pattern, case=False, na=False, regex=True
    ),
    ["title", "samsung_model"]
]

print("Possible parts/accessories:", len(samsung_parts))
display(samsung_parts.head(30))

Possible parts/accessories: 23

                                                  title        samsung_model
543   Samsung A32 128GB - سبق تغيير الشاشة بشاشة اصل...          samsung a32
2763  Galaxy M55 5Gمعاه شاحن45 الاورجينال وسكرين اما...          samsung m55
2776  سامسونج  A27 (5G)  سعة 128 جيجا، ذاكرة RAM 8 ج...          samsung a27
2864                     سامسونج فولد٣ فاصل شاشه داخليه        samsung fold3
2937   Samsung A5 78% battery charging port need fixing           samsung a5
2994  سامسونج ايه 15 رامات 8 مساحه 128 بدون كرتونه و...          samsung a15
3079                             سامسونج galaxy xcover7      samsung xcover7
3877  Samsung A30s متفتحش مغيرش حاجه بصمه شاشه طلقه ...         samsung a30s
4127   سامسونج A23 ٦ رام ١٢٨ مساحة تخزين بالشاحن الاصلي          samsung a23
4400                               Samsung XCover 6 Pro  samsung xcover6 pro
4472  موبايل سامسونج A36 8 Ram- 256 GB بالعلبة والضم...          samsung a36
4478  سامسونج A52 حاله فوق الممتازه made in india با...          samsung a52
4481  موبايل سامسونج A16 RAM 6 - 128 GB استعمال حريم...          samsung a16
4490            سامسونجA51هندى بالعلبه واسكرينه وجرابات              unknown
4674  سامسونج نوت 10 بلس مغير شاشه عليه ضريبه 1٤00 ج...  samsung note10 plus
4841  سامسونج A51 بالعلبه هندى وجرابات ظهر سيليكون و...          samsung a51
5459                         شاشة samsung a34 خلع اصلية          samsung a34
5513  سامسونج ايه 51 حاله نادره بدون صيانه بالعلبه و...          samsung a51
5753  سامسونج ايه 51 هندى بالعلبه حاله نادره بدون صي...          samsung a51
5889                                  Samsung x cover 5      samsung xcover5
7798               محتاج شاشه  سامسونج A82 5G quantum 2          samsung a82
7920  Samsung Z Fold 4  dual sim  256gb needs a  int...      samsung z fold4
8096  Samsung Galaxy M12 Mint condition box and char...          samsung m12

Mark Non-Phone Listings

In [66]:
parts_only_pattern = (
    r"^\s*(?:شاشه|شاشة|بطاريه|بطارية|بورده|بوردة|"
    r"جراب|اسكرينه|اسكرينة|شاحن|سماعه|سماعة)\b"
    r"|محتاج شاشه|محتاج شاشة|مطلوب شاشه|مطلوب شاشة"
    r"|screen\s+(?:samsung|for\s+samsung)"
)

stage1_df["is_phone_listing"] = True

parts_mask = (
    (stage1_df["brand"] == "samsung")
    & stage1_df["title"].str.contains(
        parts_only_pattern, case=False, na=False, regex=True
    )
)

stage1_df.loc[parts_mask, "is_phone_listing"] = False

print("Non-phone listings marked:", (~stage1_df["is_phone_listing"]).sum())

display(
    stage1_df.loc[
        ~stage1_df["is_phone_listing"],
        ["title", "brand", "samsung_model"]
    ]
)

Non-phone listings marked: 2

                                     title    brand samsung_model
5459            شاشة samsung a34 خلع اصلية  samsung   samsung a34
7798  محتاج شاشه  سامسونج A82 5G quantum 2  samsung   samsung a82

Review Brand Distribution in Training Data

In [67]:
print("Brands in training data:")
display(stage1_df["brand"].value_counts(dropna=False))

Brands in training data:

brand
apple       2936
samsung     1074
xiaomi       534
oppo         428
NaN          347
honor        274
realme       233
infinix      164
vivo         152
huawei       125
motorola      31
oneplus       24
zte           18
tecno         17
itel          15
google        14
sony          11
nokia          9
lenovo         8
lg             3
Name: count, dtype: int64

# Xiaomi

Some helper functions

In [68]:
def explore_brand(brand, n=20, seed=10):
    brand_titles = stage1_df.loc[stage1_df["brand"] == brand].copy()
    print(f"Total {brand} ads:", len(brand_titles))
    display(
        brand_titles[["title", "title_punct_normalized"]].sample(
            n=min(n, len(brand_titles)), random_state=seed
        )
    )



def evaluate_brand(brand, show_rows=20, max_unknown=20):
    col = f"{brand}_model"
    mask = stage1_df["brand"] == brand

    # Extract models; unmatched titles return "unknown"
    results = stage1_df.loc[mask, "title"].apply(
        lambda title: extract_brand_model(title, brand)
    )

    # Save results
    stage1_df.loc[mask, col] = results

    # Evaluate extraction
    total = len(results)
    unknown = (results == "unknown").sum()
    known = total - unknown
    coverage = known / total * 100 if total else 0

    print(f"Brand: {brand}")
    print(f"Total ads: {total}")
    print(f"Models extracted: {known}")
    print(f"Unknown models: {unknown}")
    print(f"Extraction coverage: {coverage:.2f}%")

In [69]:
explore_brand("xiaomi")

Total xiaomi ads: 534

,title,title_punct_normalized
391,شاومي بوكو ام 3 برو,شاومي بوكو ام 3 برو
1732,شاومي بوكو اكس 3 برو,شاومي بوكو اكس 3 برو
6214,للبيع او البدل Redmi A7 جديد فتحه كرتونه,للبيع او البدل redmi a7 جديد فتحه كرتونه
1798,شاومي ريدمي 9 تى,شاومي ريدمي 9 تي
5130,شاومي ريدمي 13,شاومي ريدمي 13
1151,شاومي موديل اخر,شاومي موديل اخر
3034,شاومي ريدمي 10,شاومي ريدمي 10
2339,Redmi 15C 5G 256/8 كسر زيرو هدية 8000ج أكتوبر,redmi 15c 5g 256/8 كسر زيرو هدية 8000ج اكتوبر
2263,لقطة Redmi 15C زيرو - 256/8 - ضمان 18 شهر - 80...,لقطة redmi 15c زيرو 256/8 ضمان 18 شهر 8000 جنيه
3418,شاومي بوكو ام 6 برو,شاومي بوكو ام 6 برو
6402,Xiaomi Redmi Note 14 Pro plus,xiaomi redmi note 14 pro plus
763,شاومي 15 بيع وبدل,شاومي 15 بيع وبدل
2122,شاومي ريدمي نوت 11 تى,شاومي ريدمي نوت 11 تي
6021,شاومي ريدمي نوت 13,شاومي ريدمي نوت 13
4002,شاومي ريدمي نوت 5A,شاومي ريدمي نوت 5a
7885,redmi note 13 pro 256g,redmi note 13 pro 256g
4726,شاومي موديل اخر,شاومي موديل اخر
7794,تلفون Redmi9A,تلفون redmi9a
8146,شاومي ريدمي نوت 10 برو,شاومي ريدمي نوت 10 برو
3053,Xiaomi Poco F7 Global Edition,xiaomi poco f7 global edition

# Define Xiaomi Model Rules

In [70]:
ARABIC_DIGITS = str.maketrans("٠١٢٣٤٥٦٧٨٩", "0123456789")
BRAND_WORDS = {
    "شاومي": "xiaomi", "ريدمي": "redmi", "ردمي": "redmi", "بوكو": "poco",
    "اوبو": "oppo", "رينو": "reno", "فايند": "find",
    "ريلمي": "realme", "ريالمي": "realme", "نارزو": "narzo",
    "هونر": "honor", "هونور": "honor", "اونر": "honor", "ماجيك": "magic",
    "انفينكس": "infinix", "انفنكس": "infinix",
    "فيفو": "vivo", "هواوي": "huawei", "نوفا": "nova",
    "موتورولا": "motorola", "موتو": "moto", "ريزر": "razr",
    "ون بلس": "oneplus", "وان بلس": "oneplus", "ونبلس": "oneplus", "نورد": "nord",
    "تكنو": "tecno", "سبارك": "spark", "كامون": "camon", "فانتوم": "phantom", "بوفا": "pova",
    "ايتل": "itel", "جوجل": "google", "بيكسل": "pixel", "سوني": "sony",
    "اكسبيريا": "xperia", "اكسبريا": "xperia", "نوكيا": "nokia", "لينوفو": "lenovo",
    "انفنيكس": "infinix", "نوبيا": "nubia", "بورا": "pura", "ستايلس": "stylus",
    "رازر": "razr", "بكسل": "pixel",
}

SERIES_WORDS = {
    "برو": "pro", "بلس": "plus", "الترا": "ultra", "ماكس": "max", "لايت": "lite",
    "نوت": "note", "ميني": "mini", "فولد": "fold", "فليب": "flip",
    "بلاي": "play", "برايم": "prime",
    "هوت": "hot", "سمارت": "smart", "ايدج": "edge",
}

ARABIC_RANGE = "\u0600-\u06FF"


def prepare_text(title, letters=None, aliases=None, pre=None):
    text = str(title).lower().translate(ARABIC_DIGITS)
    text = re.sub(r"[\u064B-\u065F\u0670\u0640]", "", text)
    for ch in "أإآ":
        text = text.replace(ch, "ا")
    text = text.replace("ى", "ي")
    text = text.replace("+", " plus ").replace("_", " ")
    text = re.sub(r"[^\w\s\.]", " ", text)
    text = re.sub(r"(?<!\d)\.|\.(?!\d)", " ", text)
    text = re.sub(
        rf"(?<=[{ARABIC_RANGE}])(?=[a-z0-9])|(?<=[a-z0-9])(?=[{ARABIC_RANGE}])",
        " ", text
    )

    all_brand_words = {**BRAND_WORDS, **(aliases or {})}
    for old in sorted(all_brand_words, key=len, reverse=True):
        text = text.replace(old, f" {all_brand_words[old]} ")

    for old, new in SERIES_WORDS.items():
        text = re.sub(rf"(?<![{ARABIC_RANGE}]){old}(?![{ARABIC_RANGE}])", f" {new} ", text)

    text = re.sub(r"\s+", " ", text).strip()

    text = re.sub(r"\bnot\s*(?=\d)", "note ", text)                      # not 10 -> note 10
    text = re.sub(r"(?<=\d)(pro|max|plus|ultra|lite|mini)\b", r" \1", text)  # 14pro -> 14 pro
    text = re.sub(r"(?<=\d)bro\b", " pro", text)                           # x3bro -> x3 pro
    text = re.sub(r"(?<=[a-z])5g\b", " 5g", text)                          # 50s5g -> 50s 5g

    for pattern, repl in (pre or []):
        text = re.sub(pattern, repl, text)

    for old, new in (letters or {}).items():
        text = re.sub(rf"(?<!\S){old}\s*(?=\d)", f" {new} ", text)
        text = re.sub(rf"(?<=\d)\s*{old}(?![{ARABIC_RANGE}])", f"{new} ", text)

    return re.sub(r"\s+", " ", text).strip()


BRAND_CONFIG = {}


def extract_brand_model(title, brand):
    cfg = BRAND_CONFIG[brand]
    raw = str(title).lower()
    if len(brand) >= 4:
        raw = re.sub(rf"({brand})(?=[a-z0-9])", r"\1 ", raw)
    text = prepare_text(raw, cfg.get("letters"), cfg.get("aliases"), cfg.get("pre"))

    for pattern, template in cfg["rules"]:
        match = re.search(pattern, text)
        if match:
           groups = [g or "" for g in match.groups()]
           model = template.format("", *groups)

           model = re.sub(r"\s+", " ", model).strip()
           model = re.sub(r"\b(pro|max|plus|ultra|lite|mini)\b", r"\1", model)

           return f"{brand} {model}".strip()

    return "unknown"

In [71]:

BRAND_CONFIG["xiaomi"] = {
    "letters": {
        "اكس": "x",
        "اف": "f",
        "ام": "m",
        "سي": "c",
        "كيه": "k",
        "ايه": "a",
        "تي": "t",
        "مي": "mi",
    },

    "aliases": {
        "ميكس": "mix",
        "تربو": "turbo",
        "بلاك شارك": "black shark",
    },

    "pre": [
        (r"xiaomi\s+مي\s+تن\s+تي", "xiaomi mi 10t"),
        (r"xiaomi\s+بوك\s+اكس\s+ثري\s+pro", "poco x3 pro"),
        (r"xiaomi\s+بوك\s+اكس\s+ثري", "poco x3"),
        (r"\bxiaomi\s+18\s*fold\b", "xiaomi 18 fold"),
        (r"\bxiaomi\s+fold\s+xiaomi\s+18\s*fold\b",
         "xiaomi fold xiaomi 18 fold"),
    ],

    "rules": [
        # Black Shark
        (
            r"\bblack\s*shark\s*(\d{1,2})(?:\s*(pro))?\b",
            "black shark {1} {2}"
        ),

        (
            r"\bredmi\s*note\s*(\d{1,2})"
            r"\s*(s|t|a)?"
            r"\s*(pro\s*plus|pro\s*max|pro|plus)?"
            r"\s*(5g)?\b",
            "redmi note {1}{2} {3} {4}"
        ),

        # Redmi K
        (
            r"\bredmi\s*k\s*(\d{2,3})"
            r"\s*(pro\s*max|pro|ultra|plus)?\b",
            "redmi k{1} {2}"
        ),

        # Redmi Turbo
        (
            r"\bredmi\s*turbo\s*(\d{1,2})\s*(pro|max)?\b",
            "redmi turbo {1} {2}"
        ),

        # Redmi A / C
        (
            r"\bredmi\s*([ac])\s*(\d{1,2})(y)?\b",
            "redmi {1}{2}{3}"
        ),

        # Redmi 12C / 13C / 12 5G / 13 5G وما شابه
        (
            r"\bredmi\s*(\d{1,2})\s*(c|a|t|s|x)"
            r"\s*(prime|pro|plus)?\b",
            "redmi {1}{2} {3}"
        ),

        (
            r"\bredmi\s*(\d{1,2})"
            r"\s*(prime|pro|plus)?\b",
            "redmi {1} {2}"
        ),

        # POCO X / F / M / C
        (
            r"\bpoco\s*([xfmc])\s*(\d{1,2})"
            r"\s*(pro|max|gt|ultra|plus)?\b",
            "poco {1}{2} {3}"
        ),

        (
            r"\bpoco\b.*?\b([xfmc])\s*(\d{1,2})"
            r"\s*(pro|max|gt|ultra|plus)?\b",
            "poco {1}{2} {3}"
        ),

        # Xiaomi Mix Fold / Flip
        (
            r"\bmix\s*(fold|flip)\s*(\d{1,2})?\b",
            "mix {1} {2}"
        ),

        # Xiaomi 18 Fold أو Xiaomi 18fold
        (
            r"\bxiaomi\s*(\d{1,2})\s*fold\b",
            "{1} fold"
        ),

        # Mi A
        (
            r"\bmi\s*a\s*(\d{1,2})\b",
            "mi a{1}"
        ),

        # Mi Note
        (
            r"\bmi\s*note\s*(\d{1,2})\s*(pro|lite)?\b",
            "mi note {1} {2}"
        ),

        # Mi / Mi T
        (
            r"\bmi\s*(\d{1,2}t?)\s*(pro|lite|ultra)?\b",
            "mi {1} {2}"
        ),

        # Xiaomi 12C -> Redmi 12C
        (
            r"\bxiaomi\s*(\d{1,2})\s*c\b",
            "redmi {1}c"
        ),

        # Xiaomi A3 -> Redmi A3
        (
            r"\bxiaomi\s*a\s*(\d{1,2})\b",
            "redmi a{1}"
        ),

        (
            r"\bxiaomi\s*(\d{1,2}t?)"
            r"\s*(pro|lite|ultra|plus)?\b",
            "{1} {2}"
        ),

        # Ultra 15 -> 15 ultra
        (
            r"\bultra\s*(\d{2})\b",
            "{1} ultra"
        ),

        (
            r"\bc\s*(\d{2})\b",
            "redmi c{1}"
        ),

        (
            r"\bnote\s*(\d{1,2})"
            r"\s*(s|t)?"
            r"\s*(pro\s*plus|pro\s*max|pro|plus)?"
            r"\s*(5g)?\b",
            "redmi note {1}{2} {3} {4}"
        ),
    ],
}

In [72]:
evaluate_brand("xiaomi")

Brand: xiaomi
Total ads: 534
Models extracted: 505
Unknown models: 29
Extraction coverage: 94.57%

In [73]:
stage1_df.loc[
    stage1_df["xiaomi_model"].eq("unknown"),
    ["title", "title_normalized", "xiaomi_model"]
].head(69)

,title,title_normalized,xiaomi_model
367,Poco بوكو,poco بوكو,unknown
680,شاومي 111T,شاومي 111t,unknown
946,شاومي موديل اخر,شاومي موديل اخر,unknown
1151,شاومي موديل اخر,شاومي موديل اخر,unknown
1220,شاومي موديل اخر,شاومي موديل اخر,unknown
1636,شاومي موديل اخر,شاومي موديل اخر,unknown
2219,شاومي موديل اخر,شاومي موديل اخر,unknown
2541,شاومي موديل اخر,شاومي موديل اخر,unknown
2831,شاومي ريد مى,شاومي ريد مي,unknown
2856,شاومي موديل اخر,شاومي موديل اخر,unknown
3055,شاومي ريدمي,شاومي ريدمي,unknown
3279,شاومي موديل اخر,شاومي موديل اخر,unknown
3287,شاومي موديل اخر,شاومي موديل اخر,unknown
3578,شاومي موديل اخر,شاومي موديل اخر,unknown
3647,شاومي موديل اخر,شاومي موديل اخر,unknown
4077,شاومي موديل اخر,شاومي موديل اخر,unknown
4339,شاومي موديل اخر,شاومي موديل اخر,unknown
4726,شاومي موديل اخر,شاومي موديل اخر,unknown
4769,شاومي موديل اخر,شاومي موديل اخر,unknown
5442,ريدمي نوت 110 t pro( ارخص هاتف ريدمي )فائق,ريدمي نوت 110 t pro( ارخص هاتف ريدمي )فائق,unknown
5721,شاومي موديل اخر,شاومي موديل اخر,unknown
6053,شاوميx بحاله جيده 64 جيجا بالشاحن,شاوميx بحاله جيده 64 جيجا بالشاحن,unknown
6200,لو عندك موبايل شاومي عاوز تبيعو كلمنا فورآ هنش...,لو عندك موبايل شاومي عاوز تبيعو كلمنا فورا هنش...,unknown
6248,شاومي ريدمي 114,شاومي ريدمي 114,unknown
6435,شاومي موديل اخر,شاومي موديل اخر,unknown
7009,شاومي,شاومي,unknown
7204,ريدمي A150 يعملل بحالة ممتازة معاه الكرتونة,ريدمي a150 يعملل بحالة ممتازة معاه الكرتونة,unknown
7316,شاومي موديل اخر,شاومي موديل اخر,unknown
7637,شاومي موديل اخر,شاومي موديل اخر,unknown

# Oppo

In [74]:
explore_brand("oppo")

Total oppo ads: 428

,title,title_punct_normalized
7739,اوبو A60 ذاكره ٢٥٦ حاله ممتازه,اوبو a60 ذاكره 256 حاله ممتازه
5758,اوبو ايه 74,اوبو ايه 74
1623,اوبو رينو 10,اوبو رينو 10
3729,اوبو موديل اخر,اوبو موديل اخر
812,oppo a6pro,oppo a6pro
7650,اوبو اي 5x,اوبو اي 5x
2779,اوبو رينو 8 تي,اوبو رينو 8 تي
1349,اوبو ايه 6 اكس,اوبو ايه 6 اكس
4738,OPPO A96,oppo a96
1955,Opoo reno 7,opoo reno 7
5226,اوبو اف 5,اوبو اف 5
7938,بيع موبايل اوبو A1K,بيع موبايل اوبو a1k
7694,اوبو ايه 93,اوبو ايه 93
4093,اوبو موديل اخر,اوبو موديل اخر
8041,اوبو رينو 5,اوبو رينو 5
6345,اوبو رينو 3 ب 2000 ج,اوبو رينو 3 ب 2000 ج
5651,اوبو رينو7,اوبو رينو7
1260,اوبو ايه 57,اوبو ايه 57
6903,اوبو رينو 15 اف فايف جي مساحة ٢٥٦ ورام ١٢+١٢,اوبو رينو 15 اف فايف جي مساحة 256 ورام 12+12
404,اوبو رينو 10,اوبو رينو 10

In [75]:

BRAND_CONFIG["oppo"] = {
    "letters": {
        "ايه": "a",
        "اي": "a",
        "اية": "a",
        "اف": "f",
        "ار": "r",
        "تي": "t",
        "اكس": "x",
    },

    "aliases": {
        "opoo": "oppo",
        "oppooo": "oppo",
        "فايف جي": "5g",
        "فايند": "find",
    },

    "pre": [
        (r"\bfind\s+ان\s*(?=\d)", "find n "),

        # Turbo: تربو -> turbo
        (
            r"(?<![\u0600-\u06FF])تربو(?![\u0600-\u06FF])",
            "turbo"
        ),

        (r"\ba\s*6\s+اي\b", "a6i"),

        # A6 Pro
        (r"\ba\s*6\s+pro\b", "a6pro"),
    ],

    "rules": [
        (r"\ba\s*6a\b", "a6i"),

        # Find N series
        (
            r"\bfind\s*n\s*(\d{1,2})\b",
            "find n{1}"
        ),

        # Find X series
        (
            r"\bfind\s*x\s*(\d{1,2})\s*(pro|plus|ultra)?\b",
            "find x{1} {2}"
        ),

        # K series: K13 Turbo Pro 5G
        (
            r"\bk\s*(\d{1,2})\s*turbo\s*(pro)?\s*(5g)?\b",
            "k{1} turbo {2} {3}"
        ),

        # Reno series: Reno 7, Reno 8T, Reno 15F 5G
        (
            r"\breno\s*(\d{1,2})\s*(t|f|z)?\s*"
            r"(pro\s*plus|pro|plus)?\s*(5g)?\b",
            "reno {1}{2} {3} {4}"
        ),

        # A series: A60, A5i, A6 Pro, A6X, A1K
        (
            r"\ba\s*(\d{1,3})\s*"
            r"(pro\s*plus|pro|plus|x|k|s|i)?\s*(5g)?\b",
            "a{1}{2} {3}"
        ),

        # F series: F5, F1s
        (
            r"\bf\s*(\d{1,2})\s*(s|x|pro)?\b",
            "f{1}{2}"
        ),

        # R series: R15 Pro
        (
            r"\br\s*(\d{1,2})\s*(pro|plus)?\b",
            "r{1} {2}"
        ),
    ]
}

In [76]:
evaluate_brand("oppo")

Brand: oppo
Total ads: 428
Models extracted: 385
Unknown models: 43
Extraction coverage: 89.95%

In [77]:
stage1_df.loc[
    stage1_df["oppo_model"].eq("unknown"),
    ["title", "title_normalized", "oppo_model"]
].head(69)

,title,title_normalized,oppo_model
572,اوبو موديل اخر,اوبو موديل اخر,unknown
629,كوبي نسخه اولي اصدار اماراتي OPPO 16 وصــــــ...,كوبي نسخه اولي اصدار اماراتي oppo 16 وصــــــ...,unknown
1185,اوبو موديل اخر,اوبو موديل اخر,unknown
1465,اوبو موديل اخر,اوبو موديل اخر,unknown
1565,اوبو 16f,اوبو 16f,unknown
1708,اوبو موديل اخر,اوبو موديل اخر,unknown
1935,OPPO Other Model,oppo other model,unknown
2129,اوبو فايند إن,اوبو فايند ان,unknown
2174,اوبو موديل اخر,اوبو موديل اخر,unknown
2210,اوبو موديل اخر,اوبو موديل اخر,unknown
2383,اوبو موديل اخر,اوبو موديل اخر,unknown
2397,اوبو موديل اخر,اوبو موديل اخر,unknown
2711,اوبو موديل اخر,اوبو موديل اخر,unknown
2717,اوبو موديل اخر,اوبو موديل اخر,unknown
3067,اوبو موديل اخر,اوبو موديل اخر,unknown
3585,موبايل اوبو للبيع,موبايل اوبو للبيع,unknown
3729,اوبو موديل اخر,اوبو موديل اخر,unknown
3790,موبايل مختلف وفخم جدًا لعشاق التميز OPPO Find ...,موبايل مختلف وفخم جدا لعشاق التميز oppo find n...,unknown
3858,اوبو موديل اخر,اوبو موديل اخر,unknown
4070,"Oppo - مستعمل بحالة جيدة, كاميرا ثلاثية","oppo - مستعمل بحالة جيدة, كاميرا ثلاثية",unknown
4093,اوبو موديل اخر,اوبو موديل اخر,unknown
4466,OPPO Reno,oppo reno,unknown
4497,اوبو موديل اخر,اوبو موديل اخر,unknown
4661,OPPO Other Model,oppo other model,unknown
4908,oppoAlk,oppoalk,unknown
4964,اوبو موديل اخر,اوبو موديل اخر,unknown
5096,oppo and Other Model,oppo and other model,unknown
5171,OPPO Other Model,oppo other model,unknown
5179,اوبو موديل اخر,اوبو موديل اخر,unknown
5660,اوبو رينو,اوبو رينو,unknown
5903,اوبو موديل اخر,اوبو موديل اخر,unknown
5933,اوبو موديل اخر,اوبو موديل اخر,unknown
6190,اوبو موديل اخر,اوبو موديل اخر,unknown
6356,اوبو موديل اخر,اوبو موديل اخر,unknown
6471,اوبو موديل اخر,اوبو موديل اخر,unknown
6664,اوبو موديل اخر,اوبو موديل اخر,unknown
6778,اوبو موديل اخر,اوبو موديل اخر,unknown
6947,اوبو موديل اخر,اوبو موديل اخر,unknown
7046,اوبو موديل اخر,اوبو موديل اخر,unknown
7055,اوبو موديل اخر,اوبو موديل اخر,unknown
7324,اوبو موديل اخر,اوبو موديل اخر,unknown
7806,Oppooo,oppooo,unknown
7861,اوبو موديل اخر,اوبو موديل اخر,unknown

# honor

In [78]:
explore_brand("honor")

Total honor ads: 274

                         title    title_punct_normalized
7170                 Honor 600                 honor 600
736           هونر ماجيك 5 برو          هونر ماجيك 5 برو
1064                 HONOR WIN                 honor win
5428                هونر اكس 8                هونر اكس 8
5921            هونر موديل اخر            هونر موديل اخر
2119                  هونر x6c                  هونر x6c
6373             هونر اكس 9 سى             هونر اكس 9 سي
7297                Honor Play                honor play
5388                 Honor X8c                 honor x8c
705              هونر اكس 7 سى             هونر اكس 7 سي
5304                  هونر 600                  هونر 600
1352            Honor Magic V3            honor magic v3
2723      هونر x6b. . اكس ٦ بي      هونر x6b. . اكس 6 بي
7789             هونر اكس 9 بى             هونر اكس 9 بي
7898                  هونر X7a                  هونر x7a
7173         Honor Magic 8 pro         honor magic 8 pro
6392              هونر 200 برو              هونر 200 برو
6213            هونر اكس 7 ايه            هونر اكس 7 ايه
3323  Honor 600 للبدل او البيع  honor 600 للبدل او البيع
2215            هونر موديل اخر            هونر موديل اخر

In [79]:

BRAND_CONFIG["honor"] = {
    "letters": {
        "اكس": "x",
        "سي": "c",
        "سى": "c",
        "سيه": "c",
        "سيي": "c",
        "بي": "b",
        "بى": "b",
        "ايه": "a",
        "اي": "i",
    },

    "aliases": {
        "honour": "honor",
        "هونور": "honor",
        "اونر": "honor",
    },

    "pre": [
        # Arabic X: اكس 8 -> x 8
        (r"(?<![\u0600-\u06FF])اكس(?![\u0600-\u06FF])", "x"),

        # Arabic Magic V: ماجيك في 3 -> magic v 3
        (r"ماجيك\s+في(?=\s*\d)", "magic v"),

        # Correct likely typo only in the specific model context
        (r"\bhonor\s+wen\s+rt\b", "honor win rt"),
        (r"\bhonor\s+wen(?=\s+5g\b)", "honor win"),
    ],

    "rules": [
        # Honor X series: X6, X6b, X7a, X8c, X9c
        (r"\bx\s*(\d{1,2})\s*(c|b|a|i|d|pro|plus)?\b", "x{1}{2}"),

        # Arabic reversed format: 6 X -> X6
        (r"\b(\d{1,2})\s*x\s*(c|b|a)?\b", "x{1}{2}"),

        # Magic V series with a version number
        (r"\bmagic\s+v\s*(\d{1,2})\s*(pro|plus)?\b", "magic v{1} {2}"),

        # Magic V without a version number
        (r"\bmagic\s+v\b", "magic v"),

        # Magic numeric series: Magic 5 Pro, Magic 8 Pro
        (r"\bmagic\s*(\d{1,2})\s*(pro\s*plus|pro|plus|lite)?\b", "magic {1} {2}"),

        # Honor numeric series: Honor 200 Pro, Honor 600
        (r"\bhonor\s+(\d{2,3})\s*(pro\s*plus|pro|plus|lite)?\b", "{1} {2}"),

        # Honor Win RT / Win
        (r"\bwin\s+rt\b", "win rt"),
        (r"\bwin\b", "win"),

        # Honor Robot Phone / Robot
        (r"\brobot(?:\s+phone)?\b", "robot"),

        # Honor Play
        (r"\bplay\b", "play"),

        # Honor GT
        (r"\bgt\b", "gt"),

        # Honor 8 Pro / 8 Plus / 8 Lite
        (r"\bhonor\s+(\d{1,2})\s+(pro|plus|lite)\b", "{1} {2}"),

        # Honor 8X / 8C
        (r"\bhonor\s+(\d{1,2})\s*(x|c)\b", "{1}{2}"),
    ],
}

In [80]:
evaluate_brand("honor")

Brand: honor
Total ads: 274
Models extracted: 259
Unknown models: 15
Extraction coverage: 94.53%

In [81]:
stage1_df.loc[
    stage1_df["honor_model"].eq("unknown"),
    ["title", "title_normalized", "honor_model"]
].head(69)

,title,title_normalized,honor_model
2215,هونر موديل اخر,هونر موديل اخر,unknown
2825,هونر موديل اخر,هونر موديل اخر,unknown
2951,هونر ماجيك في 3 ( فولد ينطوي),هونر ماجيك في 3 ( فولد ينطوي),unknown
3945,هونر موديل اخر,هونر موديل اخر,unknown
4014,Honor 7Xe,honor 7xe,unknown
4035,هونر موديل اخر,هونر موديل اخر,unknown
4510,هونر ماجيك في 2,هونر ماجيك في 2,unknown
5921,هونر موديل اخر,هونر موديل اخر,unknown
6194,هونر موديل اخر,هونر موديل اخر,unknown
6199,لو عندك موبايل هونر عاوز تبيعو مستعمل او جديد...,لو عندك موبايل هونر عاوز تبيعو مستعمل او جديد...,unknown
6440,هونر موديل اخر,هونر موديل اخر,unknown
6598,هونر موديل اخر,هونر موديل اخر,unknown
6840,هونر موديل اخر,هونر موديل اخر,unknown
8078,هونر اكس d9,هونر اكس d9,unknown
8170,هونر موديل اخر,هونر موديل اخر,unknown

# Realme

In [82]:
explore_brand("realme")

Total realme ads: 233

,title,title_punct_normalized
1279,ريلمي,ريلمي
6385,ريلمى سى 65,ريلمي سي 65
6703,ريلمى 12,ريلمي 12
6506,ريلمى نوت 50,ريلمي نوت 50
7198,ريلمى 15 5g زيرو فتح علبه فقط رام ١٢ جيجا مساح...,ريلمي 15 5g زيرو فتح علبه فقط رام 12 جيجا مساح...
2637,Realme p3 ultra 256/12 New sealed Tax paid,realme p3 ultra 256/12 new sealed tax paid
1800,ريلمى نوت 50,ريلمي نوت 50
8015,ريلمى بى 1 برو,ريلمي بي 1 برو
6536,ريلمى موديل اخر,ريلمي موديل اخر
3801,ريلمى موديل i9 G5,ريلمي موديل i9 g5
5385,ريلمى سى 75,ريلمي سي 75
7607,Realme C55,realme c55
7299,ريلمى 10,ريلمي 10
7648,ريلمى 15 بروه,ريلمي 15 بروه
7877,لسرعة البيع ريلمي 12 برو بلس. في حالة الجديد ب...,لسرعة البيع ريلمي 12 برو بلس. في حالة الجديد ب...
2474,ريلمي c11,ريلمي c11
4875,Realme C55,realme c55
2110,Realme 6,realme 6
2828,ريلمي 15 برو,ريلمي 15 برو
3906,Realme C75x للتبديل بايفون xs أو للبيع,realme c75x للتبديل بايفون xs او للبيع

In [83]:

BRAND_CONFIG["realme"] = {
    "letters": {
        "سي": "c",
        "سى": "c",
        "بي": "p",
        "بى": "p",
        "س": "c",
    },

    "aliases": {
        "ريلمى": "realme",
        "نارزو": "narzo",
        "نوت": "note",
    },

    "pre": [
        # Arabic model names: specific phrases must come first
        (r"جي\s*تي\s*نيو", "gt neo"),
        (r"جي\s*تي", "gt"),
        (r"نوت(?=\s*\d)", "note"),
        (r"في(?=\s*\d)", "v"),

        # Fix common spelling variations
        (r"\bnot(?=\s*\d)", "note"),
        (r"\bgt(?=\d)", "gt "),
        (r"\bc(?=\d)", "c "),
        (r"\bp(?=\d)", "p "),
        (r"\ba(?=\d)", "a "),
        (r"\bproه\b", "pro"),
        (r"بروه\b", "pro"),
    ],

    "rules": [
        # GT Neo series — place before general GT rules
        (r"\bgt\s*neo\s*(\d{1,2})\s*(t)?\b", "gt neo {1}{2}"),

        # GT Master Edition
        (r"\bgt\s*master\s*edition\b", "gt master edition"),

        # GT Pro series
        (r"\bgt\s*(\d{1,2})\s*pro\b", "gt {1} pro"),

        # GT T series: GT 6T -> gt 6t
        (r"\bgt\s*(\d{1,2})\s*t\b", "gt {1}t"),

        # Standard GT series
        (r"\bgt\s*(\d{1,2})\b", "gt {1}"),

        # Note series
        (r"\bnote\s*(\d{2,3})\s*(x)?\b", "note {1}{2}"),

        # C series: C21Y, C100i, C3
        (r"\bc\s*(\d{1,3})\s*([a-z])?\b", "c{1}{2}"),

        # P series
        (r"\bp\s*(\d{1,2})\s*(ultra|pro\s*plus|pro|plus)?\b", "p{1} {2}"),

        # Narzo series
        (r"\bnarzo\s*(\d{1,3})\s*(pro|plus|x)?\b", "narzo {1} {2}"),

        # V series
        (r"\bv\s*(\d{1,2})\s*(t|i)?\b", "v{1}{2}"),

        # Numbered series with suffixes: Realme 9i, 14t, etc.
        (r"\brealme\s+(\d{1,2})\s*(pro\s*plus|pro|plus)\b", "{1} {2}"),
        (r"\brealme\s+(\d{1,2})\s*(i|t|x)\b", "{1}{2}"),
        (r"\brealme\s+(\d{1,2})\b", "{1}"),

        # A series
        (r"\ba\s*(\d{1,2})\s*(pro|plus)?\b", "a{1} {2}"),
    ],
}

In [84]:
evaluate_brand("realme")

Brand: realme
Total ads: 233
Models extracted: 214
Unknown models: 19
Extraction coverage: 91.85%

In [85]:
stage1_df.loc[
    stage1_df["realme_model"].eq("unknown"),
    ["title", "title_normalized", "realme_model"]
].head(69)

                  title   title_normalized realme_model
1279              ريلمي              ريلمي      unknown
1291    ريلمى موديل اخر    ريلمي موديل اخر      unknown
1674    ريلمى موديل اخر    ريلمي موديل اخر      unknown
2115    ريلمى موديل اخر    ريلمي موديل اخر      unknown
2197    ريلمى موديل اخر    ريلمي موديل اخر      unknown
2414              ريلمي              ريلمي      unknown
3061    ريلمى موديل اخر    ريلمي موديل اخر      unknown
3273    ريلمى موديل اخر    ريلمي موديل اخر      unknown
3381    ريلمى موديل اخر    ريلمي موديل اخر      unknown
3643    ريلمى موديل اخر    ريلمي موديل اخر      unknown
3683    ريلمى موديل اخر    ريلمي موديل اخر      unknown
3801  ريلمى موديل i9 G5  ريلمي موديل i9 g5      unknown
4848    ريلمى موديل اخر    ريلمي موديل اخر      unknown
5738    ريلمى موديل اخر    ريلمي موديل اخر      unknown
6415    ريلمى موديل اخر    ريلمي موديل اخر      unknown
6536    ريلمى موديل اخر    ريلمي موديل اخر      unknown
6797    ريلمى موديل اخر    ريلمي موديل اخر      unknown
7072    ريلمى موديل اخر    ريلمي موديل اخر      unknown
8024    ريلمى موديل اخر    ريلمي موديل اخر      unknown

# infinix

In [86]:
explore_brand("infinix")

Total infinix ads: 164

,title,title_punct_normalized
1453,إنفنيكس سمارت 7,انفنيكس سمارت 7
2886,Infinix Note 50s,infinix note 50s
4336,Infinix Hot 11 Play,infinix hot 11 play
1001,إنفنيكس سمارت ٦ اي,انفنيكس سمارت 6 اي
6799,إنفنيكس سمارت 6,انفنيكس سمارت 6
3449,إنفنيكس هوت 60 برو,انفنيكس هوت 60 برو
5022,Infinix Hot 60i – 12GB RAM / 128GB,infinix hot 60i – 12gb ram / 128gb
5300,بفضل الله متوفر كمية كبيره من انفنكس نوت ايدج ...,بفضل الله متوفر كمية كبيره من انفنكس نوت ايدج ...
3094,إنفنيكس سمارت 10,انفنيكس سمارت 10
7023,إنفنيكس نوت 50s استخدام ١٥ يوم,انفنيكس نوت 50s استخدام 15 يوم
7499,إنفنيكس هوت 50,انفنيكس هوت 50
633,Infinix GT 20 Pro,infinix gt 20 pro
7098,إنفنيكس هوت 50,انفنيكس هوت 50
1071,Infinix HOT 60 6/128,infinix hot 60 6/128
2675,إنفنيكس هوت 6 برو,انفنيكس هوت 6 برو
7825,إنفنيكس هوت60i,انفنيكس هوت60i
2565,إنفنيكس هوت 6 برو,انفنيكس هوت 6 برو
3519,InfinixGT30Pro,infinixgt30pro
2117,إنفنيكس نوت 60,انفنيكس نوت 60
5313,إنفنيكس موديل اخر,انفنيكس موديل اخر

In [87]:

BRAND_CONFIG["infinix"] = {
    "letters": {},

    "aliases": {
        "انفنيكس": "infinix",
        "انفنكس": "infinix",
        "انفينكس": "infinix",
        "إنفنيكس": "infinix",
        "سمارت": "smart",
        "سمار": "smart",
        "هوت": "hot",
        "نوت": "note",
        "زيرو": "zero",
        "ايدج": "edge",
        "برو": "pro",
        "بلاي": "play",
    },

    "pre": [
        # Arabic series names
        (r"جي\s*تي", "gt"),
        (r"اس(?=\s*\d)", "s"),
        (r"سمارت\s*زيرو", "smart zero"),

        # Smart 6 اي -> Smart 6i
        (r"\bsmart\s*(\d{1,2})\s*اي\b", r"smart \1i"),

        # Join brand and model if written together
        (r"\binfinix(?=[a-z])", "infinix "),

        # Separate series from numbers
        (r"\b(gt|smart|note|hot|zero|s)\s*(?=\d)", r"\1 "),

        # Separate suffixes from numbers
        (r"(?<=\d)(pro|plus|play|ultra|lite)\b", r" \1"),
    ],

    "rules": [
        # GT series
        (r"\bgt\s*(\d{1,2})\s*pro\b", "gt {1} pro"),
        (r"\bgt\s*(\d{1,2})\s*plus\b", "gt {1} plus"),
        (r"\bgt\s*(\d{1,2})\b", "gt {1}"),

        # Smart Zero
        (r"\bsmart\s+zero\b", "smart zero"),

        # Smart series
        (r"\bsmart\s*(\d{1,2})\s*i\b", "smart {1}i"),
        (r"\bsmart\s*(\d{1,2})\b", "smart {1}"),

        # Zero series: Zero 8i, Zero 30, etc.
        (r"\bzero\s*(\d{1,2})\s*(i|x|pro)?\b", "zero {1}{2}"),

        # Note Edge
        (r"\bnote\s*edge\b", "note edge"),

        # Note series: Note 50s, Note 60
        (r"\bnote\s*(\d{1,3})\s*(s|pro|plus|x|i)?\b", "note {1}{2}"),

        # Hot series with letter suffix: Hot 60i
        (r"\bhot\s*(\d{1,3})\s*(i|s|x)\b", "hot {1}{2}"),

        # Hot series with word suffix: Hot 11 Play, Hot 60 Pro
        (
            r"\bhot\s*(\d{1,3})\s*(play|pro\s*plus|pro|plus|ultra|lite)?\b",
            "hot {1} {2}"
        ),

        # S series: S4, S5
        (r"\bs\s*(\d{1,2})\s*(pro|plus|lite)?\b", "s{1} {2}"),
    ],
}

In [88]:
evaluate_brand("infinix")

Brand: infinix
Total ads: 164
Models extracted: 140
Unknown models: 24
Extraction coverage: 85.37%

In [89]:
stage1_df.loc[
    stage1_df["infinix_model"].eq("unknown"),
    ["title", "title_normalized", "infinix_model"]
].head(69)

                            title             title_normalized infinix_model
68           تليفون انفينكس للبيع         تليفون انفينكس للبيع       unknown
662             إنفنيكس موديل اخر            انفنيكس موديل اخر       unknown
710             إنفنيكس موديل اخر            انفنيكس موديل اخر       unknown
904   موبايل مستعمل انفنيكس سمارت  موبايل مستعمل انفنيكس سمارت       unknown
1184            إنفنيكس موديل اخر            انفنيكس موديل اخر       unknown
1420            إنفنيكس موديل اخر            انفنيكس موديل اخر       unknown
1451                Infinix Smart                infinix smart       unknown
1680          Infinix Other Model          infinix other model       unknown
1693            إنفنيكس موديل اخر            انفنيكس موديل اخر       unknown
1747            إنفنيكس موديل اخر            انفنيكس موديل اخر       unknown
2498            إنفنيكس موديل اخر            انفنيكس موديل اخر       unknown
2875            إنفنيكس موديل اخر            انفنيكس موديل اخر       unknown
3993            إنفنيكس موديل اخر            انفنيكس موديل اخر       unknown
4155                تليفون انفنكس                تليفون انفنكس       unknown
4236            إنفنيكس موديل اخر            انفنيكس موديل اخر       unknown
4291            إنفنيكس موديل اخر            انفنيكس موديل اخر       unknown
4865          Infinix Other Model          infinix other model       unknown
5133          Infinix Other Model          infinix other model       unknown
5187            إنفنيكس موديل اخر            انفنيكس موديل اخر       unknown
5313            إنفنيكس موديل اخر            انفنيكس موديل اخر       unknown
5946                Infinix Smart                infinix smart       unknown
6291            إنفنيكس موديل اخر            انفنيكس موديل اخر       unknown
6849            إنفنيكس موديل اخر            انفنيكس موديل اخر       unknown
7839          Infinix Other Model          infinix other model       unknown

# Vivo

In [90]:
explore_brand("vivo")

Total vivo ads: 152

,title,title_punct_normalized
7956,فيفو واى 29,فيفو واي 29
8143,فيفو V60,فيفو v60
858,فيفو في 70 5 جي,فيفو في 70 5 جي
6311,Vivo Y11,vivo y11
3132,فيفو واي 28,فيفو واي 28
6208,فيفو فى 29 برو,فيفو في 29 برو
1597,فيفو V60,فيفو v60
5613,Vivo V60 12 Ram,vivo v60 12 ram
4372,فيفو في 70 5 جي,فيفو في 70 5 جي
5341,فيفو اس 19 برو,فيفو اس 19 برو
6487,فيفو فى 40 لايت,فيفو في 40 لايت
7808,فيفو واى 29,فيفو واي 29
3472,Vivo Y 73,vivo y 73
175,فيفو واى 31,فيفو واي 31
1370,فيفو اس 19,فيفو اس 19
4347,فيفو V60,فيفو v60
5382,تليفون فيفو V60 رامات 12 ذاكره تخزين 256 التل...,تليفون فيفو v60 رامات 12 ذاكره تخزين 256 التلي...
5108,فيفو V60,فيفو v60
1503,Vivo X300 ultra,vivo x300 ultra
7179,vivo x300 pro,vivo x300 pro

In [91]:

BRAND_CONFIG["vivo"] = {
    "letters": {},

    "aliases": {
        "فيفو": "vivo",
        "اكس": "x",
        "إكس": "x",
        "فولد": "fold",
        "اف اي": "fe",
        "إف إي": "fe",
        "واي": "y",
        "واى": "y",
        "اس": "s",
        "إس": "s",
        "برو": "pro",
        "لايت": "lite",
        "الترا": "ultra",
        "نيو": "neo",
    },

    "pre": [
        # Arabic V-series notation: في 70 -> v 70
        (r"في(?=\s*\d)", "v"),

        # Arabic iQOO spelling variants
        (r"اي\s*كيو\s*او(?:و)?", "iqoo"),

        # Arabic model suffixes
        (r"اف\s*اي\b", "fe"),
        (r"اي(?=\s|$)", "e"),

        # Smart spacing for concatenated brand and model
        (r"\bvivo(?=[a-z])", "vivo "),

        # X Fold 3 Pro and similar
        (r"\bx\s*fold\s*(?=\d)", "x fold "),

        # Separate series from model number
        (r"\b(x|y|v|s)\s*(?=\d)", r"\1 "),

        # Separate suffixes when written directly after digits
        (r"(?<=\d)(pro|plus|ultra|lite|fe)\b", r" \1"),
    ],

    "rules": [
        # iQOO Neo series
        (
            r"\biqoo\s*neo\s*(\d{1,3})\s*(pro\s*plus|pro|plus|ultra)?\b",
            "iqoo neo {1} {2}"
        ),

        # X Fold series: X Fold 3 Pro
        (
            r"\bx\s*fold\s*(\d{1,2})\s*(pro|plus|ultra)?\b",
            "x fold {1} {2}"
        ),

        # X series with FE suffix: X300 FE
        (
            r"\bx\s*(\d{2,3})\s*(fe|ultra|pro|plus|lite|e)?\b",
            "x{1} {2}"
        ),

        # V series with suffix: V23e, V27e, V29e
        (
            r"\bv\s*(\d{1,3})\s*(e|s|d)\s*(pro|plus|lite|ultra)?\b",
            "v{1}{2} {3}"
        ),

        # V series with Pro / Lite / Ultra
        (
            r"\bv\s*(\d{1,3})\s*(pro|plus|lite|ultra)\b",
            "v{1} {2}"
        ),

        # V series without suffix
        (
            r"\bv\s*(\d{1,3})\b",
            "v{1}"
        ),

        # Titles like "Vivo 40 Lite" or "Vivo 50 Lite"
        (
            r"\bvivo\s+(\d{1,3})\s*lite\b",
            "v{1} lite"
        ),

        # S series with suffix
        (
            r"\bs\s*(\d{1,3})\s*(pro|plus|lite|ultra)?\b",
            "s{1} {2}"
        ),

        # Y series with suffixes: Y11D, Y31D, Y20s, Y17s
        (
            r"\by\s*(\d{1,3})\s*(s|d|e)\s*(pro|plus|lite|ultra)?\b",
            "y{1}{2} {3}"
        ),

        # Y series with Pro / Lite / Plus
        (
            r"\by\s*(\d{1,3})\s*(pro|plus|lite|ultra)\b",
            "y{1} {2}"
        ),

        # Standard Y series
        (
            r"\by\s*(\d{1,3})\b",
            "y{1}"
        ),
    ],
}

In [92]:
evaluate_brand("vivo")

Brand: vivo
Total ads: 152
Models extracted: 146
Unknown models: 6
Extraction coverage: 96.05%

In [93]:
stage1_df.loc[
    stage1_df["vivo_model"].eq("unknown"),
    ["title", "title_normalized", "vivo_model"]
].head(69)

,title,title_normalized,vivo_model
569,فيفو ٢٠١٥,فيفو 2015,unknown
1123,Vivo Other Model,vivo other model,unknown
3879,فيفووى11دى,فيفووي11دي,unknown
4854,فيفو مستعمل,فيفو مستعمل,unknown
5309,فيفو موديل اخر للبيع او البدل بأعلي مع دفع الفرق,فيفو موديل اخر للبيع او البدل باعلي مع دفع الفرق,unknown
6287,فيفو 19 جهاز زيروعجلة سرعات زيرو 6سرعات جميل...,فيفو 19 جهاز زيروعجلة سرعات زيرو 6سرعات جميل...,unknown

In [94]:
explore_brand("huawei")

Total huawei ads: 125

,title,title_punct_normalized
3399,هواوي Y7 برايم بلس,هواوي y7 برايم بلس
2418,Huawei Y9 Prime,huawei y9 prime
2267,هواوي بي 20 برو,هواوي بي 20 برو
3645,Huawei Mate X5 ميتx5,huawei mate x5 ميتx5
7217,هواوي Y7 برايم 2019 بشريحتي اتصال - 32 جيجا، 3...,هواوي y7 برايم 2019 بشريحتي اتصال 32 جيجا، 3 ج...
6485,هواوي ميت 10 برو,هواوي ميت 10 برو
2845,huawei هواوي,huawei هواوي
6728,هواوي y6p,هواوي y6p
4825,هواوي نوفا 7 se نسخه5,هواوي نوفا 7 se نسخه5
2187,هواوي بي 20 لايت,هواوي بي 20 لايت
335,هواوي موديل اخر,هواوي موديل اخر
3805,هواوي ميت 80 برو,هواوي ميت 80 برو
6729,هواوي ميت 40 برو,هواوي ميت 40 برو
6186,هواوي نوفا 3i,هواوي نوفا 3i
2146,هواوي بى 10 لايت,هواوي بي 10 لايت
312,هواويه ميت 10 لايت بحالة جيدة لم يفتح من قبل,هواويه ميت 10 لايت بحالة جيدة لم يفتح من قبل
4822,هواوي موديل اخر,هواوي موديل اخر
3024,هواوي mate 50 pro,هواوي mate 50 pro
716,هواوي بي 20 برو,هواوي بي 20 برو
2370,هواوي موديل اخر,هواوي موديل اخر

In [95]:
BRAND_CONFIG["huawei"] = {
    "letters": {},

    "aliases": {
        "هواوي": "huawei",
        "هواوى": "huawei",
        "هواويه": "huawei",

        "ميت": "mate",
        "نوفا": "nova",
        "بورا": "pura",

        "برايم": "prime",
        "برو": "pro",
        "لايت": "lite",
        "بلس": "plus",
        "الترا": "ultra",
        "التميت": "ultimate",

        "بي": "p",
        "بى": "p",
        "واي": "y",
        "واى": "y",
        "اكس": "x",
        "إكس": "x",
        "سي": "se",
    },

    "pre": [
        (r"ميت\s*(?=[a-z0-9])", "mate "),
        (r"نوفا\s*(?=\d)", "nova "),
        (r"بورا\s*(?=\d)", "pura "),

        (r"\bmat(?=\s*\d)", "mate "),
        (r"\bhuawei(?=[a-z])", "huawei "),

        (r"\b(y|p|nova|mate|pura)\s*(?=\d)", r"\1 "),
        (r"\bmate\s*x\s*t\s*(?=\d)", "mate xt "),
        (r"\bmate\s*x\s*(?=\d)", "mate x "),

        (r"\by\s*(\d{1,2})([a-z])\b", r"y \1\2"),

        (r"\by\s*(9)\s*(2019)\b", r"y \1 \2"),

        (r"(?<=\d)(pro|max|plus|ultra|lite|prime|ultimate)\b", r" \1"),
    ],

    "rules": [
        # -------------------------
        # Huawei Pura series
        # -------------------------
        (r"\bpura\s*(\d{2})\s*s\s*pro\s*max\b",
         "pura {1}s pro max"),

        (r"\bpura\s*(\d{2})\s*pro\s*max\b",
         "pura {1} pro max"),

        (r"\bpura\s*(\d{2})\s*(ultra|pro|plus|lite|max)\b",
         "pura {1} {2}"),

        (r"\bpura\s*(\d{2})\b",
         "pura {1}"),

        # -------------------------
        # Huawei Mate XT series
        # -------------------------
        (r"\bmate\s*xt\s*(\d{1,2})\s*(ultimate|pro|plus)?\b",
         "mate xt{1} {2}"),

        # -------------------------
        # Huawei Mate X series
        # -------------------------
        (r"\bmate\s*x\s*(\d{1,2})\s*(ultimate|pro|plus)?\b",
         "mate x{1} {2}"),

        # -------------------------
        # Huawei Mate series
        # -------------------------
        (r"\bmate\s*(\d{1,2})\s*(pro|plus|lite|x)?\b",
         "mate {1} {2}"),

        # -------------------------
        # Huawei Nova series
        # -------------------------
        (r"\bnova\s*(\d{1,2})\s*(se|i|pro|plus|lite|max)?\b",
         "nova {1}{2}"),

        # -------------------------
        # Huawei P series
        # -------------------------
        (r"\bp\s*(\d{1,2})\s*(pro|plus|lite|max)?\b",
         "p{1} {2}"),

        # -------------------------
        # Huawei Y series
        # -------------------------
        (r"\by\s*(7)\s*a\b",
         "y{1}a"),

        (r"\by\s*(6)\s*p\b",
         "y{1}p"),

        (r"\by\s*(\d{1,2})\s*(prime)\s*(plus)\b",
         "y{1} prime plus"),

        (r"\by\s*(\d{1,2})\s*(prime)\s*(2019)\b",
         "y{1} prime {3}"),

        (r"\by\s*(\d{1,2})\s*(2019|2020)\b",
         "y{1} {2}"),

        (r"\by\s*(\d{1,2})\s*(prime|pro|plus|lite|p|s)?\b",
         "y{1} {2}"),
    ],
}

In [96]:
evaluate_brand("huawei")

Brand: huawei
Total ads: 125
Models extracted: 98
Unknown models: 27
Extraction coverage: 78.40%

In [97]:
stage1_df.loc[
    stage1_df["huawei_model"].eq("unknown"),
    ["title", "title_normalized", "huawei_model"]
].head(69)

,title,title_normalized,huawei_model
335,هواوي موديل اخر,هواوي موديل اخر,unknown
419,هاتف هواوي واي,هاتف هواوي واي,unknown
423,هواوى نوفا ماكس استعمال 10 ايام بالفاتورة والض...,هواوي نوفا ماكس استعمال 10 ايام بالفاتورة والض...,unknown
1282,تلفون هواوي للبيع شغال,تلفون هواوي للبيع شغال,unknown
1575,هواوي موديل اخر,هواوي موديل اخر,unknown
1928,هواوي موديل اخر,هواوي موديل اخر,unknown
2080,هواوي ميت اكس تي التميت,هواوي ميت اكس تي التميت,unknown
2137,Huawei Other Model,huawei other model,unknown
2309,هواوي موديل اخر,هواوي موديل اخر,unknown
2370,هواوي موديل اخر,هواوي موديل اخر,unknown
2604,هواوي موديل اخر,هواوي موديل اخر,unknown
2608,موبايلين Huawei للبيع للتصليح أو قطع الغيار,موبايلين huawei للبيع للتصليح او قطع الغيار,unknown
2845,huawei هواوي,huawei هواوي,unknown
3025,هواوي موديل اخر,هواوي موديل اخر,unknown
3050,هواوي موديل اخر,هواوي موديل اخر,unknown
3564,Huawei Other Model,huawei other model,unknown
3742,هواوي موديل اخر,هواوي موديل اخر,unknown
3943,هواوي موديل اخر,هواوي موديل اخر,unknown
4034,هواوي موديل اخر,هواوي موديل اخر,unknown
4038,هواوي موديل اخر,هواوي موديل اخر,unknown
4822,هواوي موديل اخر,هواوي موديل اخر,unknown
5191,Huawei Other Model,huawei other model,unknown
5197,Huawei Other Model,huawei other model,unknown
6627,Huawei Other Model,huawei other model,unknown
6801,هواوي موديل اخر,هواوي موديل اخر,unknown
6958,هواوي موديل اخر,هواوي موديل اخر,unknown
7892,هواوي موديل اخر,هواوي موديل اخر,unknown

# motorola

In [98]:
explore_brand("motorola")

Total motorola ads: 31

,title,title_punct_normalized
5041,Motorola Stylus 5G بالقلم وارد أمريكا جديد خال...,motorola stylus 5g بالقلم وارد امريكا جديد خال...
1725,Motorola Edge 60 fusion,motorola edge 60 fusion
1585,موتورولا موتو جي 35,موتورولا موتو جي 35
346,موتورولا موتو جى 85,موتورولا موتو جي 85
1541,موتورولا ستايلس 5G بالقلم وارد امريكا كأنه جدي...,موتورولا ستايلس 5g بالقلم وارد امريكا كانه جدي...
5152,Motorola razr 60 ultra,motorola razr 60 ultra
2701,موتورولا موتو جى 85,موتورولا موتو جي 85
7139,Motorola 60 age fugen,motorola 60 age fugen
2586,Motorola Other Model,motorola other model
231,موتورولا ايدج 2023+,موتورولا ايدج 2023+
4928,موتورولا ايدج 50 فيوجن,موتورولا ايدج 50 فيوجن
2807,موتورولا موتو جى 85 كسر كسر الزيرو تم تنزيل ال...,موتورولا موتو جي 85 كسر كسر الزيرو تم تنزيل ال...
4326,موتورولا رازر 40 زيروو ضريبه جديد متبرشم,موتورولا رازر 40 زيروو ضريبه جديد متبرشم
1630,Motorola Moto G56,motorola moto g56
2552,موتورولا موتو جي 15,موتورولا موتو جي 15
5950,Motorola Signature,motorola signature
6012,موتورولا g04 بحاله الجديد,موتورولا g04 بحاله الجديد
7480,موتورولا موتو جي,موتورولا موتو جي
5685,موتورولا موتو جى 85,موتورولا موتو جي 85
2543,موتورولا g24 جهاز جبار,موتورولا g24 جهاز جبار

In [99]:
BRAND_CONFIG["motorola"] = {
    "letters": {},

    "aliases": {
        # Brand
        "موتورولا": "motorola",
        "موتورله": "motorola",

        # Moto G
        "موتو": "moto",
        "جي": "g",
        "جى": "g",

        # Edge
        "ايدج": "edge",
        "إيدج": "edge",

        # Razr
        "رازر": "razr",
        "ريزر": "razr",

        # Stylus
        "ستايلس": "stylus",
        "ستايلوس": "stylus",

        # Other model words
        "فيوجن": "fusion",
        "الترا": "ultra",
        "زيروو": "zero",
    },

    "pre": [
        # Brand normalization
        (r"\bmotorola(?=[a-z0-9])", "motorola "),

        # Moto G series
        (r"\bmoto\s*g\s*(?=\d)", "moto g "),

        # Edge series
        (r"\bedge\s*(?=\d)", "edge "),

        # Razr series
        (r"\brazr\s*(?=\d)", "razr "),

        # Stylus series
        (r"\bstylus\s*(?=\d)", "stylus "),

        # G04, G24, etc.
        (r"\bg\s*(?=\d)", "g "),

        # Separate suffixes attached to digits
        (r"(?<=\d)(ultra|fusion|stylus)\b", r" \1"),
    ],

    "rules": [
        # -------------------------
        # Motorola Edge
        # -------------------------

        # Reversed title: 50 Edge Fusion
        (r"\b(\d{2})\s*edge\s*fusion\b",
         "edge {1} fusion"),

        # Edge 50 Fusion, Edge 60 Fusion
        (r"\bedge\s*(\d{2})\s*fusion\b",
         "edge {1} fusion"),

        # Edge models with suffix
        (r"\bedge\s*(\d{2})\s*(ultra|pro|neo|fusion|plus)\b",
         "edge {1} {2}"),

        # Edge models without suffix
        (r"\bedge\s*(\d{2})\b",
         "edge {1}"),

        # Edge 2023+
        (r"\bedge\s*(2023)\s*\+",
         "edge {1} plus"),

        (r"\bedge\s*(\d{4})\b",
         "edge {1}"),

        # -------------------------
        # Motorola Razr
        # -------------------------
        (r"\brazr\s*(\d{2})\s*(ultra|plus)?\b",
         "razr {1} {2}"),

        # -------------------------
        # Motorola Stylus
        # -------------------------
        (r"\bstylus\s*5g\b",
         "stylus 5g"),

        (r"\bstylus\s*(\d{1,2})\s*(5g)?\b",
         "stylus {1} {2}"),

        # -------------------------
        # Motorola Moto G
        # -------------------------

        # Moto G5 Plus, Moto G85, Moto G56, etc.
        (r"\bmoto\s*g\s*(\d{1,3})\s*(plus|power|play|pro)?\b",
         "moto g{1} {2}"),

        # G04, G24, G85, etc. without Moto
        (r"\bg\s*(\d{2,3})\s*(plus|power|play|pro)?\b",
         "g{1} {2}"),

        # -------------------------
        # Motorola Signature
        # -------------------------
        (r"\bsignature\b",
         "signature"),
    ],
}

In [100]:
evaluate_brand("motorola")

Brand: motorola
Total ads: 31
Models extracted: 26
Unknown models: 5
Extraction coverage: 83.87%

In [101]:
stage1_df.loc[
    stage1_df["motorola_model"].eq("unknown"),
    ["title", "title_normalized", "motorola_model"]
].head(69)

                      title       title_normalized motorola_model
2586   Motorola Other Model   motorola other model        unknown
4303   Motorola Other Model   motorola other model        unknown
7139  Motorola 60 age fugen  motorola 60 age fugen        unknown
7480       موتورولا موتو جي       موتورولا موتو جي        unknown
7818     موتورولا موديل اخر     موتورولا موديل اخر        unknown

# oneplus

In [102]:
explore_brand("oneplus")

Total oneplus ads: 24

,title,title_punct_normalized
2206,وان بلس ايس 6,وان بلس ايس 6
873,وان بلس 5,وان بلس 5
2833,Oneplus Ace 5 256g 12g ram زيروووو,oneplus ace 5 256g 12g ram زيروووو
1115,OnePlus 12r علبه انجليزي بحالته وجميع مشتملاته,oneplus 12r علبه انجليزي بحالته وجميع مشتملاته
3429,OnePlus Ace 6T 12/256,oneplus ace 6t 12/256
3523,OnePlus 15 استخدام ايام فقط,oneplus 15 استخدام ايام فقط
7304,OnePlus Nord ce4,oneplus nord ce4
3904,Oneplus 7tpro mclaren edition,oneplus 7tpro mclaren edition
4703,OnePlus 15,oneplus 15
1145,ون بلس نورد ٤ مساحة ٥١٢ جيجا,ون بلس نورد 4 مساحة 512 جيجا
7731,One Plus Nord 4,one plus nord 4
2413,OnePlus 11وان بلس ١١ حالة ممتازة,oneplus 11وان بلس 11 حالة ممتازة
6304,وان بلس 15,وان بلس 15
3221,Oneplus 10 pro,oneplus 10 pro
6683,one plus nord ce4 ون بلس نورد ce4,one plus nord ce4 ون بلس نورد ce4
7797,oneplus 13t,oneplus 13t
2929,تليفون رائد بمعالج سناب دراجون الجيل الثامن On...,تليفون رائد بمعالج سناب دراجون الجيل الثامن on...
6358,وان بلس 12 ار one +12r,وان بلس 12 ار one +12r
5039,OnePlus Open fold,oneplus open fold
5220,وان بلس 15,وان بلس 15

In [103]:
BRAND_CONFIG["oneplus"] = {
    "letters": {},

    "aliases": {
        # Brand names in Arabic
        "وان بلس": "oneplus",
        "ون بلس": "oneplus",
        "وانبلس": "oneplus",
        "ونبلس": "oneplus",

        # Series names
        "ايس": "ace",
        "آيس": "ace",
        "نورد": "nord",
        "نورد سي": "nord ce",
        "ار": "r",
        "تي": "t",

        # Suffixes
        "برو": "pro",
        "بلس": "plus",
        "الترا": "ultra",
        "اوبن": "open",
        "ماكلارين": "mclaren",
    },

    "pre": [
        # Normalize brand spelling
        (r"\bone\s+plus\b", "oneplus"),
        (r"\boneplus(?=[a-z0-9])", "oneplus "),

        # Normalize series names
        (r"\bace\s*(?=\d)", "ace "),
        (r"\bnord\s+ce\s*(?=\d)", "nord ce "),
        (r"\bnord\s*(?=\d)", "nord "),

        # Separate suffixes attached to digits
        (r"(?<=\d)(pro|plus|ultra)\b", r" \1"),

        # Normalize numbered suffixes
        (r"\b(\d{1,2})\s*t\s*pro\s*mclaren\b",
         r"\1t pro mclaren"),

        (r"\b(\d{1,2})\s*t\s*pro\b",
         r"\1t pro"),

        (r"\b(\d{1,2})\s*r\b",
         r"\1r"),
    ],

    "rules": [
        # -------------------------
        # OnePlus Ace
        # -------------------------
        (r"\bace\s*(\d{1,2})\s*t\b",
         "ace {1}t"),

        (r"\bace\s*(\d{1,2})\s*(pro|plus|ultra)\b",
         "ace {1} {2}"),

        (r"\bace\s*(\d{1,2})\b",
         "ace {1}"),

        # -------------------------
        # OnePlus Nord CE
        # -------------------------
        (r"\bnord\s*ce\s*(\d{1,2})\s*(lite)?\b",
         "nord ce{1} {2}"),

        # -------------------------
        # OnePlus Nord
        # -------------------------
        (r"\bnord\s*(\d{1,2})\s*(pro|plus)?\b",
         "nord {1} {2}"),

        # -------------------------
        # OnePlus Open
        # -------------------------
        (r"\bopen(?:\s+fold)?\b",
         "open"),

        # -------------------------
        # OnePlus numbered models
        # -------------------------

        # 7T Pro McLaren Edition
        (r"\b(\d{1,2})\s*t\s*pro\s*mclaren\b",
         "{1}t pro mclaren"),

        # 13s, 13t, 12r
        (r"\b(\d{1,2})\s*(s|t|r)\b",
         "{1}{2}"),

        # Numbered Pro models
        (r"\b(\d{1,2})\s*pro\b",
         "{1} pro"),

        # Numbered Plus / Ultra models
        (r"\b(\d{1,2})\s*(plus|ultra)\b",
         "{1} {2}"),

        # Numbered models without suffix
        (r"\b(\d{1,2})\b",
         "{1}"),
    ],
}

In [104]:
evaluate_brand("oneplus")

Brand: oneplus
Total ads: 24
Models extracted: 24
Unknown models: 0
Extraction coverage: 100.00%

# zte

In [105]:
explore_brand("zte")

Total zte ads: 18

,title,title_punct_normalized
749,زد تى إي نيو 2,زد تي اي نيو 2
2065,Nubia v60,nubia v60
7376,ZTE Other Model,zte other model
1201,موبايل Nubia A76 5G جديد للبيع,موبايل nubia a76 5g جديد للبيع
1456,زد تى إي نوبيا زد 30 برو,زد تي اي نوبيا زد 30 برو
301,زد تى إي نوبيا زد 30 برو,زد تي اي نوبيا زد 30 برو
3343,تليفون نوبيا كسر زيرو بيع بسعر حرق,تليفون نوبيا كسر زيرو بيع بسعر حرق
5560,نوبيا A36,نوبيا a36
2445,موبايل نوبيا A36,موبايل نوبيا a36
6472,زد تى إي ريد ماجيك 10 برو,زد تي اي ريد ماجيك 10 برو
6721,زد تى إي موديل اخر,زد تي اي موديل اخر
7918,زد تى إي ريد ماجيك 10 اير,زد تي اي ريد ماجيك 10 اير
5515,للبيع موبايل/ هاتف ZTE Blade A76 5G بالضم...,للبيع موبايل/ هاتف zte blade a76 5g بالضمان با...
260,نوبيا a36,نوبيا a36
69,ZTE Red Magic 7 Black,zte red magic 7 black
7373,nubia neo 5g,nubia neo 5g
786,زد تى إي نوبيا زد 30 برو,زد تي اي نوبيا زد 30 برو
2488,تلفون نوبياA36,تلفون نوبياa36

In [106]:
BRAND_CONFIG["zte"] = {
    "letters": {},

    "aliases": {
        # Brand
        "زد تي اي": "zte",
        "زد تى اي": "zte",
        "زد تي إي": "zte",
        "زد تى إي": "zte",
        "زدتي اي": "zte",
        "زدتي": "zte",

        # Nubia
        "نوبيا": "nubia",
        "نوبيا زد": "nubia z",

        # RedMagic
        "ريد ماجيك": "red magic",
        "ريدماجيك": "red magic",

        # Neo
        "نيو": "neo",

        # Other
        "برو": "pro",
        "اير": "air",
        "إير": "air",
        "الترا": "ultra",
        "بلس": "plus",
    },

    "pre": [
        # Brand normalization
        (r"\bzte(?=[a-z0-9])", "zte "),

        # Normalize Nubia and RedMagic
        (r"\bred\s*magic\s*(?=\d)", "red magic "),
        (r"\bnubia\s*z\s*(?=\d)", "nubia z "),
        (r"\bnubia\s*a\s*(?=\d)", "nubia a "),
        (r"\bnubia\s*v\s*(?=\d)", "nubia v "),
        (r"\bnubia\s*neo\s*(?=\d)", "nubia neo "),

        # Blade series
        (r"\bblade\s*a\s*(?=\d)", "blade a "),

        # Normalize Neo series
        (r"\bneo\s*(?=\d)", "neo "),

        # Fix attached model names
        (r"\bnubia(?=[a-z]\d)", "nubia "),
    ],

    "rules": [
        # -------------------------
        # RedMagic
        # -------------------------
        (r"\bred\s*magic\s*(\d{1,2})\s*(pro|max|ultra|air)?\b",
         "red magic {1} {2}"),

        # -------------------------
        # Nubia Neo
        # -------------------------
        (r"\bnubia\s*neo\s*(\d{1,2})\s*(5g|pro|plus)?\b",
         "nubia neo {1} {2}"),

        # -------------------------
        # Nubia Z series
        # -------------------------
        (r"\bnubia\s*z\s*(\d{1,2})\s*(pro|ultra|plus)?\b",
         "nubia z{1} {2}"),

        # -------------------------
        # Nubia A series
        # -------------------------
        (r"\bnubia\s*a\s*(\d{1,3})\s*(5g)?\b",
         "nubia a{1} {2}"),

        # -------------------------
        # Nubia V series
        # -------------------------
        (r"\bnubia\s*v\s*(\d{1,3})\s*(5g)?\b",
         "nubia v{1} {2}"),

        # -------------------------
        # ZTE Blade
        # -------------------------
        (r"\bblade\s*a\s*(\d{1,3})\s*(5g)?\b",
         "blade a{1} {2}"),

        # -------------------------
        # ZTE Neo
        # -------------------------
        (r"\bneo\s*(\d{1,2})\b",
         "nubia neo {1}"),

        # -------------------------
        # Unknown / Other Model
        # -------------------------
        (r"\bother\s+model\b",
         "unknown"),
    ],
}

In [107]:
evaluate_brand("zte")

Brand: zte
Total ads: 18
Models extracted: 15
Unknown models: 3
Extraction coverage: 83.33%

In [108]:
stage1_df.loc[
    stage1_df["zte_model"].eq("unknown"),
    ["title", "title_normalized", "zte_model"]
].head(69)

,title,title_normalized,zte_model
3343,تليفون نوبيا كسر زيرو بيع بسعر حرق,تليفون نوبيا كسر زيرو بيع بسعر حرق,unknown
6721,زد تى إي موديل اخر,زد تي اي موديل اخر,unknown
7373,nubia neo 5g,nubia neo 5g,unknown

# tecno

In [109]:
explore_brand("tecno")

Total tecno ads: 17

,title,title_punct_normalized
2451,Tecno Pova 7,tecno pova 7
1536,تكنو سبارك 40 برو جديد,تكنو سبارك 40 برو جديد
7477,Tecno Spark,tecno spark
3732,Tecno Spark 20 Pro +,tecno spark 20 pro +
3527,تكنو كامون 40,تكنو كامون 40
4131,تكنو بوفا 6 برو للتبديل بايفون 12 برو,تكنو بوفا 6 برو للتبديل بايفون 12 برو
5460,Tecno Camon 40 Pro 5G,tecno camon 40 pro 5g
524,تكنو سبارك جو ٣ جديد ما اشتغلش لسه جديد شراء ا...,تكنو سبارك جو 3 جديد ما اشتغلش لسه جديد شراء ا...
6886,تليفون جديد تكنو سبارك 30C مساحه 256 رام معاه ...,تليفون جديد تكنو سبارك 30c مساحه 256 رام معاه ...
7710,Tecno Spark 20 Pro + السعر نهائي,tecno spark 20 pro + السعر نهائي
8163,تكنو سبارك ٣٠,تكنو سبارك 30
5760,تكنو سبارك سي إم كسر زيرو مفيش خربوش256/16,تكنو سبارك سي ام كسر زيرو مفيش خربوش256/16
515,تكنو سبارك 40برو,تكنو سبارك 40برو
236,تكنو سبارك,تكنو سبارك
2351,Tecno Camon CM,tecno camon cm
7325,تكنو كامون 30 للبيع داخل محافظة المنيا,تكنو كامون 30 للبيع داخل محافظة المنيا
4774,Tecno Pop 7,tecno pop 7

In [110]:
BRAND_CONFIG["tecno"] = {
    "letters": {},

    "aliases": {
        "تكنو": "tecno",

        "سبارك": "spark",
        "سبارك جو": "spark go",
        "سبارك سي ام": "spark cm",
        "سبارك سي إم": "spark cm",

        "كامون": "camon",
        "كامون سي ام": "camon cm",
        "كامون سي إم": "camon cm",

        "بوفا": "pova",
        "بوب": "pop",

        "برو": "pro",
        "بلس": "plus",
        "جو": "go",
    },

    "pre": [
        (r"\btecno(?=[a-z0-9])", "tecno "),

        (r"\bspark\s*go\s*(?=\d)", "spark go "),
        (r"\bspark\s*cm\b", "spark cm"),
        (r"\bspark\s*(?=\d)", "spark "),
        (r"\bcamon\s*cm\b", "camon cm"),
        (r"\bcamon\s*(?=\d)", "camon "),
        (r"\bpova\s*(?=\d)", "pova "),
        (r"\bpop\s*(?=\d)", "pop "),

        (r"(?<=\d)(pro|plus)\b", r" \1"),
    ],

    "rules": [
        # Tecno Spark Go 3
        (
            r"\bspark\s*go\s*(\d{1,2})\b",
            "spark go {1}"
        ),

        # Tecno Spark 20 Pro+
        (
            r"\bspark\s*(\d{1,3})\s*pro\s*plus\b",
            "spark {1} pro plus"
        ),

        # Tecno Spark 20 Pro
        (
            r"\bspark\s*(\d{1,3})\s*pro\b",
            "spark {1} pro"
        ),

        # Tecno Spark CM
        (
            r"\bspark\s*cm\b",
            "spark cm"
        ),

        # Tecno Spark 30C
        (
            r"\bspark\s*(\d{1,3})\s*c\b",
            "spark {1}c"
        ),

        # Tecno Spark 30 / Spark 40
        (
            r"\bspark\s*(\d{1,3})\b",
            "spark {1}"
        ),

        # Tecno Camon CM
        (
            r"\bcamon\s*cm\b",
            "camon cm"
        ),

        # Tecno Camon 40 Pro 5G
        (
            r"\bcamon\s*(\d{1,3})\s*pro\s*5g\b",
            "camon {1} pro 5g"
        ),

        # Tecno Camon 40 Pro
        (
            r"\bcamon\s*(\d{1,3})\s*pro\b",
            "camon {1} pro"
        ),

        # Tecno Camon 40
        (
            r"\bcamon\s*(\d{1,3})\b",
            "camon {1}"
        ),

        # Tecno Pova 6 Pro / Pova 7
        (
            r"\bpova\s*(\d{1,3})\s*(pro|plus|ultra)?\b",
            "pova {1} {2}"
        ),

        # Tecno Pop 7
        (
            r"\bpop\s*(\d{1,3})\b",
            "pop {1}"
        ),
    ],
}

In [111]:
evaluate_brand("tecno")

Brand: tecno
Total ads: 17
Models extracted: 15
Unknown models: 2
Extraction coverage: 88.24%

# itel

In [112]:
explore_brand("itel")

Total itel ads: 15

                        title   title_punct_normalized
2232         ايتل اس 25 الترا         ايتل اس 25 الترا
4545           ايتل ايه 50 سى           ايتل ايه 50 سي
6321              ايتل ايه 80              ايتل ايه 80
2794           ايتل ايه 50 سى           ايتل ايه 50 سي
5200                 itel A90                 itel a90
1816           ايتل موديل اخر           ايتل موديل اخر
5776           ايتل موديل اخر           ايتل موديل اخر
2680             ايتل ار اس 4             ايتل ار اس 4
6061              ايتل ايه 80              ايتل ايه 80
7440                 ايتل a90                 ايتل a90
1713  Itel A90 (ايتيل ايه ٩٠)  itel a90 (ايتيل ايه 90)
398      ايتل موديل itel a 90     ايتل موديل itel a 90
2303                 ايتل A90                 ايتل a90
6959               ايتل اس 24               ايتل اس 24
5213              ايتل  A100c               ايتل a100c

In [113]:

BRAND_CONFIG["itel"] = {
    "letters": {},
    "aliases": {
        "ايتل": "itel",
        "ايتيل": "itel",

        "اس": "s",
        "إس": "s",

        "ايه": "a",
        "إيه": "a",

        "ار": "r",
        "آر": "r",

        "اس 4": "s4",
        "اس 24": "s24",
        "اس 25": "s25",

        "الترا": "ultra",
        "سي": "c",
        "سى": "c",
    },

    "pre": [
        (r"\bitel(?=[a-z0-9])", "itel "),
        (r"\b([as])\s*(\d{1,3})\s*c\b", r"\1 \2c"),
        (r"\ba\s*(?=\d)", "a "),
        (r"\bs\s*(?=\d)", "s "),
        (r"\brs\s*(?=\d)", "rs "),
        (r"\br\s+s\s*(?=\d)", "rs "),
        (r"\b(\d{1,3})\s*c\b", r"\1c"),
    ],

    "rules": [
        # itel S25 Ultra
        (
            r"\bs\s*(\d{1,3})\s*ultra\b",
            "s{1} ultra"
        ),

        # itel S24 / S25
        (
            r"\bs\s*(\d{1,3})\b",
            "s{1}"
        ),

        # itel A50C
        (
            r"\ba\s*(\d{1,3})\s*c\b",
            "a{1}c"
        ),

        # itel A90 / A80 / A100C
        (
            r"\ba\s*(\d{1,3})\s*c\b",
            "a{1}c"
        ),
        (
            r"\ba\s*(\d{1,3})\b",
            "a{1}"
        ),

        # itel RS4
        (
            r"\brs\s*(\d{1,3})\b",
            "rs {1}"
        ),
    ],
}

In [114]:
evaluate_brand("itel")

Brand: itel
Total ads: 15
Models extracted: 13
Unknown models: 2
Extraction coverage: 86.67%

In [115]:
explore_brand("google")

Total google ads: 14

,title,title_punct_normalized
3515,جوجل بكسل 8 ايه,جوجل بكسل 8 ايه
4378,للبيع موبايل جوجل بكسل 6 برو,للبيع موبايل جوجل بكسل 6 برو
7131,Pixel 11 Pro Fold,pixel 11 pro fold
4224,جوجل بكسل 6 ايه,جوجل بكسل 6 ايه
4551,Google Pixel 7,google pixel 7
2480,Google Pixel 6 Pro,google pixel 6 pro
4804,Google Pixel 10 5G 128G Hazel جديد متبرشم,google pixel 10 5g 128g hazel جديد متبرشم
4189,جوجل بكسل 6 برو,جوجل بكسل 6 برو
5811,تليفون google pixel 7 pro بالعلبه وكامل المشتملات,تليفون google pixel 7 pro بالعلبه وكامل المشتملات
8099,Google pixel 9a مدفوع الضريبة,google pixel 9a مدفوع الضريبة
918,Google Pixel 6 pro 12-128,google pixel 6 pro 12 128
28,Google Pixel 11 Pro Fold 16g 256g Black New,google pixel 11 pro fold 16g 256g black new
3983,google pixel 9a//128+8//مدفوع الضريبة,google pixel 9a//128+8//مدفوع الضريبة
4779,Google Pixel 9 Pro,google pixel 9 pro

In [116]:

BRAND_CONFIG["google"] = {
    "letters": {},
    "aliases": {
        "جوجل": "google",
        "بكسل": "pixel",
        "برو": "pro",
        "فولد": "fold",
        "ايه": "a",
        "إيه": "a",
    },

    "pre": [
        (r"\bgoogle(?=[a-z0-9])", "google "),
        (r"\bpixel\s*(?=\d)", "pixel "),
        (r"\b(\d{1,2})\s*pro\s*fold\b", r"\1 pro fold"),
        (r"\b(\d{1,2})\s*pro\b", r"\1 pro"),
        (r"\b(\d{1,2})\s*5g\b", r"\1 5g"),
    ],

    "rules": [
        # Pixel 11 Pro Fold
        (
            r"\bpixel\s*(\d{1,2})\s*pro\s*fold\b",
            "{1} pro fold"
        ),

        # Pixel 6 Pro / Pixel 9 Pro
        (
            r"\bpixel\s*(\d{1,2})\s*pro\b",
            "{1} pro"
        ),

        # Pixel 8a / Pixel 9a
        (
            r"\bpixel\s*(\d{1,2})\s*a\b",
            "{1}a"
        ),

        # Pixel 10 5G
        (
            r"\bpixel\s*(\d{1,2})\s*5g\b",
            "{1} 5g"
        ),

        # Pixel 6 / Pixel 7 / Pixel 10 / Pixel 11
        (
            r"\bpixel\s*(\d{1,2})\b",
            "{1}"
        ),
    ],
}

In [117]:
evaluate_brand("google")

Brand: google
Total ads: 14
Models extracted: 14
Unknown models: 0
Extraction coverage: 100.00%

# sony
11
nokia
9
lenovo
8
lg

In [118]:
explore_brand("sony")

Total sony ads: 11

,title,title_punct_normalized
1136,Sony Xperia 1 mark 2. كسر زيرو بالعلبة كاملة,sony xperia 1 mark 2. كسر زيرو بالعلبة كاملة
2257,سوني اكسبريا 4مارك 5,سوني اكسبريا 4مارك 5
5741,سوني اريكسون K610i,سوني اريكسون k610i
2016,Sony Xperia PRO-I موبايل سوني إكسبيريا برو,sony xperia pro i موبايل سوني اكسبيريا برو
4884,Sony xperia 1 mark 7 سوني إكسبريا ١ مارك ٧,sony xperia 1 mark 7 سوني اكسبريا 1 مارك 7
6473,Sony Ericsson,sony ericsson
1353,Sony Other Model,sony other model
851,sony Xperia 5iv,sony xperia 5iv
390,شاشه touchscreen panel sony xperia Z Ultra للبيع,شاشه touchscreen panel sony xperia z ultra للبيع
1466,سوني زد 2,سوني زد 2
5954,Sony Xperia 1 V,sony xperia 1 v

In [119]:

BRAND_CONFIG["sony"] = {
    "letters": {},
    "aliases": {
        "سوني": "sony",
        "اكسبريا": "xperia",
        "إكسبريا": "xperia",
        "اريكسون": "ericsson",
        "إريكسون": "ericsson",
        "مارك": "mark",
        "برو": "pro",
        "الترا": "ultra",
        "زد": "z",
    },

    "pre": [
        (r"\bsony(?=[a-z0-9])", "sony "),
        (r"\bxperia(?=[a-z0-9])", "xperia "),
        (r"\b(\d)\s*mark\s*(\d)\b", r"\1 mark \2"),
        (r"\b(\d{1,2})\s*(iv|v|vi|iii|ii)\b", r"\1 \2"),
        (r"\bpro\s*[- ]?\s*i\b", "pro i"),
        (r"\bz\s*ultra\b", "z ultra"),
    ],

    "rules": [
        # Sony Xperia 1 Pro-I
        (
            r"\bxperia\s+pro\s+i\b",
            "xperia pro-i"
        ),

        # Sony Xperia 1 Mark 2 / Mark 7
        (
            r"\bxperia\s+(\d)\s*mark\s*(\d)\b",
            "xperia {1} mark {2}"
        ),

        # Sony Xperia 1 V / 5 IV
        (
            r"\bxperia\s+(\d{1,2})\s*(iv|v|vi|iii|ii)\b",
            "xperia {1} {2}"
        ),

        # Sony Xperia Z Ultra
        (
            r"\bxperia\s+z\s+ultra\b",
            "xperia z ultra"
        ),

        # Sony Xperia 1 / 5
        (
            r"\bxperia\s+(\d{1,2})\b",
            "xperia {1}"
        ),

        # Sony Ericsson K610i
        (
            r"\b([a-z]{1,3}\d{2,4}i?)\b",
            "{1}"
        ),
    ],
}

In [120]:
evaluate_brand("sony")

Brand: sony
Total ads: 11
Models extracted: 8
Unknown models: 3
Extraction coverage: 72.73%

# nokia

In [121]:
explore_brand("nokia")

Total nokia ads: 9

,title,title_punct_normalized
6224,نوكيا موديل اخر,نوكيا موديل اخر
1976,Nokia G300 5G وارد أمريكا بلمعته كالجديد شاشه...,nokia g300 5g وارد امريكا بلمعته كالجديد شاشه ...
3818,هاتف hmd نوكيا,هاتف hmd نوكيا
3981,NOKIA X350 for sale,nokia x350 for sale
2916,Nokia Other Model,nokia other model
271,نوكيا 7.1 للبيع,نوكيا 7.1 للبيع
187,Nokia C21 Plus,nokia c21 plus
4489,Nokia N9,nokia n9
3417,نوكيا اكس 2,نوكيا اكس 2

In [122]:

BRAND_CONFIG["nokia"] = {
    "letters": {},
    "aliases": {
        "نوكيا": "nokia",
        "اكس": "x",
        "إكس": "x",
        "بلس": "plus",
        "برو": "pro",
        "الترا": "ultra",
    },

    "pre": [
        (r"\bnokia(?=[a-z0-9])", "nokia "),

        (r"\b([gc])\s*(?=\d)", r"\1 "),
        (r"\bx\s*(?=\d)", "x "),
        (r"\bn\s*(?=\d)", "n "),

        (r"\b(\d+)\s*\.\s*(\d+)\b", r"\1.\2"),

        (r"(?<=\d)(plus|pro|ultra)\b", r" \1"),
    ],

    "rules": [
        # Nokia G300 5G
        (
            r"\bg\s*(\d{1,3})\s*5g\b",
            "g{1} 5g"
        ),
        (
            r"\bg\s*(\d{1,3})\b",
            "g{1}"
        ),

        # Nokia C21 Plus / C-series
        (
            r"\bc\s*(\d{1,3})\s*plus\b",
            "c{1} plus"
        ),
        (
            r"\bc\s*(\d{1,3})\s*pro\b",
            "c{1} pro"
        ),
        (
            r"\bc\s*(\d{1,3})\b",
            "c{1}"
        ),

        # Nokia X350 / X2
        (
            r"\bx\s*(\d{1,4})\b",
            "x{1}"
        ),

        # Nokia N9
        (
            r"\bn\s*(\d{1,3})\b",
            "n{1}"
        ),

        # Nokia 7.1
        (
            r"\b(\d{1,2})\.(\d)\b",
            "{1}.{2}"
        ),
    ],
}

In [123]:
evaluate_brand("nokia")

Brand: nokia
Total ads: 9
Models extracted: 6
Unknown models: 3
Extraction coverage: 66.67%

# lenovo

In [124]:
explore_brand("lenovo")

Total lenovo ads: 8

,title,title_punct_normalized
2944,لينوفو كيه 14 بلس وارد الخارج ٦٤جيجا+٤جيجا را...,لينوفو كيه 14 بلس وارد الخارج 64جيجا+4جيجا رام...
3102,لينوفو كيه 12 نوت,لينوفو كيه 12 نوت
7164,موبايل لينوفو Lenovo K8 NOTE,موبايل لينوفو lenovo k8 note
7359,Lenovo Other Model,lenovo other model
2526,Lenovo Legion Y70 2026 mobile phone,lenovo legion y70 2026 mobile phone
5490,لينوفو نوت6 بالعلبه 32ج 3 رام ماتفتحش خدش فى ا...,لينوفو نوت6 بالعلبه 32ج 3 رام ماتفتحش خدش في ا...
5901,lenovo k15 plus(لسه موجود),lenovo k15 plus(لسه موجود)
2650,Lenovo A8,lenovo a8

In [125]:

BRAND_CONFIG["lenovo"] = {
    "letters": {},
    "aliases": {
        "لينوفو": "lenovo",
        "كيه": "k",
        "نوت": "note",
        "نوتة": "note",
        "ليجن": "legion",
        "ليجيون": "legion",
        "بلس": "plus",
        "برو": "pro",
    },

    "pre": [
        (r"\blenovo(?=[a-z0-9])", "lenovo "),
        (r"\blegion\s*y\s*(?=\d)", "legion y "),
        (r"\bk\s*(?=\d)", "k "),
        (r"\ba\s*(?=\d)", "a "),
        (r"\b(note)\s*(?=\d)", "note "),
        (r"\b(\d{1,3})\s*note\b", r"\1 note"),
    ],

    "rules": [
        # Lenovo Legion Y70
        (
            r"\blegion\s*y\s*(\d{1,3})\b",
            "legion y{1}"
        ),

        # Lenovo K14 Plus
        (
            r"\bk\s*(\d{1,3})\s*plus\b",
            "k{1} plus"
        ),

        # Lenovo K12 Note / K8 Note
        (
            r"\bk\s*(\d{1,3})\s*note\b",
            "k{1} note"
        ),

        # Lenovo K15
        (
            r"\bk\s*(\d{1,3})\b",
            "k{1}"
        ),

        # Lenovo A8
        (
            r"\ba\s*(\d{1,3})\b",
            "a{1}"
        ),

        # Lenovo Note 6
        (
            r"\bnote\s*(\d{1,3})\b",
            "note {1}"
        ),
    ],
}

In [126]:
evaluate_brand("lenovo")

Brand: lenovo
Total ads: 8
Models extracted: 7
Unknown models: 1
Extraction coverage: 87.50%

In [127]:
explore_brand("lg")

Total lg ads: 3

                      title title_punct_normalized
954   lg g6 خطين محتاج تاتش  lg g6 خطين محتاج تاتش
7951        lg g6 جديد خطين        lg g6 جديد خطين
6873              موبايل Lg              موبايل lg

In [128]:

BRAND_CONFIG["lg"] = {
    "letters": {},
    "aliases": {
        "ال جي": "lg",
        "إل جي": "lg",
        "ال جى": "lg",
        "إل جى": "lg",

        "فيلفيت": "velvet",
        "وينج": "wing",
        "وينغ": "wing",
        "ستايلو": "stylo",
        "ثينك كيو": "thinq",
        "ثينكيو": "thinq",
    },

    "pre": [
        (r"\blg(?=[a-z0-9])", "lg "),

        (r"\b(g|v|k|q|w|x)\s*(?=\d)", r"\1 "),
        (r"\bstylo\s*(?=\d)", "stylo "),
        (r"\bvelvet(?=\d)", "velvet "),
        (r"\bwing(?=\d)", "wing "),

        (r"\bthin\s*q\b", "thinq"),
        (r"\bthinq\b", "thinq"),

        (r"\b(v\d{1,2})\s*thinq\b", r"\1 thinq"),
    ],

    "rules": [
        # LG Velvet
        (r"\bvelvet\s*(\d{1,2})?\b", "velvet {1}"),

        # LG Wing
        (r"\bwing\s*(\d{1,2})?\b", "wing {1}"),

        # LG Stylo 6 / Stylo 7
        (r"\bstylo\s*(\d{1,2})\b", "stylo {1}"),

        # LG V60 ThinQ / V50 ThinQ
        (r"\bv\s*(\d{1,2})\s*thinq\b", "v{1} thinq"),

        # LG G-series
        (r"\bg\s*(\d{1,2})\b", "g{1}"),

        # LG V-series
        (r"\bv\s*(\d{1,2})\b", "v{1}"),

        # LG K-series
        (r"\bk\s*(\d{1,3})\b", "k{1}"),

        # LG Q-series
        (r"\bq\s*(\d{1,3})\b", "q{1}"),

        # LG W-series
        (r"\bw\s*(\d{1,3})\b", "w{1}"),

        # LG X-series
        (r"\bx\s*(\d{1,3})\b", "x{1}"),
    ],
}

In [129]:
evaluate_brand("lg")

Brand: lg
Total ads: 3
Models extracted: 2
Unknown models: 1
Extraction coverage: 66.67%

In [130]:
print("Columns names:\n", stage1_df.columns.to_list())

Columns names:
 ['title', 'price', 'location', 'ad_url', 'ad_id', 'run_id', 'brand', 'storage_gb', 'ram_gb', 'storage_src', 'condition', 'condition_src', 'ram_src', 'has_5g', 'has_warranty', 'has_box', 'mentions_exchange', 'is_wanted_ad', 'is_accessory_hint', 'is_tablet_hint', 'is_parts_hint', 'accessory_first', 'bundle_hint', 'is_feature_phone_hint', 'price_placeholder', 'loc_area', 'loc_city', 'price_missing', 'price_suspicious', 'price_very_high', 'title_normalized', 'title_punct_normalized', 'title_group', 'iphone_model', 'samsung_model', 'is_phone_listing', 'xiaomi_model', 'oppo_model', 'honor_model', 'realme_model', 'infinix_model', 'vivo_model', 'huawei_model', 'motorola_model', 'oneplus_model', 'zte_model', 'tecno_model', 'itel_model', 'google_model', 'sony_model', 'nokia_model', 'lenovo_model', 'lg_model']