Imports

In [315]:
import pandas as pd
import re

Load Data

In [316]:
file_path = r"C:\Users\viola\OneDrive\VIOLA\CS\Courses\AI\AI DEPI 2026\Graduation Project\The Project\data\raw\dubizzle_phones_clean.csv"
df = pd.read_csv(file_path)

Dataset Shape

In [317]:
print("Dataset shape:", df.shape)

Dataset shape: (8213, 30)

Dataset Columns

In [318]:
print("Columns names:\n", df.columns.to_list())

Columns names:
 ['title', 'price', 'location', 'ad_url', 'ad_id', 'run_id', 'brand', 'storage_gb', 'ram_gb', 'storage_src', 'condition', 'condition_src', 'ram_src', 'has_5g', 'has_warranty', 'has_box', 'mentions_exchange', 'is_wanted_ad', 'is_accessory_hint', 'is_tablet_hint', 'is_parts_hint', 'accessory_first', 'bundle_hint', 'is_feature_phone_hint', 'price_placeholder', 'loc_area', 'loc_city', 'price_missing', 'price_suspicious', 'price_very_high']

In [319]:
print("Number of columns:", len(df.columns))

Number of columns: 30

In [320]:
df.head()

,title,price,location,ad_url,ad_id,run_id,brand,storage_gb,ram_gb,storage_src,...,is_parts_hint,accessory_first,bundle_hint,is_feature_phone_hint,price_placeholder,loc_area,loc_city,price_missing,price_suspicious,price_very_high
0,ايفون 13 iPhone,19500.0,مساكن المهندسين، مدينة نصر,/ad/%D8%A7%D9%8A%D9%81%D9%88%D9%86-13-iphone-I...,208854767,legacy,apple,NaN,NaN,NaN,...,False,False,False,False,False,مساكن المهندسين,مدينة نصر,False,False,False
1,Honor Magic V5,80000.0,اوبن اير مول، مدينتي,/ad/honor-magic-v5-ID209010621.html,209010621,legacy,honor,NaN,NaN,NaN,...,False,False,False,False,False,اوبن اير مول,مدينتي,False,False,False
2,OPPO Find X9 Pro ضمان محلي للبيع او البدل,57999.0,سموحة، الإسكندرية,/ad/oppo-find-x9-pro-%D8%B6%D9%85%D8%A7%D9%86-...,209003975,legacy,oppo,NaN,NaN,NaN,...,False,False,False,False,False,سموحة,الإسكندرية,False,False,False
3,Honor Robot Phone 512G 12G ram,94000.0,مدينة نصر، القاهرة,/ad/honor-robot-phone-512g-12g-ram-ID208841945...,208841945,legacy,honor,512.0,12.0,L1:unit,...,False,False,False,False,False,مدينة نصر,القاهرة,False,False,False
4,شاومي 17 الترا xiaomi 17 ultra,70000.0,التجمع الخامس، القاهرة الجديدة,/ad/%D8%B4%D8%A7%D9%88%D9%85%D9%8A-17-%D8%A7%D...,208281312,legacy,xiaomi,NaN,NaN,NaN,...,False,False,False,False,False,التجمع الخامس,القاهرة الجديدة,False,False,False

In [321]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 8213 entries, 0 to 8212
Data columns (total 30 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   title                  8213 non-null   str
 1   price                  8213 non-null   float64
 2   location               8207 non-null   str
 3   ad_url                 8213 non-null   str
 4   ad_id                  8213 non-null   int64
 5   run_id                 8213 non-null   str
 6   brand                  7772 non-null   str
 7   storage_gb             586 non-null    float64
 8   ram_gb                 177 non-null    float64
 9   storage_src            586 non-null    str
 10  condition              439 non-null    str
 11  condition_src          439 non-null    str
 12  ram_src                177 non-null    str
 13  has_5g                 8213 non-null   bool
 14  has_warranty           8213 non-null   bool
 15  has_box                8213 non-null   bool
 16  mentions_exchange      8213 non-null   bool
 17  is_wanted_ad           8213 non-null   bool
 18  is_accessory_hint      8213 non-null   bool
 19  is_tablet_hint         8213 non-null   bool
 20  is_parts_hint          8213 non-null   bool
 21  accessory_first        8213 non-null   bool
 22  bundle_hint            8213 non-null   bool
 23  is_feature_phone_hint  8213 non-null   bool
 24  price_placeholder      8213 non-null   bool
 25  loc_area               8207 non-null   str
 26  loc_city               8207 non-null   str
 27  price_missing          8213 non-null   bool
 28  price_suspicious       8213 non-null   bool
 29  price_very_high        8213 non-null   bool
dtypes: bool(15), float64(3), int64(1), str(11)
memory usage: 1.1 MB

In [322]:
df.isna().sum().to_frame("Missing Values")

                       Missing Values
title                               0
price                               0
location                            6
ad_url                              0
ad_id                               0
run_id                              0
brand                             441
storage_gb                       7627
ram_gb                           8036
storage_src                      7627
condition                        7774
condition_src                    7774
ram_src                          8036
has_5g                              0
has_warranty                        0
has_box                             0
mentions_exchange                   0
is_wanted_ad                        0
is_accessory_hint                   0
is_tablet_hint                      0
is_parts_hint                       0
accessory_first                     0
bundle_hint                         0
is_feature_phone_hint               0
price_placeholder                   0
loc_area                            6
loc_city                            6
price_missing                       0
price_suspicious                    0
price_very_high                     0

Data Types and Missing Values

In [323]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 8213 entries, 0 to 8212
Data columns (total 30 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   title                  8213 non-null   str
 1   price                  8213 non-null   float64
 2   location               8207 non-null   str
 3   ad_url                 8213 non-null   str
 4   ad_id                  8213 non-null   int64
 5   run_id                 8213 non-null   str
 6   brand                  7772 non-null   str
 7   storage_gb             586 non-null    float64
 8   ram_gb                 177 non-null    float64
 9   storage_src            586 non-null    str
 10  condition              439 non-null    str
 11  condition_src          439 non-null    str
 12  ram_src                177 non-null    str
 13  has_5g                 8213 non-null   bool
 14  has_warranty           8213 non-null   bool
 15  has_box                8213 non-null   bool
 16  mentions_exchange      8213 non-null   bool
 17  is_wanted_ad           8213 non-null   bool
 18  is_accessory_hint      8213 non-null   bool
 19  is_tablet_hint         8213 non-null   bool
 20  is_parts_hint          8213 non-null   bool
 21  accessory_first        8213 non-null   bool
 22  bundle_hint            8213 non-null   bool
 23  is_feature_phone_hint  8213 non-null   bool
 24  price_placeholder      8213 non-null   bool
 25  loc_area               8207 non-null   str
 26  loc_city               8207 non-null   str
 27  price_missing          8213 non-null   bool
 28  price_suspicious       8213 non-null   bool
 29  price_very_high        8213 non-null   bool
dtypes: bool(15), float64(3), int64(1), str(11)
memory usage: 1.1 MB

In [324]:
df.isna().sum().to_frame("Number of Missing Values")

                       Number of Missing Values
title                                         0
price                                         0
location                                      6
ad_url                                        0
ad_id                                         0
run_id                                        0
brand                                       441
storage_gb                                 7627
ram_gb                                     8036
storage_src                                7627
condition                                  7774
condition_src                              7774
ram_src                                    8036
has_5g                                        0
has_warranty                                  0
has_box                                       0
mentions_exchange                             0
is_wanted_ad                                  0
is_accessory_hint                             0
is_tablet_hint                                0
is_parts_hint                                 0
accessory_first                               0
bundle_hint                                   0
is_feature_phone_hint                         0
price_placeholder                             0
loc_area                                      6
loc_city                                      6
price_missing                                 0
price_suspicious                              0
price_very_high                               0

Check Duplicate Titles

In [325]:
df["title"].duplicated().sum()

np.int64(4513)

Inspect Duplicate Titles

In [326]:
df.loc[df["title"].duplicated(keep = False) , "title"].head(20).to_frame()

                        title
0             ايفون 13 iPhone
1              Honor Magic V5
5       Apple - iPhone 17 Pro
9     آبل - آيفون 15 برو ماكس
14    آبل - آيفون 17 برو ماكس
15    آبل - آيفون 13 برو ماكس
17          Apple - iPhone 15
18          Samsung S25 Ultra
19        سامسونج اس 24 الترا
21  Apple - iPhone 17 Pro Max
22          Apple - iPhone 14
30          iPhone 16 pro max
35                   هونر 600
37        سامسونج اس 24 الترا
46             آبل - آيفون 13
48                   Vivo V60
50      Apple - iPhone 13 Pro
51  Apple - iPhone 11 Pro Max
55        سامسونج اس 25 الترا
57             آبل - آيفون 12

Inspect Title Examples

In [327]:
df["title"].head(30)

0                                       ايفون 13 iPhone
1                                        Honor Magic V5
2             OPPO Find X9 Pro ضمان محلي للبيع او البدل
3                        Honor Robot Phone 512G 12G ram
4                        شاومي 17 الترا xiaomi 17 ultra
5                                 Apple - iPhone 17 Pro
6     للبيع iPhone 15 Pro 1TB_ايفون 15 برو_زيرو بسعر...
7                                         Honor 500 pro
8     ايفون 11 بحاله الزيرو (iphone11) - سعر لقطه لل...
9                               آبل - آيفون 15 برو ماكس
10                                   Huawei nova 15 max
11    ايفون 16e جديد وارد الامارات مدفوع ضريبة | iPh...
12    Oppo Find X5 5G dual sim 256/8G Black بحالة مم...
13    Samsung S24 Ultra زيرو 256GB تيتانيوم مدفوع ال...
14                              آبل - آيفون 17 برو ماكس
15                              آبل - آيفون 13 برو ماكس
16    Honor Magic V5 dual sim 512/16G White Gold جدي...
17                                    Apple - iPhone 15
18                                    Samsung S25 Ultra
19                                  سامسونج اس 24 الترا
20    زد فولد ٨  للبيع مستعمل ساعتين فقط بحالة الجدي...
21                            Apple - iPhone 17 Pro Max
22                                    Apple - iPhone 14
23                                    oppo find x9s pro
24                                   Redmi k100 pro max
25                                      Galaxy Z Flip 8
26                     Apple - iPhone 17 Pro Max 512 GB
27                                         Honor win rt
28          Google Pixel 11 Pro Fold 16g 256g Black New
29                                Galaxy Z Fold 8 ultra
Name: title, dtype: str

Check Title Normalization Examples

In [328]:
df.loc[df["title"].str.contains("iPhone 17 Pro Max", case=False), "title"]

21                              Apple - iPhone 17 Pro Max
26                       Apple - iPhone 17 Pro Max 512 GB
39                Apple - iPhone 17 Pro Max - Battery 98%
42                 Apple - iPhone 17 Pro Max battery 100%
43      Apple iPhone 17 Pro Max (512GB) كسر زيرو | خال...
                              ...
8049                            Apple - iPhone 17 Pro Max
8057                            Apple - iPhone 17 Pro Max
8072    Apple - iPhone 17 Pro Max battery 98% still in...
8084                            Apple - iPhone 17 Pro Max
8122                            Apple - iPhone 17 Pro Max
Name: title, Length: 169, dtype: str

Check Title Variations

In [329]:
df.loc[df["title"].str.contains("iPhone 17 Pro Max", case=False),"title"].nunique()

46

Inspect Unique Title Variations

In [330]:
df.loc[df["title"].str.contains("iPhone 17 Pro Max", case=False),"title"].drop_duplicates().to_list()

['Apple - iPhone 17 Pro Max',
 'Apple - iPhone 17 Pro Max 512 GB',
 'Apple - iPhone 17 Pro Max - Battery 98%',
 'Apple - iPhone 17 Pro Max battery 100%',
 'Apple iPhone 17 Pro Max (512GB) كسر زيرو | خالص ضريبة',
 'iPhone 17 pro max',
 'Apple - iPhone 17 Pro Max First high copy',
 'Apple - iPhone 17 Pro Max -Used Like New',
 'آبل - آيفون 17 برو ماكس iphone 17 pro max',
 'Apple - iPhone 17 Pro max',
 'iPhone 17 Pro Max 512gb',
 'iPhone 17 Pro Max 256GB – Silver',
 'iPhone 17 pro max 256 سيلفر',
 'IPhone 17 Pro Max silver zero scratches',
 'آيفون 17 برو ماكس  سيلفر - Apple iPhone 17 Pro Max siliver',
 'آبل IPhone 17 Pro max',
 'Apple - iPhone 17 Pro Max خربوش بسيط جدا جدا ف الباغه',
 'Apple - iPhone 17 Pro Max tradeline جديد متبرشم معفي ضريبة',
 'IPhone 17 pro max',
 'Iphone 17 pro max blue new',
 'iPhone 17 Pro Max 256 شريحه نسخه محلي مسجل بالعلبه فقط',
 'iphone 17 pro max',
 'iPhone 17 Pro Max كسر زيرو بدون خربوش للبيع',
 'iPhone 17 Pro Max 256GB Deep Blue – 100% Battery',
 'Apple - iPhone 17 Pro Max battery 100% 113 cycle',
 'أنتا الكسبان  IPhone 17 Pro Max جديد متبرشم ضمان سنة بسعر مميز',
 'Apple - iPhone 17 Pro Max / اي فون 17 برو مكس',
 'موبيل ايفون 17 برو ماكس | Apple iPhone 17 Pro Max تليفون مميز جدا',
 'Apple - iPhone 17 Pro Max - ايفون ١٧ برو ماكس',
 'Apple - iPhone 17 pro max',
 'iPhone 17 Pro Max',
 'iPhone 17 Pro Max 512 - مدفوع الضريبة',
 'iPhone 17 pro max gray white',
 'Apple IPhone 17 pro max',
 'iPhone 17 Pro max - 1st High copy "American"',
 'Apple - iPhone 17 Pro Max sliver',
 'Apple - iPhone 17 Pro Max trade line',
 'Iphone 17 pro max 256GB 98%',
 'Iphone 17 Pro Max',
 'iPhone 17 Pro Max 256GB with Box– 96% Battery Health – معفي من الضريبة',
 'iphone 17 pro max 256G',
 'Apple - iPhone 17 Pro Max كالجديد بدون خدش',
 'iPhone 17 Pro Max-256GB perfect condition',
 'iphone 17 pro max with box and cable',
 'iPhone 17 Pro Max خطين فعلي بطاريه ٩٦ بالعلبه معفي ضرايب',
 'Apple - iPhone 17 Pro Max battery 98% still in warranty']

Title Normalization

In [331]:
df["title_normalized"] = df["title"].str.lower().str.strip()

In [332]:
df[["title", "title_normalized"]].head(20)

,title,title_normalized
0,ايفون 13 iPhone,ايفون 13 iphone
1,Honor Magic V5,honor magic v5
2,OPPO Find X9 Pro ضمان محلي للبيع او البدل,oppo find x9 pro ضمان محلي للبيع او البدل
3,Honor Robot Phone 512G 12G ram,honor robot phone 512g 12g ram
4,شاومي 17 الترا xiaomi 17 ultra,شاومي 17 الترا xiaomi 17 ultra
5,Apple - iPhone 17 Pro,apple - iphone 17 pro
6,للبيع iPhone 15 Pro 1TB_ايفون 15 برو_زيرو بسعر...,للبيع iphone 15 pro 1tb_ايفون 15 برو_زيرو بسعر...
7,Honor 500 pro,honor 500 pro
8,ايفون 11 بحاله الزيرو (iphone11) - سعر لقطه لل...,ايفون 11 بحاله الزيرو (iphone11) - سعر لقطه لل...
9,آبل - آيفون 15 برو ماكس,آبل - آيفون 15 برو ماكس
10,Huawei nova 15 max,huawei nova 15 max
11,ايفون 16e جديد وارد الامارات مدفوع ضريبة | iPh...,ايفون 16e جديد وارد الامارات مدفوع ضريبة | iph...
12,Oppo Find X5 5G dual sim 256/8G Black بحالة مم...,oppo find x5 5g dual sim 256/8g black بحالة مم...
13,Samsung S24 Ultra زيرو 256GB تيتانيوم مدفوع ال...,samsung s24 ultra زيرو 256gb تيتانيوم مدفوع ال...
14,آبل - آيفون 17 برو ماكس,آبل - آيفون 17 برو ماكس
15,آبل - آيفون 13 برو ماكس,آبل - آيفون 13 برو ماكس
16,Honor Magic V5 dual sim 512/16G White Gold جدي...,honor magic v5 dual sim 512/16g white gold جدي...
17,Apple - iPhone 15,apple - iphone 15
18,Samsung S25 Ultra,samsung s25 ultra
19,سامسونج اس 24 الترا,سامسونج اس 24 الترا

Compare Unique Titles

In [333]:
print("Original unique titles:", df["title"].nunique())
print("Normalized unique titles:", df["title_normalized"].nunique())

Original unique titles: 3700
Normalized unique titles: 3565

Normalize Arabic Letter Variants

In [334]:
df["title_normalized"] = (df["title_normalized"]
    .str.replace("أ" , "ا", regex=False)
    .str.replace("إ" , "ا", regex=False)
    .str.replace("آ" , "ا", regex=False)
    .str.replace("ى" , "ي", regex=False)
)

Compare Normalized Titles

In [335]:
df["title_normalized"].nunique()

3551

Inspect Title Punctuation

In [336]:
df["title_normalized"].head(20).to_list()

['ايفون 13 iphone',
 'honor magic v5',
 'oppo find x9 pro ضمان محلي للبيع او البدل',
 'honor robot phone 512g 12g ram',
 'شاومي 17 الترا xiaomi 17 ultra',
 'apple - iphone 17 pro',
 'للبيع iphone 15 pro 1tb_ايفون 15 برو_زيرو بسعر لقطة لسرعه البيع ممتاز',
 'honor 500 pro',
 'ايفون 11 بحاله الزيرو (iphone11) - سعر لقطه للجادين للسرعه البيع 64 gb',
 'ابل - ايفون 15 برو ماكس',
 'huawei nova 15 max',
 'ايفون 16e جديد وارد الامارات مدفوع ضريبة | iphone 16e phone new',
 'oppo find x5 5g dual sim 256/8g black بحالة ممتازة',
 'samsung s24 ultra زيرو 256gb تيتانيوم مدفوع الضريبة بالضمان',
 'ابل - ايفون 17 برو ماكس',
 'ابل - ايفون 13 برو ماكس',
 'honor magic v5 dual sim 512/16g white gold جديد بضمان الوكيل',
 'apple - iphone 15',
 'samsung s25 ultra',
 'سامسونج اس 24 الترا']

Punctuation Normalization

In [337]:
df["title_punct_normalized"] = (
    df["title_normalized"]
    .str.replace("-", " ", regex=False)
    .str.replace("_", " ", regex=False)
    .str.strip()
    .str.split()
    .str.join(" ")
)

Compare Titles After Punctuation Normalization

In [338]:
print("Before:", df["title_normalized"].nunique())
print("After:", df["title_punct_normalized"].nunique())

Before: 3551
After: 3531

Review Normalized Titles

In [339]:
df[["title", "title_normalized", "title_punct_normalized"]].head(10)

,title,title_normalized,title_punct_normalized
0,ايفون 13 iPhone,ايفون 13 iphone,ايفون 13 iphone
1,Honor Magic V5,honor magic v5,honor magic v5
2,OPPO Find X9 Pro ضمان محلي للبيع او البدل,oppo find x9 pro ضمان محلي للبيع او البدل,oppo find x9 pro ضمان محلي للبيع او البدل
3,Honor Robot Phone 512G 12G ram,honor robot phone 512g 12g ram,honor robot phone 512g 12g ram
4,شاومي 17 الترا xiaomi 17 ultra,شاومي 17 الترا xiaomi 17 ultra,شاومي 17 الترا xiaomi 17 ultra
5,Apple - iPhone 17 Pro,apple - iphone 17 pro,apple iphone 17 pro
6,للبيع iPhone 15 Pro 1TB_ايفون 15 برو_زيرو بسعر...,للبيع iphone 15 pro 1tb_ايفون 15 برو_زيرو بسعر...,للبيع iphone 15 pro 1tb ايفون 15 برو زيرو بسعر...
7,Honor 500 pro,honor 500 pro,honor 500 pro
8,ايفون 11 بحاله الزيرو (iphone11) - سعر لقطه لل...,ايفون 11 بحاله الزيرو (iphone11) - سعر لقطه لل...,ايفون 11 بحاله الزيرو (iphone11) سعر لقطه للجا...
9,آبل - آيفون 15 برو ماكس,ابل - ايفون 15 برو ماكس,ابل ايفون 15 برو ماكس

Improve Punctuation Normalization

In [340]:
df["title_punct_normalized"] = (
    df["title_normalized"]
    .str.replace("-", " ", regex=False)
    .str.replace("_", " ", regex=False)
    .str.strip()
)

In [341]:
df.loc[df["title_normalized"] != df["title_punct_normalized"],["title_normalized", "title_punct_normalized"]].head(10)

,title_normalized,title_punct_normalized
5,apple - iphone 17 pro,apple iphone 17 pro
6,للبيع iphone 15 pro 1tb_ايفون 15 برو_زيرو بسعر...,للبيع iphone 15 pro 1tb ايفون 15 برو زيرو بسعر...
8,ايفون 11 بحاله الزيرو (iphone11) - سعر لقطه لل...,ايفون 11 بحاله الزيرو (iphone11) سعر لقطه لل...
9,ابل - ايفون 15 برو ماكس,ابل ايفون 15 برو ماكس
14,ابل - ايفون 17 برو ماكس,ابل ايفون 17 برو ماكس
15,ابل - ايفون 13 برو ماكس,ابل ايفون 13 برو ماكس
17,apple - iphone 15,apple iphone 15
21,apple - iphone 17 pro max,apple iphone 17 pro max
22,apple - iphone 14,apple iphone 14
26,apple - iphone 17 pro max 512 gb,apple iphone 17 pro max 512 gb

In [342]:
print("Before:", df["title_normalized"].nunique())
print("After:", df["title_punct_normalized"].nunique())

Before: 3551
After: 3551

Normalize Extra Spaces

In [343]:
df["title_punct_normalized"] = (
    df["title_punct_normalized"]
    .str.split()
    .str.join(" ")
)

In [344]:
df["title_punct_normalized"].head(20).to_list()

['ايفون 13 iphone',
 'honor magic v5',
 'oppo find x9 pro ضمان محلي للبيع او البدل',
 'honor robot phone 512g 12g ram',
 'شاومي 17 الترا xiaomi 17 ultra',
 'apple iphone 17 pro',
 'للبيع iphone 15 pro 1tb ايفون 15 برو زيرو بسعر لقطة لسرعه البيع ممتاز',
 'honor 500 pro',
 'ايفون 11 بحاله الزيرو (iphone11) سعر لقطه للجادين للسرعه البيع 64 gb',
 'ابل ايفون 15 برو ماكس',
 'huawei nova 15 max',
 'ايفون 16e جديد وارد الامارات مدفوع ضريبة | iphone 16e phone new',
 'oppo find x5 5g dual sim 256/8g black بحالة ممتازة',
 'samsung s24 ultra زيرو 256gb تيتانيوم مدفوع الضريبة بالضمان',
 'ابل ايفون 17 برو ماكس',
 'ابل ايفون 13 برو ماكس',
 'honor magic v5 dual sim 512/16g white gold جديد بضمان الوكيل',
 'apple iphone 15',
 'samsung s25 ultra',
 'سامسونج اس 24 الترا']

Inspect Remaining Punctuation

In [345]:
df.loc[df["title_punct_normalized"].str.contains(r"[|()]", regex=True, na=False), ["title", "title_punct_normalized"]].head(10)

,title,title_punct_normalized
8,ايفون 11 بحاله الزيرو (iphone11) - سعر لقطه لل...,ايفون 11 بحاله الزيرو (iphone11) سعر لقطه للجا...
11,ايفون 16e جديد وارد الامارات مدفوع ضريبة | iPh...,ايفون 16e جديد وارد الامارات مدفوع ضريبة | iph...
40,موبايل Samsung S23 Ultra مستعمل (256GB / 12GB ...,موبايل samsung s23 ultra مستعمل (256gb / 12gb ...
43,Apple iPhone 17 Pro Max (512GB) كسر زيرو | خال...,apple iphone 17 pro max (512gb) كسر زيرو | خال...
72,Infinix smart 20 (4+4/64) جديد,infinix smart 20 (4+4/64) جديد
196,ايفون ١٦ بلس (iphone 16 plus),ايفون ١٦ بلس (iphone 16 plus)
327,Apple iPhone 16 Pro (128 g) كسر زيرو | بطارية ...,apple iphone 16 pro (128 g) كسر زيرو | بطارية ...
527,Xiaomi Poco X3 (128/6),xiaomi poco x3 (128/6)
529,جهازين 11pro max (X),جهازين 11pro max (x)
653,iPhone 12 Pro Max (256) zero tax,iphone 12 pro max (256) zero tax

Normalize Arabic and English Digits

In [346]:
digit_map = str.maketrans("٠١٢٣٤٥٦٧٨٩", "0123456789")

df["title_normalized"] = (df["title_normalized"].str.translate(digit_map))

Remove Arabic Diacritics

In [347]:
df["title_normalized"] = (df["title_normalized"].str.replace(r"[\u064B-\u065F\u0670]", "" , regex=True))

In [348]:
df.loc[df["title"].str.contains("[ًٌٍَُِّْ]", na=False),["title", "title_normalized"]].head(10)

,title,title_normalized
354,سامسونج جالاكسي A07 مساحة 128GB رام 6GB - زير...,سامسونج جالاكسي a07 مساحة 128gb رام 6gb - زير...
507,Realme 9i 6/128 بحالة ممتازة جدًا + الكرتونة,realme 9i 6/128 بحالة ممتازة جدا + الكرتونة
746,للبيغ Infinix Smart بحالة ممتازة وبسعر لُقطة!,للبيغ infinix smart بحالة ممتازة وبسعر لقطة!
1499,لقطه العمر هاتف سامسونج جالاكسي ايه 13 ب 3000ج...,لقطه العمر هاتف سامسونج جالاكسي ايه 13 ب 3000ج...
2296,13 عاديً,13 عادي
2443,اوبو رينو 6 5g الفون زي الجديد حرفياً موضح بالصور,اوبو رينو 6 5g الفون زي الجديد حرفيا موضح بالصور
2495,​ فرصة مميزة للبيع: هاتف Infinix Note 50s كسر ...,​ فرصة مميزة للبيع: هاتف infinix note 50s كسر ...
3507,آبل - آيفون 17 برو ماكس زيرو تماماً جديد,ابل - ايفون 17 برو ماكس زيرو تماما جديد
3790,موبايل مختلف وفخم جدًا لعشاق التميز OPPO Find ...,موبايل مختلف وفخم جدا لعشاق التميز oppo find n...
4020,موبل سامسونج ِ30 جيد جدا للبيع,موبل سامسونج 30 جيد جدا للبيع

Compare Unique Titles Before and After Punctuation Normalization

In [349]:
print("Unique normalized titles:", df["title_normalized"].nunique())
print("Unique punctuation-normalized titles:", df["title_punct_normalized"].nunique())

Unique normalized titles: 3521
Unique punctuation-normalized titles: 3531

Rebuild Punctuation-Normalized Titles

In [350]:
df["title_punct_normalized"] = (df["title_normalized"]
    .str.replace(r"[-_]", " ", regex=True)
    .str.split()
    .str.join(" ")
)

In [351]:
df[["title", "brand", "storage_gb", "ram_gb"]].head(20)

,title,brand,storage_gb,ram_gb
0,ايفون 13 iPhone,apple,NaN,NaN
1,Honor Magic V5,honor,NaN,NaN
2,OPPO Find X9 Pro ضمان محلي للبيع او البدل,oppo,NaN,NaN
3,Honor Robot Phone 512G 12G ram,honor,512.0,12.0
4,شاومي 17 الترا xiaomi 17 ultra,xiaomi,NaN,NaN
5,Apple - iPhone 17 Pro,apple,NaN,NaN
6,للبيع iPhone 15 Pro 1TB_ايفون 15 برو_زيرو بسعر...,apple,1024.0,NaN
7,Honor 500 pro,honor,NaN,NaN
8,ايفون 11 بحاله الزيرو (iphone11) - سعر لقطه لل...,apple,64.0,NaN
9,آبل - آيفون 15 برو ماكس,apple,NaN,NaN
10,Huawei nova 15 max,huawei,NaN,NaN
11,ايفون 16e جديد وارد الامارات مدفوع ضريبة | iPh...,apple,NaN,NaN
12,Oppo Find X5 5G dual sim 256/8G Black بحالة مم...,oppo,256.0,8.0
13,Samsung S24 Ultra زيرو 256GB تيتانيوم مدفوع ال...,samsung,256.0,NaN
14,آبل - آيفون 17 برو ماكس,apple,NaN,NaN
15,آبل - آيفون 13 برو ماكس,apple,NaN,NaN
16,Honor Magic V5 dual sim 512/16G White Gold جدي...,honor,512.0,16.0
17,Apple - iPhone 15,apple,NaN,NaN
18,Samsung S25 Ultra,samsung,NaN,NaN
19,سامسونج اس 24 الترا,samsung,NaN,NaN

In [352]:
print("Unique normalized titles:", df["title_normalized"].nunique())
print("Unique punctuation-normalized titles:", df["title_punct_normalized"].nunique())

Unique normalized titles: 3521
Unique punctuation-normalized titles: 3500

In [353]:
df[["title", "title_normalized", "title_punct_normalized"]].sample(10, random_state=42)

,title,title_normalized,title_punct_normalized
6791,فيفو x200 fe,فيفو x200 fe,فيفو x200 fe
7863,اوبو رينو 10 برو,اوبو رينو 10 برو,اوبو رينو 10 برو
3647,شاومي موديل اخر,شاومي موديل اخر,شاومي موديل اخر
7364,Apple - iPhone 17 Pro Max,apple - iphone 17 pro max,apple iphone 17 pro max
5549,آبل - آيفون 14 برو,ابل - ايفون 14 برو,ابل ايفون 14 برو
5584,آبل - آيفون 13,ابل - ايفون 13,ابل ايفون 13
2540,Apple - iPhone 15 Pro Max,apple - iphone 15 pro max,apple iphone 15 pro max
1882,Vivo y19 s Pro,vivo y19 s pro,vivo y19 s pro
970,آبل - آيفون 11 برو ماكس,ابل - ايفون 11 برو ماكس,ابل ايفون 11 برو ماكس
5952,Apple - iPhone 12 Pro Max,apple - iphone 12 pro max,apple iphone 12 pro max

Check for Extra Spaces in Normalized Titles

In [354]:
df["title_punct_normalized"].str.contains(r"\s{2,}", regex=True, na=False).sum()

np.int64(0)

 Verify Final Title Normalization

In [355]:
df[["title", "title_normalized", "title_punct_normalized"]].sample(10, random_state=42)

,title,title_normalized,title_punct_normalized
6791,فيفو x200 fe,فيفو x200 fe,فيفو x200 fe
7863,اوبو رينو 10 برو,اوبو رينو 10 برو,اوبو رينو 10 برو
3647,شاومي موديل اخر,شاومي موديل اخر,شاومي موديل اخر
7364,Apple - iPhone 17 Pro Max,apple - iphone 17 pro max,apple iphone 17 pro max
5549,آبل - آيفون 14 برو,ابل - ايفون 14 برو,ابل ايفون 14 برو
5584,آبل - آيفون 13,ابل - ايفون 13,ابل ايفون 13
2540,Apple - iPhone 15 Pro Max,apple - iphone 15 pro max,apple iphone 15 pro max
1882,Vivo y19 s Pro,vivo y19 s pro,vivo y19 s pro
970,آبل - آيفون 11 برو ماكس,ابل - ايفون 11 برو ماكس,ابل ايفون 11 برو ماكس
5952,Apple - iPhone 12 Pro Max,apple - iphone 12 pro max,apple iphone 12 pro max

Count Unique Titles After Final Normalization

In [356]:
df["title_punct_normalized"].nunique()

3500

Create Final Normalized Title Groups

In [357]:
df["title_group"] = df["title_punct_normalized"]

In [358]:
print("Missing groups:", df["title_group"].isna().sum())
print("Total groups:", df["title_group"].nunique())
print("Total rows:", len(df))

Missing groups: 0
Total groups: 3500
Total rows: 8213

Validate Title Normalization

In [359]:
print("Original unique titles:", df["title"].nunique())
print("Normalized unique titles:", df["title_normalized"].nunique())
print("Final title groups:", df["title_group"].nunique())
print("Missing groups:", df["title_group"].isna().sum())
print("Total rows:", len(df))

Original unique titles: 3700
Normalized unique titles: 3521
Final title groups: 3500
Missing groups: 0
Total rows: 8213

# Grouped Train-Test Split

In [ ]:
from sklearn.model_selection import GroupShuffleSplit

splitter = GroupShuffleSplit(n_splits=1 , test_size=0.20, random_state=42)

train_idx, test_idx = next(splitter.split(df , groups = df["title_group"]))

train_df = df.iloc[train_idx].copy()
test_df = df.iloc[test_idx].copy()

Validate Grouped Split

In [ ]:
train_groups = set(train_df["title_group"])
test_groups = set(test_df["title_group"])

overlap = train_groups.intersection(test_groups)

print("Train rows:", len(train_df))
print("Test rows:", len(test_df))
print("Overlapping groups:", len(overlap))

Train rows: 6417
Test rows: 1796
Overlapping groups: 0

Save Frozen Test Set

In [365]:
from pathlib import Path

output_dir = Path("data/processed")
output_dir.mkdir(parents=True, exist_ok=True)

test_df.to_csv(output_dir / "frozen_test_set.csv",index=False)

train_df.to_csv(output_dir / "train_set.csv",index=False)

In [366]:
print("Train groups:", train_df["title_group"].nunique())
print("Test groups:", test_df["title_group"].nunique())
print("Total groups:", df["title_group"].nunique())

Train groups: 2800
Test groups: 700
Total groups: 3500

In [367]:
print("Saved test rows:", len(test_df))
print("Saved train rows:", len(train_df))
print("Test file exists:", (output_dir / "frozen_test_set.csv").exists())
print("Train file exists:", (output_dir / "train_set.csv").exists())

Saved test rows: 1796
Saved train rows: 6417
Test file exists: True
Train file exists: True

##### GroupKFold Cross-Validation

In [368]:
from sklearn.model_selection import GroupKFold

gkf = GroupKFold(n_splits=5)

for fold, (train_idx, val_idx) in enumerate(
    gkf.split(
        train_df,
        groups=train_df["title_group"]
    ),
    start=1
):
    print(
        f"Fold {fold}: "
        f"Train={len(train_idx)}, "
        f"Validation={len(val_idx)}"
    )

Fold 1: Train=5133, Validation=1284
Fold 2: Train=5133, Validation=1284
Fold 3: Train=5134, Validation=1283
Fold 4: Train=5134, Validation=1283
Fold 5: Train=5134, Validation=1283

In [369]:
for fold, (train_idx, val_idx) in enumerate(gkf.split(train_df,groups=train_df["title_group"]),
    start=1
):
    train_groups = set(train_df.iloc[train_idx]["title_group"])
    val_groups = set(train_df.iloc[val_idx]["title_group"])

    overlap = train_groups.intersection(val_groups)

    print(f"Fold {fold}: Overlapping groups = {len(overlap)}")

Fold 1: Overlapping groups = 0
Fold 2: Overlapping groups = 0
Fold 3: Overlapping groups = 0
Fold 4: Overlapping groups = 0
Fold 5: Overlapping groups = 0