# استخراج مفاتيح موديلات الهواتف

In [2]:
from pathlib import Path
import sys

project_root = Path.cwd()
if project_root.name == "notebooks":
    project_root = project_root.parent

sys.path.insert(0, str(project_root))
print(project_root)

c:\Users\user\DEPI-GRADUATION-PROJECT

In [12]:
import pandas as pd

In [7]:
import sys
from pathlib import Path

project_root = Path.cwd()
sys.path.insert(0, str(project_root))

## 1. تحميل بيانات التدريب

In [11]:
train_path = Path("../data/processed/train_set.csv")
print("path:", train_path.resolve())
print("here????", train_path.exists())

path: C:\Users\user\DEPI-GRADUATION-PROJECT\data\processed\train_set.csv
here???? True

In [14]:
train_df = pd.read_csv(train_path)
print(train_df.shape)
train_df[["title", "brand"]].head()

(5258, 33)

                            title   brand
0                  Honor Magic V5   honor
1  شاومي 17 الترا xiaomi 17 ultra  xiaomi
2           Apple - iPhone 17 Pro   apple
3                   Honor 500 pro   honor
4         آبل - آيفون 15 برو ماكس   apple

In [15]:
train_path = Path("../data/processed/train_set.csv")
train_df = pd.read_csv(train_path)
stage1_df = train_df.copy()

In [16]:
stage1_df

,title,price,location,ad_url,ad_id,run_id,brand,storage_gb,ram_gb,storage_src,...,is_feature_phone_hint,price_placeholder,loc_area,loc_city,price_missing,price_suspicious,price_very_high,title_normalized,title_punct_normalized,title_group
0,Honor Magic V5,80000.0,اوبن اير مول، مدينتي,/ad/honor-magic-v5-ID209010621.html,209010621,legacy,honor,NaN,NaN,NaN,...,False,False,اوبن اير مول,مدينتي,False,False,False,honor magic v5,honor magic v5,honor magic v5
1,شاومي 17 الترا xiaomi 17 ultra,70000.0,التجمع الخامس، القاهرة الجديدة,/ad/%D8%B4%D8%A7%D9%88%D9%85%D9%8A-17-%D8%A7%D...,208281312,legacy,xiaomi,NaN,NaN,NaN,...,False,False,التجمع الخامس,القاهرة الجديدة,False,False,False,شاومي17الترا xiaomi17ultra,شاومي17الترا xiaomi17ultra,شاومي17الترا xiaomi17ultra
2,Apple - iPhone 17 Pro,75000.0,محور 26 يوليو، 6 اكتوبر,/ad/apple-iphone-17-pro-ID208973056.html,208973056,legacy,apple,NaN,NaN,NaN,...,False,False,محور 26 يوليو,6 اكتوبر,False,False,False,apple iphone17pro,apple iphone17pro,apple iphone17pro
3,Honor 500 pro,35000.0,6 اكتوبر، الجيزة,/ad/honor-500-pro-ID208029599.html,208029599,legacy,honor,NaN,NaN,NaN,...,False,False,6 اكتوبر,الجيزة,False,False,False,honor500pro,honor500pro,honor500pro
4,آبل - آيفون 15 برو ماكس,58000.0,ستيلا هليوبوليس، مدينة الشروق,/ad/%D8%A2%D8%A8%D9%84-%D8%A2%D9%8A%D9%81%D9%8...,208989761,legacy,apple,NaN,NaN,NaN,...,False,False,ستيلا هليوبوليس,مدينة الشروق,False,False,False,ابل ايفون15برو ماكس,ابل ايفون15برو ماكس,ابل ايفون15برو ماكس
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5253,oppo Reno 5,7000.0,ذات، 6 اكتوبر,/ad/oppo-reno-5-ID204026091.html,204026091,legacy,oppo,NaN,NaN,NaN,...,False,False,ذات,6 اكتوبر,False,False,False,oppo reno5,oppo reno5,oppo reno5
5254,آبل - آيفون 12,13000.0,شارع فاروق، الزقازيق,/ad/%D8%A2%D8%A8%D9%84-%D8%A2%D9%8A%D9%81%D9%8...,208942278,legacy,apple,NaN,NaN,NaN,...,False,False,شارع فاروق,الزقازيق,False,False,False,ابل ايفون12,ابل ايفون12,ابل ايفون12
5255,آبل - آيفون 11 برو ماكس,22000.0,الخصوص، القليوبية,/ad/%D8%A2%D8%A8%D9%84-%D8%A2%D9%8A%D9%81%D9%8...,208942276,legacy,apple,NaN,NaN,NaN,...,False,False,الخصوص,القليوبية,False,False,False,ابل ايفون11برو ماكس,ابل ايفون11برو ماكس,ابل ايفون11برو ماكس
5256,iphone 17,58000.0,طنطا، الغربية,/ad/iphone-17-ID208942264.html,208942264,legacy,apple,NaN,NaN,NaN,...,False,False,طنطا,الغربية,False,False,False,iphone17,iphone17,iphone17
5257,Honor Robot phone,92000.0,ميدان الساعة، مدينة نصر,/ad/honor-robot-phone-ID208817348.html,208817348,legacy,honor,NaN,NaN,NaN,...,False,False,ميدان الساعة,مدينة نصر,False,False,False,honor robot phone,honor robot phone,honor robot phone

## 2. تحميل مجموعة الجولد

In [18]:
gold_path = Path("../data/labels/gold_set_Aya.csv")
print( gold_path.exists())

gold_df = pd.read_csv(gold_path)
print( gold_df.shape)
gold_df[["title", "brand", "gold_model_key"]].head()

True
(200, 8)

,title,brand,gold_model_key
0,ايفون اير نسخه الالمانيه مدفوع الضريبه ماشا ال...,apple,apple iphone air
1,iPhone 12 pro ايفون ١٢ برو,apple,apple iphone 12 pro
2,آبل - آيفون 13,apple,apple iphone 13
3,iPhone 16 Pro Max,apple,apple iphone 16 pro max
4,آبل - آيفون 13 برو ماكس,apple,apple iphone 13 pro max

In [19]:
print(gold_df.columns.tolist())

['ad_id', 'title', 'brand', 'gold_model_key', 'review_notes', 'predicted_model_key', 'predicted_match_rule', 'confidence']

In [ ]:
gold_df["gold_model_key"].notna().sum() # sum of NaN

np.int64(200)

### مراجعة قاعدة Samsung من الدفتر السابق

In [29]:

sys.path.insert(0, str(Path.cwd().parent))

from src.preprocessing.model_keys import extract_brand_model

print(extract_brand_model("Samsung Galaxy A54", "samsung"))

samsung a54

#### فحص نتائج Samsung

In [30]:
samsung_gold = gold_df.loc[
    gold_df["brand"] == "samsung"
].copy()

In [34]:
samsung_gold["my_prediction"]=samsung_gold["title"].apply(
    lambda title : extract_brand_model(title,'samsung')
                                                             )

In [35]:
display(
    samsung_gold[
        ["title", "gold_model_key", "my_prediction"]
    ].head(10)
)

,title,gold_model_key,my_prediction
91,Samsung S26 Ultra,samsung s26 ultra,samsung s26 ultra
92,Samsung A52,samsung a52,samsung a52
93,سامسونج ايه 30,samsung a30,samsung a30
94,Galaxy M55 5G 256,samsung m55,samsung m55
95,سامسونج اس 25 الترا,samsung s25 ultra,samsung s25 ultra
96,سامسونج ايه 30,samsung a30,samsung a30
97,Samsung galagxy s25 ultra,samsung s25 ultra,samsung s25 ultra
98,Galaxy Z Fold 7 dual sim 512G Blue جديد متبرشم,samsung z fold7,samsung z fold7
99,سامسونج ايه 37,samsung a37,samsung a37
100,سامسونج ايه 23,samsung a23,samsung a23

In [37]:
"""Erros"""


samsung_errors = samsung_gold.loc[
    samsung_gold["my_prediction"] != samsung_gold["gold_model_key"],
    ["title", "gold_model_key", "my_prediction"]
]

In [48]:
print(f"Errors: {len(samsung_errors)}") # عدد الاختلافات هنا بيساوي = 1

Errors: 1

In [49]:
display(samsung_errors)

                 title gold_model_key  my_prediction
112  سامسونج موديل اخر        unknown  samsung other

In [54]:
stage1_df['brand'].value_counts()

brand
apple       2416
samsung      984
xiaomi       380
oppo         325
realme       187
honor        181
infinix      144
vivo         131
huawei       114
motorola      24
oneplus       18
zte           17
google        17
tecno         15
sony           8
itel           7
nokia          5
lenovo         4
lg             2
Name: count, dtype: int64

#### فحص نتائج Apple

In [ ]:
import importlib
from src.preprocessing import model_keys

importlib.reload(model_keys)

gold_df["my_prediction"] = gold_df.apply(
    lambda row: model_keys.predict_model_key(row["title"], row["brand"]),
    axis=1
)

display(gold_df[["brand", "title", "gold_model_key", "my_prediction"]].head(10))

In [59]:
apple_errors = gold_df.loc[
    (gold_df["brand"] == "apple")
    & (gold_df["my_prediction"] != gold_df["gold_model_key"]),
    ["title", "gold_model_key", "my_prediction"]
]

In [60]:
apple_errors

,title,gold_model_key,my_prediction
0,ايفون اير نسخه الالمانيه مدفوع الضريبه ماشا ال...,apple iphone air,unknown
53,آبل - آيفون 4 اس,apple iphone 4s,apple iphone 4
62,آبل - آيفون 13 ميني,apple iphone 13 mini,apple iphone 13
64,لو عندك ايفون 14 او 15 او 16 او 17 وعاوز تبيعو...,unknown,apple iphone 14

#### فحص نتائج Xiaomi

In [63]:
xiaomi_gold = gold_df.loc[
    gold_df["brand"] == "xiaomi"
].copy()

xiaomi_errors = xiaomi_gold.loc[
    xiaomi_gold["my_prediction"] != xiaomi_gold["gold_model_key"],
    ["title", "gold_model_key", "my_prediction"]
]

In [64]:
len(xiaomi_errors)

2

In [62]:
xiaomi_errors

                        title          gold_model_key       my_prediction
128  تليفون Poco x3 nfc 8/128      xiaomi poco x3 nfc      xiaomi poco x3
140           Poco x8 pro max  xiaomi poco x8 pro max  xiaomi poco x8 pro

#### فحص نتائج OPPO

In [67]:
oppo_gold = gold_df.loc[
    gold_df["brand"] == "oppo"
].copy()

oppo_errors = oppo_gold.loc[
    oppo_gold["my_prediction"] != oppo_gold["gold_model_key"],
    ["title", "gold_model_key", "my_prediction"]
]

In [66]:
oppo_errors

Empty DataFrame
Columns: [title, gold_model_key, my_prediction]
Index: []

### فحص بقية الشركات

In [68]:
def review_brand(brand_name):
    brand_gold = gold_df.loc[
        gold_df["brand"] == brand_name
    ].copy()

    brand_errors = brand_gold.loc[
        brand_gold["my_prediction"] != brand_gold["gold_model_key"],
        ["title", "gold_model_key", "my_prediction"]
    ]

    print("Brand:", brand_name)
    print("len:", len(brand_gold))
    print("Errors:", len(brand_errors))
    display(brand_errors)

In [69]:
review_brand("realme")

Brand: realme
len: 7
Errors: 1

              title  gold_model_key my_prediction
167  realme c85 pro  realme c85 pro    realme c85

In [70]:
review_brand("honor")

Brand: honor
len: 6
Errors: 1

                   title   gold_model_key my_prediction
173  هونر اكس 9 سى سمارت  honor x9c smart     honor x9c

In [71]:
review_brand("infinix")

Brand: infinix
len: 5
Errors: 0

Empty DataFrame
Columns: [title, gold_model_key, my_prediction]
Index: []

In [72]:
review_brand("vivo")

Brand: vivo
len: 4
Errors: 2

                title    gold_model_key  my_prediction
183  Vivo V60 lite 5g  vivo v60 lite 5g  vivo v60 lite
185      vivo v40 ite     vivo v40 lite       vivo v40

In [73]:
review_brand("huawei")

Brand: huawei
len: 4
Errors: 1

,title,gold_model_key,my_prediction
187,هواوى نوفا ماكس استعمال 10 ايام بالفاتورة والض...,huawei nova max,unknown

In [74]:
review_brand("motorola")

Brand: motorola
len: 1
Errors: 0

Empty DataFrame
Columns: [title, gold_model_key, my_prediction]
Index: []

In [75]:
review_brand("oneplus")

Brand: oneplus
len: 1
Errors: 0

Empty DataFrame
Columns: [title, gold_model_key, my_prediction]
Index: []

In [76]:
review_brand("oneplus")

Brand: oneplus
len: 1
Errors: 0

Empty DataFrame
Columns: [title, gold_model_key, my_prediction]
Index: []

In [77]:
review_brand("zte")

Brand: zte
len: 1
Errors: 0

Empty DataFrame
Columns: [title, gold_model_key, my_prediction]
Index: []

In [79]:
review_brand("google")

Brand: google
len: 1
Errors: 1

,title,gold_model_key,my_prediction
193,Google Pixel 11 Pro Fold 16g 256g Black New,google pixel 11 pro fold,google 11 pro fold

In [80]:
review_brand("tecno")

Brand: tecno
len: 1
Errors: 0

Empty DataFrame
Columns: [title, gold_model_key, my_prediction]
Index: []

In [81]:
review_brand("sony")

Brand: sony
len: 1
Errors: 0

Empty DataFrame
Columns: [title, gold_model_key, my_prediction]
Index: []

In [82]:
review_brand("itel")

Brand: itel
len: 1
Errors: 0

Empty DataFrame
Columns: [title, gold_model_key, my_prediction]
Index: []

In [84]:
review_brand("nokia")

Brand: nokia
len: 1
Errors: 0

Empty DataFrame
Columns: [title, gold_model_key, my_prediction]
Index: []

In [85]:
review_brand("nokia")

Brand: nokia
len: 1
Errors: 0

Empty DataFrame
Columns: [title, gold_model_key, my_prediction]
Index: []

In [86]:
review_brand("lenovo")

Brand: lenovo
len: 1
Errors: 0

Empty DataFrame
Columns: [title, gold_model_key, my_prediction]
Index: []

In [87]:
review_brand("lg")

Brand: lg
len: 1
Errors: 0

Empty DataFrame
Columns: [title, gold_model_key, my_prediction]
Index: []

## 3. تحديث القواعد بناءً على الأخطاء

In [90]:
"""
 here iam fix orignal file "model_keys.py"
"""

'\n here iam fix orignal file "model_keys.py"\n'

In [91]:
import importlib
from src.preprocessing import model_keys

importlib.reload(model_keys)

gold_df["my_prediction"] = gold_df.apply(
    lambda row: model_keys.predict_model_key(row["title"], row["brand"]),
    axis=1
)

In [92]:
gold_df["my_prediction"]

0             apple iphone air
1          apple iphone 12 pro
2              apple iphone 13
3      apple iphone 16 pro max
4      apple iphone 13 pro max
                ...
195                 sony st15i
196                   itel a90
197                   nokia x2
198            lenovo k12 note
199                      lg g6
Name: my_prediction, Length: 200, dtype: object

In [97]:
errors = gold_df.loc[
    gold_df["my_prediction"] != gold_df["gold_model_key"],
    ["brand", "title", "gold_model_key", "my_prediction"]
]

print("Errors:", len(errors))
display(errors)

Errors: 5

,brand,title,gold_model_key,my_prediction
154,NaN,Mi 17 Ultra dual sim 512/1TB Black جديد متبرشم...,xiaomi 17 ultra,unknown
156,NaN,Turbo 4 pro كسر زيرو,xiaomi redmi turbo 4 pro,unknown
157,NaN,لبيع ميت تن لايت,huawei mate 10 lite,unknown
159,NaN,17 Pro Max,apple iphone 17 pro max,unknown
160,NaN,Mate 30 pro 5g,huawei mate 30 pro 5g,unknown

In [100]:
print(float(len(errors)/len(gold_df["my_prediction"])) *100)

2.5

## 4. تقييم القواعد على مجموعة الجولد

In [103]:
import importlib
from src.preprocessing import model_keys

In [106]:
gold_pairs = gold_df.apply(
    lambda row: model_keys.predict_model_key(
        row["title"],
        row["brand"],
        with_rule=True
    ),
    axis=1
)

In [107]:
gold_df[["my_prediction", "match_rule"]] = pd.DataFrame(
    gold_pairs.tolist(),
    index=gold_df.index
)

In [110]:
display(gold_df[["brand", "title", "my_prediction", "match_rule"]].head(10)) # بعد ما عدلت في الملف الاخر و ضيفت  enumrate علشان اعرف انهب case هي الي عامله المشكله

,brand,title,my_prediction,match_rule
0,apple,ايفون اير نسخه الالمانيه مدفوع الضريبه ماشا ال...,apple iphone air,apple:special_case_01
1,apple,iPhone 12 pro ايفون ١٢ برو,apple iphone 12 pro,apple:model_pattern_06
2,apple,آبل - آيفون 13,apple iphone 13,apple:fallback_pattern
3,apple,iPhone 16 Pro Max,apple iphone 16 pro max,apple:model_pattern_01
4,apple,آبل - آيفون 13 برو ماكس,apple iphone 13 pro max,apple:model_pattern_02
5,apple,آبل - آيفون 13,apple iphone 13,apple:fallback_pattern
6,apple,Apple - iPhone 13,apple iphone 13,apple:numeric_pattern
7,apple,Apple - iPhone 15 plus,apple iphone 15 plus,apple:model_pattern_03
8,apple,آبل - آيفون 17 برو ماكس هاي كوبي ١٠٠٠ جيجا,apple iphone 17 pro max,apple:model_pattern_02
9,apple,آبل - آيفون 17 برو ماكس فرست هاي كوبي,apple iphone 17 pro max,apple:model_pattern_02

In [111]:
scored_gold = gold_df.loc[
    gold_df["my_prediction"] != "unknown"
].copy()

In [112]:
scored_gold["is_correct"] = (
    scored_gold["my_prediction"] == scored_gold["gold_model_key"]
)

In [113]:
rule_stats = scored_gold.groupby("match_rule").agg(
    support=("is_correct", "size"),
    correct=("is_correct", "sum")
)

In [114]:
rule_stats["confidence"] = (
    rule_stats["correct"] / rule_stats["support"]
).where(rule_stats["support"] >= 5)

In [115]:
gold_df["confidence"] = gold_df["match_rule"].map(
    rule_stats["confidence"]
)

In [117]:
gold_df["is_correct"] = (
    gold_df["my_prediction"] == gold_df["gold_model_key"]
)

display(
    gold_df[
        ["gold_model_key", "my_prediction", "match_rule", "is_correct"]
    ].head(10)
)

,gold_model_key,my_prediction,match_rule,is_correct
0,apple iphone air,apple iphone air,apple:special_case_01,True
1,apple iphone 12 pro,apple iphone 12 pro,apple:model_pattern_06,True
2,apple iphone 13,apple iphone 13,apple:fallback_pattern,True
3,apple iphone 16 pro max,apple iphone 16 pro max,apple:model_pattern_01,True
4,apple iphone 13 pro max,apple iphone 13 pro max,apple:model_pattern_02,True
5,apple iphone 13,apple iphone 13,apple:fallback_pattern,True
6,apple iphone 13,apple iphone 13,apple:numeric_pattern,True
7,apple iphone 15 plus,apple iphone 15 plus,apple:model_pattern_03,True
8,apple iphone 17 pro max,apple iphone 17 pro max,apple:model_pattern_02,True
9,apple iphone 17 pro max,apple iphone 17 pro max,apple:model_pattern_02,True

In [118]:
scored_gold = gold_df.loc[
    gold_df["my_prediction"] != "unknown"
].copy()

rule_stats = scored_gold.groupby("match_rule").agg(
    support=("is_correct", "size"),
    correct=("is_correct", "sum")
)

display(rule_stats)

                        support  correct
match_rule
apple:fallback_pattern       14       14
apple:model_pattern_01       13       13
apple:model_pattern_02       23       23
apple:model_pattern_03        1        1
apple:model_pattern_04        2        2
apple:model_pattern_05        2        2
apple:model_pattern_06        8        8
apple:model_pattern_07        4        4
apple:numeric_pattern        12       12
apple:special_case_01         1        1
apple:special_case_02         1        1
apple:special_case_09         2        2
apple:special_model_01        2        2
apple:special_model_02        1        1
apple:special_model_03        1        1
apple:special_model_04        1        1
google:rule_01                1        1
honor:rule_01                 1        1
honor:rule_06                 3        3
honor:rule_07                 2        2
huawei:rule_03                1        1
huawei:rule_08                1        1
huawei:rule_14                1        1
huawei:rule_16                1        1
infinix:rule_01               1        1
infinix:rule_04               1        1
infinix:rule_09               1        1
infinix:rule_10               1        1
infinix:rule_11               1        1
itel:rule_05                  1        1
lenovo:rule_03                1        1
lg:rule_05                    1        1
motorola:rule_10              1        1
nokia:rule_06                 1        1
oneplus:rule_05               1        1
oppo:rule_02                  1        1
oppo:rule_05                  6        6
oppo:rule_06                  4        4
realme:rule_07                1        1
realme:rule_08                4        4
realme:rule_13                1        1
realme:rule_14                1        1
samsung:rule_02               2        2
samsung:rule_07               1        1
samsung:rule_08               1        1
samsung:rule_13               3        3
samsung:rule_14              10       10
samsung:rule_15               1        1
samsung:rule_16              17       17
samsung:rule_19               1        1
sony:rule_06                  1        1
tecno:rule_12                 1        1
vivo:rule_05                  2        2
xiaomi:rule_02                5        5
xiaomi:rule_04                1        1
xiaomi:rule_06                3        3
xiaomi:rule_08                3        3
xiaomi:rule_15                1        1
xiaomi:rule_17                1        1
zte:rule_01                   1        1

In [119]:
rule_stats["confidence"] = (
    rule_stats["correct"] / rule_stats["support"]
).where(rule_stats["support"] >= 5)

gold_df["confidence"] = gold_df["match_rule"].map(
    rule_stats["confidence"]
)

In [120]:
rule_stats["confidence"]

match_rule
apple:fallback_pattern    1.0
apple:model_pattern_01    1.0
apple:model_pattern_02    1.0
apple:model_pattern_03    NaN
apple:model_pattern_04    NaN
apple:model_pattern_05    NaN
apple:model_pattern_06    1.0
apple:model_pattern_07    NaN
apple:numeric_pattern     1.0
apple:special_case_01     NaN
apple:special_case_02     NaN
apple:special_case_09     NaN
apple:special_model_01    NaN
apple:special_model_02    NaN
apple:special_model_03    NaN
apple:special_model_04    NaN
google:rule_01            NaN
honor:rule_01             NaN
honor:rule_06             NaN
honor:rule_07             NaN
huawei:rule_03            NaN
huawei:rule_08            NaN
huawei:rule_14            NaN
huawei:rule_16            NaN
infinix:rule_01           NaN
infinix:rule_04           NaN
infinix:rule_09           NaN
infinix:rule_10           NaN
infinix:rule_11           NaN
itel:rule_05              NaN
lenovo:rule_03            NaN
lg:rule_05                NaN
motorola:rule_10          NaN
nokia:rule_06             NaN
oneplus:rule_05           NaN
oppo:rule_02              NaN
oppo:rule_05              1.0
oppo:rule_06              NaN
realme:rule_07            NaN
realme:rule_08            NaN
realme:rule_13            NaN
realme:rule_14            NaN
samsung:rule_02           NaN
samsung:rule_07           NaN
samsung:rule_08           NaN
samsung:rule_13           NaN
samsung:rule_14           1.0
samsung:rule_15           NaN
samsung:rule_16           1.0
samsung:rule_19           NaN
sony:rule_06              NaN
tecno:rule_12             NaN
vivo:rule_05              NaN
xiaomi:rule_02            1.0
xiaomi:rule_04            NaN
xiaomi:rule_06            NaN
xiaomi:rule_08            NaN
xiaomi:rule_15            NaN
xiaomi:rule_17            NaN
zte:rule_01               NaN
Name: confidence, dtype: float64

In [121]:
gold_df["confidence"]

0      NaN
1      1.0
2      1.0
3      1.0
4      1.0
      ...
195    NaN
196    NaN
197    NaN
198    NaN
199    NaN
Name: confidence, Length: 200, dtype: float64

## 5. تطبيق القواعد على بيانات التدريب

In [ ]:
importlib.reload(model_keys)

In [ ]:
train_pairs = train_df.apply(
    lambda row: model_keys.predict_model_key(
        row["title"],
        row["brand"],
        with_rule=True
    ),
    axis=1
)

In [ ]:
train_predictions = pd.DataFrame(
    train_pairs.tolist(),
    columns=["model_key", "match_rule"],
    index=train_df.index
)

stage1_df = train_df.copy()
stage1_df[["model_key", "match_rule"]] = train_predictions
stage1_df["confidence"] = stage1_df["match_rule"].map(
    rule_stats["confidence"]
)

display(
    stage1_df[
        ["brand", "title", "model_key", "match_rule", "confidence"]
    ].head(10)
)

### حفظ ملف النتائج

In [124]:
stage1_df.to_csv(
    "../data/processed/stage1/stage1_model_keys.csv",
    index=False
)